/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ConfigView.java
 *
 * Created on 29-11-2009, 14:32:15
 */
package com.gcs.wb.views;

import com.fazecast.jSerialComm.SerialPort;
import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.model.AppConfig;
import com.gcs.wb.base.enums.ParityEnum;
import com.gcs.wb.base.serials.SerialHelper;
import com.gcs.wb.controller.ConfigController;
import com.gcs.wb.jpa.JPAConnector;
import com.gcs.wb.jpa.entity.Configuration;
import com.gcs.wb.service.SyncMasterDataService;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.apache.commons.configuration.ConfigurationException;
import org.apache.commons.lang.SerializationUtils;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.Task;
import org.jdesktop.swingx.combobox.EnumComboBoxModel;

/**
 *
 * @author Tran-Vu
 */
public class ConfigView extends javax.swing.JDialog {

    private AppConfig config = null;
    private boolean validFormDB = false;
    private boolean validForm = false;
    public ConfigController configController = new ConfigController();
    ResourceMap resourceMap = Application.getInstance(WeighBridgeApp.class).getContext().getResourceMap(ConfigView.class);
    private DefaultComboBoxModel port1Model = null;
    private DefaultComboBoxModel port2Model = null;
    public static Logger logger = Logger.getLogger(ConfigView.class);

    // <editor-fold defaultstate="collapsed" desc="Class Constructors">
    /**
     * Creates new form ConfigView
     *
     * @param parent
     */
    public ConfigView(java.awt.Frame parent) {
        super(parent);
        initComponents();
        initController();
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMySQLCon = new javax.swing.JPanel();
        lblDBHost = new javax.swing.JLabel();
        txtDBHost = new javax.swing.JTextField();
        lblDBName = new javax.swing.JLabel();
        txtDBName = new javax.swing.JTextField();
        lblDBUsr = new javax.swing.JLabel();
        txtDBUsr = new javax.swing.JTextField();
        lblDBPwd = new javax.swing.JLabel();
        txtDBPwd = new javax.swing.JPasswordField();
        btnCheckDbConnection = new javax.swing.JButton();
        iconLoading = new org.jdesktop.swingx.JXBusyLabel();
        pnSAPConfig = new javax.swing.JPanel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblSId = new javax.swing.JLabel();
        txtSNo = new javax.swing.JFormattedTextField();
        lblRString = new javax.swing.JLabel();
        txtRString = new javax.swing.JTextField();
        lblDClient = new javax.swing.JLabel();
        txtDClient = new javax.swing.JFormattedTextField();
        lblSapUsername = new javax.swing.JLabel();
        lblSapPassword = new javax.swing.JLabel();
        txtSapUpsername = new javax.swing.JTextField();
        txtSapPassword = new javax.swing.JPasswordField();
        pnWB1Config = new javax.swing.JPanel();
        lblPort1 = new javax.swing.JLabel();
        cbxPort1 = new javax.swing.JComboBox();
        lblSpeed1 = new javax.swing.JLabel();
        cbxSpeed1 = new javax.swing.JComboBox();
        lblDataBits1 = new javax.swing.JLabel();
        cbxDataBits1 = new javax.swing.JComboBox();
        lblStopBits1 = new javax.swing.JLabel();
        cbxStopBits1 = new javax.swing.JComboBox();
        lblPControl1 = new javax.swing.JLabel();
        cbxPControl1 = new javax.swing.JComboBox();
        chbMettler1 = new javax.swing.JCheckBox();
        chbAutoSignal1 = new javax.swing.JCheckBox();
        pnWB2Config = new javax.swing.JPanel();
        lblPort2 = new javax.swing.JLabel();
        cbxPort2 = new javax.swing.JComboBox();
        lblSpeed2 = new javax.swing.JLabel();
        cbxSpeed2 = new javax.swing.JComboBox();
        lblDataBits2 = new javax.swing.JLabel();
        cbxDataBits2 = new javax.swing.JComboBox();
        lblStopBits2 = new javax.swing.JLabel();
        cbxStopBits2 = new javax.swing.JComboBox();
        lblPControl2 = new javax.swing.JLabel();
        cbxPControl2 = new javax.swing.JComboBox();
        chbMettler2 = new javax.swing.JCheckBox();
        chbAutoSignal2 = new javax.swing.JCheckBox();
        pnWorkingPlant = new javax.swing.JPanel();
        lblPlant = new javax.swing.JLabel();
        txtPlant = new javax.swing.JTextField();
        txtWBID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        syncIconLoading = new org.jdesktop.swingx.JXBusyLabel();
        lblSyncData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(ConfigView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnMySQLCon.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnMySQLCon.border.title"))); // NOI18N
        pnMySQLCon.setName("pnMySQLCon"); // NOI18N

        lblDBHost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDBHost.setText(resourceMap.getString("lblDBHost.text")); // NOI18N
        lblDBHost.setName("lblDBHost"); // NOI18N
        lblDBHost.setPreferredSize(new java.awt.Dimension(60, 14));

        txtDBHost.setName("txtDBHost"); // NOI18N
        txtDBHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBHostKeyReleased(evt);
            }
        });

        lblDBName.setText(resourceMap.getString("lblDBName.text")); // NOI18N
        lblDBName.setName("lblDBName"); // NOI18N

        txtDBName.setName("txtDBName"); // NOI18N
        txtDBName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBNameKeyReleased(evt);
            }
        });

        lblDBUsr.setText(resourceMap.getString("lblDBUsr.text")); // NOI18N
        lblDBUsr.setName("lblDBUsr"); // NOI18N

        txtDBUsr.setName("txtDBUsr"); // NOI18N
        txtDBUsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBUsrKeyReleased(evt);
            }
        });

        lblDBPwd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDBPwd.setText(resourceMap.getString("lblDBPwd.text")); // NOI18N
        lblDBPwd.setName("lblDBPwd"); // NOI18N

        txtDBPwd.setName("txtDBPwd"); // NOI18N
        txtDBPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBPwdKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(ConfigView.class, this);
        btnCheckDbConnection.setAction(actionMap.get("checkDbConnection")); // NOI18N
        btnCheckDbConnection.setText(resourceMap.getString("btnCheckDbConnection.text")); // NOI18N
        btnCheckDbConnection.setName("btnCheckDbConnection"); // NOI18N

        iconLoading.setBusy(true);
        iconLoading.setDirection(org.jdesktop.swingx.JXBusyLabel.Direction.RIGHT);
        iconLoading.setName("iconLoading"); // NOI18N

        javax.swing.GroupLayout pnMySQLConLayout = new javax.swing.GroupLayout(pnMySQLCon);
        pnMySQLCon.setLayout(pnMySQLConLayout);
        pnMySQLConLayout.setHorizontalGroup(
            pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMySQLConLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDBUsr)
                    .addComponent(lblDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMySQLConLayout.createSequentialGroup()
                        .addComponent(btnCheckDbConnection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMySQLConLayout.createSequentialGroup()
                        .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDBUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtDBHost, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDBName)
                            .addComponent(lblDBPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDBPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtDBName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnMySQLConLayout.setVerticalGroup(
            pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMySQLConLayout.createSequentialGroup()
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDBUsr)
                    .addComponent(txtDBUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDBPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBPwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckDbConnection)
                    .addComponent(iconLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnSAPConfig.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnSAPConfig.border.title"))); // NOI18N
        pnSAPConfig.setMinimumSize(new java.awt.Dimension(247, 84));
        pnSAPConfig.setName("pnSAPConfig"); // NOI18N

        lblHost.setText(resourceMap.getString("lblHost.text")); // NOI18N
        lblHost.setName("lblHost"); // NOI18N

        txtHost.setName("txtHost"); // NOI18N
        txtHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHostKeyReleased(evt);
            }
        });

        lblSId.setText(resourceMap.getString("lblSId.text")); // NOI18N
        lblSId.setName("lblSId"); // NOI18N

        txtSNo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSNo.setName("txtSNo"); // NOI18N
        txtSNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSNoKeyReleased(evt);
            }
        });

        lblRString.setText(resourceMap.getString("lblRString.text")); // NOI18N
        lblRString.setName("lblRString"); // NOI18N

        txtRString.setName("txtRString"); // NOI18N
        txtRString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRStringKeyReleased(evt);
            }
        });

        lblDClient.setText(resourceMap.getString("lblDClient.text")); // NOI18N
        lblDClient.setName("lblDClient"); // NOI18N

        txtDClient.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDClient.setName("txtDClient"); // NOI18N
        txtDClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDClientKeyReleased(evt);
            }
        });

        lblSapUsername.setText(resourceMap.getString("lblSapUsername.text")); // NOI18N
        lblSapUsername.setName("lblSapUsername"); // NOI18N

        lblSapPassword.setText(resourceMap.getString("lblSapPassword.text")); // NOI18N
        lblSapPassword.setName("lblSapPassword"); // NOI18N

        txtSapUpsername.setText(resourceMap.getString("txtSapUpsername.text")); // NOI18N
        txtSapUpsername.setName("txtSapUpsername"); // NOI18N
        txtSapUpsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSapUpsernameKeyReleased(evt);
            }
        });

        txtSapPassword.setText(resourceMap.getString("txtSapPassword.text")); // NOI18N
        txtSapPassword.setName("txtSapPassword"); // NOI18N
        txtSapPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSapPasswordKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnSAPConfigLayout = new javax.swing.GroupLayout(pnSAPConfig);
        pnSAPConfig.setLayout(pnSAPConfigLayout);
        pnSAPConfigLayout.setHorizontalGroup(
            pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSAPConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRString)
                    .addComponent(lblHost)
                    .addComponent(lblSapUsername)
                    .addComponent(lblSapPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSapPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtSapUpsername, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtRString, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDClient)
                    .addComponent(lblSId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnSAPConfigLayout.setVerticalGroup(
            pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSAPConfigLayout.createSequentialGroup()
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHost)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRString)
                    .addComponent(txtRString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSapUsername)
                    .addComponent(txtSapUpsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSapPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSapPassword))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnWB1Config.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWB1Config.border.title"))); // NOI18N
        pnWB1Config.setMinimumSize(new java.awt.Dimension(230, 170));
        pnWB1Config.setName("pnWB1Config"); // NOI18N

        lblPort1.setText(resourceMap.getString("lblPort1.text")); // NOI18N
        lblPort1.setName("lblPort1"); // NOI18N

        cbxPort1.setEditable(true);
        cbxPort1.setName("cbxPort1"); // NOI18N
        cbxPort1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPort1ItemStateChanged(evt);
            }
        });

        lblSpeed1.setText(resourceMap.getString("lblSpeed1.text")); // NOI18N
        lblSpeed1.setName("lblSpeed1"); // NOI18N

        cbxSpeed1.setModel(getSpeedModel());
        cbxSpeed1.setName("cbxSpeed1"); // NOI18N
        cbxSpeed1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSpeed1ItemStateChanged(evt);
            }
        });

        lblDataBits1.setText(resourceMap.getString("lblDataBits1.text")); // NOI18N
        lblDataBits1.setName("lblDataBits1"); // NOI18N

        cbxDataBits1.setModel(getDBitsModel());
        cbxDataBits1.setName("cbxDataBits1"); // NOI18N
        cbxDataBits1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDataBits1ItemStateChanged(evt);
            }
        });

        lblStopBits1.setText(resourceMap.getString("lblStopBits1.text")); // NOI18N
        lblStopBits1.setName("lblStopBits1"); // NOI18N

        cbxStopBits1.setModel(getSBitsModel());
        cbxStopBits1.setName("cbxStopBits1"); // NOI18N
        cbxStopBits1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxStopBits1ItemStateChanged(evt);
            }
        });

        lblPControl1.setText(resourceMap.getString("lblPControl1.text")); // NOI18N
        lblPControl1.setName("lblPControl1"); // NOI18N

        cbxPControl1.setModel(getParityModel());
        cbxPControl1.setName("cbxPControl1"); // NOI18N
        cbxPControl1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPControl1ItemStateChanged(evt);
            }
        });

        chbMettler1.setText(resourceMap.getString("chbMettler1.text")); // NOI18N
        chbMettler1.setName("chbMettler1"); // NOI18N

        chbAutoSignal1.setSelected(true);
        chbAutoSignal1.setText(resourceMap.getString("chbAutoSignal1.text")); // NOI18N
        chbAutoSignal1.setName("chbAutoSignal1"); // NOI18N

        javax.swing.GroupLayout pnWB1ConfigLayout = new javax.swing.GroupLayout(pnWB1Config);
        pnWB1Config.setLayout(pnWB1ConfigLayout);
        pnWB1ConfigLayout.setHorizontalGroup(
            pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB1ConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPort1)
                    .addComponent(lblSpeed1)
                    .addComponent(lblDataBits1)
                    .addComponent(lblStopBits1)
                    .addComponent(lblPControl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAutoSignal1)
                    .addComponent(chbMettler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSpeed1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPort1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxDataBits1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxStopBits1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPControl1, 0, 165, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWB1ConfigLayout.setVerticalGroup(
            pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB1ConfigLayout.createSequentialGroup()
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort1)
                    .addComponent(cbxPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeed1)
                    .addComponent(cbxSpeed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataBits1)
                    .addComponent(cbxDataBits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopBits1)
                    .addComponent(cbxStopBits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPControl1)
                    .addComponent(cbxPControl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbMettler1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbAutoSignal1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnWB2Config.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWB2Config.border.title"))); // NOI18N
        pnWB2Config.setMinimumSize(new java.awt.Dimension(230, 170));
        pnWB2Config.setName("pnWB2Config"); // NOI18N

        lblPort2.setText(resourceMap.getString("lblPort2.text")); // NOI18N
        lblPort2.setName("lblPort2"); // NOI18N

        cbxPort2.setEditable(true);
        cbxPort2.setName("cbxPort2"); // NOI18N
        cbxPort2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPort2ItemStateChanged(evt);
            }
        });

        lblSpeed2.setText(resourceMap.getString("lblSpeed2.text")); // NOI18N
        lblSpeed2.setName("lblSpeed2"); // NOI18N

        cbxSpeed2.setModel(getSpeedModel());
        cbxSpeed2.setName("cbxSpeed2"); // NOI18N
        cbxSpeed2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSpeed2ItemStateChanged(evt);
            }
        });

        lblDataBits2.setText(resourceMap.getString("lblDataBits2.text")); // NOI18N
        lblDataBits2.setName("lblDataBits2"); // NOI18N

        cbxDataBits2.setModel(getDBitsModel());
        cbxDataBits2.setName("cbxDataBits2"); // NOI18N
        cbxDataBits2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDataBits2ItemStateChanged(evt);
            }
        });

        lblStopBits2.setText(resourceMap.getString("lblStopBits2.text")); // NOI18N
        lblStopBits2.setName("lblStopBits2"); // NOI18N

        cbxStopBits2.setModel(getSBitsModel());
        cbxStopBits2.setName("cbxStopBits2"); // NOI18N
        cbxStopBits2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxStopBits2ItemStateChanged(evt);
            }
        });

        lblPControl2.setText(resourceMap.getString("lblPControl2.text")); // NOI18N
        lblPControl2.setName("lblPControl2"); // NOI18N

        cbxPControl2.setModel(getParityModel());
        cbxPControl2.setName("cbxPControl2"); // NOI18N
        cbxPControl2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPControl2ItemStateChanged(evt);
            }
        });

        chbMettler2.setText(resourceMap.getString("chbMettler2.text")); // NOI18N
        chbMettler2.setName("chbMettler2"); // NOI18N

        chbAutoSignal2.setSelected(true);
        chbAutoSignal2.setText(resourceMap.getString("chbAutoSignal2.text")); // NOI18N
        chbAutoSignal2.setName("chbAutoSignal2"); // NOI18N

        javax.swing.GroupLayout pnWB2ConfigLayout = new javax.swing.GroupLayout(pnWB2Config);
        pnWB2Config.setLayout(pnWB2ConfigLayout);
        pnWB2ConfigLayout.setHorizontalGroup(
            pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB2ConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPort2)
                    .addComponent(lblSpeed2)
                    .addComponent(lblDataBits2)
                    .addComponent(lblStopBits2)
                    .addComponent(lblPControl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAutoSignal2)
                    .addComponent(chbMettler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSpeed2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPort2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxDataBits2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxStopBits2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPControl2, 0, 165, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWB2ConfigLayout.setVerticalGroup(
            pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB2ConfigLayout.createSequentialGroup()
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort2)
                    .addComponent(cbxPort2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeed2)
                    .addComponent(cbxSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataBits2)
                    .addComponent(cbxDataBits2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopBits2)
                    .addComponent(cbxStopBits2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPControl2)
                    .addComponent(cbxPControl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbMettler2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbAutoSignal2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnWorkingPlant.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWorkingPlant.border.title"))); // NOI18N
        pnWorkingPlant.setName("pnWorkingPlant"); // NOI18N
        pnWorkingPlant.setPreferredSize(new java.awt.Dimension(640, 69));

        lblPlant.setText(resourceMap.getString("lblPlant.text")); // NOI18N
        lblPlant.setName("lblPlant"); // NOI18N

        txtPlant.setName("txtPlant"); // NOI18N
        txtPlant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlantKeyReleased(evt);
            }
        });

        txtWBID.setName("txtWBID"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout pnWorkingPlantLayout = new javax.swing.GroupLayout(pnWorkingPlant);
        pnWorkingPlant.setLayout(pnWorkingPlantLayout);
        pnWorkingPlantLayout.setHorizontalGroup(
            pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWorkingPlantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWBID)
                    .addComponent(txtPlant, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWorkingPlantLayout.setVerticalGroup(
            pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWorkingPlantLayout.createSequentialGroup()
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlant)
                    .addComponent(txtPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        btnSave.setAction(actionMap.get("saveConfig")); // NOI18N
        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setMaximumSize(new java.awt.Dimension(85, 23));
        btnSave.setMinimumSize(new java.awt.Dimension(85, 23));
        btnSave.setName("btnSave"); // NOI18N
        btnSave.setPreferredSize(null);

        syncIconLoading.setBusy(true);
        syncIconLoading.setDirection(org.jdesktop.swingx.JXBusyLabel.Direction.RIGHT);
        syncIconLoading.setName("syncIconLoading"); // NOI18N

        lblSyncData.setText(resourceMap.getString("lblSyncData.text")); // NOI18N
        lblSyncData.setName("lblSyncData"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnMySQLCon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnSAPConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnWorkingPlant, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnWB1Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnWB2Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(syncIconLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSyncData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMySQLCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnWorkingPlant, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(pnSAPConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnWB2Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnWB1Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSyncData))
                    .addComponent(syncIconLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // </editor-fold>
    // <editor-fold defaultstate="expaned" desc="Event Handlers">
    private void txtRStringKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRStringKeyReleased
        validateForm();
    }//GEN-LAST:event_txtRStringKeyReleased

    private void cbxPort1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPort1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPort1ItemStateChanged

    private void cbxPort2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPort2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPort2ItemStateChanged

    private void cbxSpeed1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSpeed1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxSpeed1ItemStateChanged

    private void cbxSpeed2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSpeed2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxSpeed2ItemStateChanged

    private void cbxDataBits1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDataBits1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxDataBits1ItemStateChanged

    private void cbxDataBits2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDataBits2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxDataBits2ItemStateChanged

    private void cbxStopBits1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxStopBits1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxStopBits1ItemStateChanged

    private void cbxStopBits2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxStopBits2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxStopBits2ItemStateChanged

    private void cbxPControl1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPControl1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPControl1ItemStateChanged

    private void cbxPControl2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPControl2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPControl2ItemStateChanged

    private void txtSNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNoKeyReleased
        validateForm();
    }//GEN-LAST:event_txtSNoKeyReleased

    private void txtDClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDClientKeyReleased
        validateForm();
    }//GEN-LAST:event_txtDClientKeyReleased

    private void txtDBHostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBHostKeyReleased
        validateFormDB();
        String dbHost = txtDBHost.getText().trim();
        if (!dbHost.equals(config.getDbHost())) {
            setFormEditable(false);
        }
    }//GEN-LAST:event_txtDBHostKeyReleased

    private void txtDBNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBNameKeyReleased
        validateFormDB();
        String dbName = txtDBName.getText().trim();
        if (!dbName.equals(config.getDbName())) {
            setFormEditable(false);
        }
    }//GEN-LAST:event_txtDBNameKeyReleased

    private void txtDBUsrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBUsrKeyReleased
        validateFormDB();
        String dbUser = txtDBUsr.getText().trim();
        if (!dbUser.equals(config.getDbUsername())) {
            setFormEditable(false);
        }
    }//GEN-LAST:event_txtDBUsrKeyReleased

    private void txtDBPwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBPwdKeyReleased
        validateFormDB();
        String dbPass = new String(txtDBPwd.getPassword()).trim();
        if (!dbPass.equals(config.getDbPassword())) {
            setFormEditable(false);
        }
    }//GEN-LAST:event_txtDBPwdKeyReleased

    private void txtHostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostKeyReleased
        validateForm();
    }//GEN-LAST:event_txtHostKeyReleased

    private void txtPlantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlantKeyReleased
        validateForm();
    }//GEN-LAST:event_txtPlantKeyReleased

private void txtSapUpsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSapUpsernameKeyReleased
    validateForm();
}//GEN-LAST:event_txtSapUpsernameKeyReleased

private void txtSapPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSapPasswordKeyReleased
    validateForm();
}//GEN-LAST:event_txtSapPasswordKeyReleased

    private void setFormEditable(boolean editable) {
        txtHost.setEnabled(editable);
        txtRString.setEnabled(editable);
        txtSNo.setEnabled(editable);
        txtDClient.setEnabled(editable);
        txtSapUpsername.setEnabled(editable);
        txtSapPassword.setEnabled(editable);

        txtPlant.setEnabled(editable);
        txtWBID.setEnabled(editable);

        cbxPort1.setEnabled(editable);
        cbxSpeed1.setEnabled(editable);
        cbxDataBits1.setEnabled(editable);
        cbxStopBits1.setEnabled(editable);
        cbxPControl1.setEnabled(editable);
        chbMettler1.setEnabled(editable);
        chbAutoSignal1.setEnabled(editable);

        cbxPort2.setEnabled(editable);
        cbxSpeed2.setEnabled(editable);
        cbxDataBits2.setEnabled(editable);
        cbxStopBits2.setEnabled(editable);
        cbxPControl2.setEnabled(editable);
        chbMettler2.setEnabled(editable);
        chbAutoSignal2.setEnabled(editable);

        if (!editable) {
            btnSave.setEnabled(false);
        } else {
            validateForm();
        }
    }

    private void initController() {
        config = WeighBridgeApp.getApplication().getConfig();
        port1Model = getPortModel();
        port2Model = (DefaultComboBoxModel) SerializationUtils.clone(port1Model);
        cbxPort1.setModel(port1Model);
        cbxPort2.setModel(port2Model);

        if (config != null) {
            objBinding();
        }

        validateFormDB();
        validateForm();

        iconLoading.setVisible(false);
        syncIconLoading.setVisible(false);
        lblSyncData.setVisible(false);
    }

    private DefaultComboBoxModel getPortModel() {
        DefaultComboBoxModel result = new DefaultComboBoxModel();
        HashSet<SerialPort> ports = SerialHelper.getAvailableSerialPorts();
        for (SerialPort port : ports) {
            result.addElement(port.getSystemPortName());
        }
        return result;
    }

    private DefaultComboBoxModel getSpeedModel() {
        return new DefaultComboBoxModel(new Integer[]{110, 300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200});
    }

    private DefaultComboBoxModel getDBitsModel() {
        return new DefaultComboBoxModel(new Short[]{5, 6, 7, 8});
    }

    private DefaultComboBoxModel getSBitsModel() {
        return new DefaultComboBoxModel(new Float[]{1f, 1.5f, 2f});
    }

    private EnumComboBoxModel getParityModel() {
        return new EnumComboBoxModel<>(ParityEnum.class);
    }

    private void validateFormDB() {
        boolean bDBHost, bDBName, bDBUsr, bDBPwd;

        bDBHost = !txtDBHost.getText().trim().isEmpty();
        lblDBHost.setForeground(bDBHost ? Color.black : Color.red);

        bDBName = !txtDBName.getText().trim().isEmpty();
        lblDBName.setForeground(bDBName ? Color.black : Color.red);

        bDBUsr = !txtDBUsr.getText().trim().isEmpty();
        lblDBUsr.setForeground(bDBUsr ? Color.black : Color.red);

        bDBPwd = !(new String(txtDBPwd.getPassword())).trim().isEmpty();
        lblDBPwd.setForeground(bDBPwd ? Color.black : Color.red);

        validFormDB = bDBHost && bDBName && bDBUsr && bDBPwd;
        btnCheckDbConnection.setEnabled(validFormDB);
    }

    private void validateForm() {
        boolean bSHost, bSNo, bSClient, bSUser, bSPass,
                bCOM1, bSpeed1, bCOM2, bSpeed2, bWPlant;

        bSHost = !txtHost.getText().trim().isEmpty();
        lblHost.setForeground(bSHost ? Color.black : Color.red);

        bSNo = !txtSNo.getText().trim().isEmpty();
        lblSId.setForeground(bSNo ? Color.black : Color.red);

        bSClient = !txtDClient.getText().trim().isEmpty();
        lblDClient.setForeground(bSClient ? Color.black : Color.red);

        bSPass = !(new String(txtSapPassword.getPassword())).trim().isEmpty();
        lblSapPassword.setForeground(bSPass ? Color.black : Color.red);

        bSUser = !txtSapUpsername.getText().trim().isEmpty();
        lblSapUsername.setForeground(bSUser ? Color.black : Color.red);

        bCOM1 = !(cbxPort1.getSelectedItem() == null || ((String) cbxPort1.getSelectedItem()).isEmpty());
        lblPort1.setForeground(bCOM1 ? Color.black : Color.red);

        bCOM2 = !(cbxPort2.getSelectedItem() == null || ((String) cbxPort2.getSelectedItem()).isEmpty());
        lblPort2.setForeground(bCOM2 ? Color.black : Color.red);

        bSpeed1 = cbxSpeed1.getSelectedItem() != null;
        lblSpeed1.setForeground(bSpeed1 ? Color.black : Color.red);

        bSpeed2 = cbxSpeed2.getSelectedItem() != null;
        lblSpeed2.setForeground(bSpeed2 ? Color.black : Color.red);

        bWPlant = !txtPlant.getText().trim().isEmpty();
        lblPlant.setForeground(bWPlant ? Color.black : Color.red);

        boolean bB1 = bCOM1 && bSpeed1, bB2 = bCOM2 && bSpeed2;

        validForm = (bSHost && bSNo && bSClient
                && (bB1 || bB2) && bSUser && bSPass
                && bWPlant);
        btnSave.setEnabled(validForm);
    }

    private AppConfig objMapping() {
        if (config == null) {
            config = new AppConfig();
        }

        config.setDbHost(txtDBHost.getText().trim());
        config.setDbName(txtDBName.getText().trim());
        config.setDbUsername(txtDBUsr.getText().trim());
        config.setDbPassword(new String(txtDBPwd.getPassword()).trim());
        String wbId = txtWBID.getText().trim();
        config.setWbId(wbId);

        Configuration configuration = config.getConfiguration();
        if (configuration != null && !wbId.equalsIgnoreCase(configuration.getWbId())) {
            configuration = configController.getConfiguration(wbId);
        }

        configuration = configuration != null ? configuration : new Configuration();
        if (configuration.getId() > 0) {
            configuration.setUpdatedDate(new Date());
        }

        configuration.setSapHost(txtHost.getText().trim());
        configuration.setSapGwHost(txtHost.getText().trim());
        configuration.setSapRouteString(txtRString.getText().trim());
        configuration.setSapSystemNumber(txtSNo.getText().trim());
        configuration.setSapClient(txtDClient.getText().trim());
        configuration.setSapUser(txtSapUpsername.getText().trim());
        configuration.setSapPass(new String(txtSapPassword.getPassword()).trim());

        configuration.setWkPlant(txtPlant.getText().trim());
        configuration.setWbId(wbId);

        configuration.setWb1Port(cbxPort1.getSelectedItem().toString().trim());
        configuration.setWb1BaudRate((Integer) cbxSpeed1.getSelectedItem());
        configuration.setWb1DataBit((Short) cbxDataBits1.getSelectedItem());
        Float sbit1 = (Float) cbxStopBits1.getSelectedItem();
        configuration.setWb1StopBit(new BigDecimal(sbit1 == 1.5f ? sbit1 * 2f : sbit1));
        configuration.setWb1ParityControl(((ParityEnum) cbxPControl1.getSelectedItem()).ordinal());
        configuration.setWb1Mettler(chbMettler1.isSelected());
        configuration.setWb1AutoSignal(chbAutoSignal1.isSelected());

        configuration.setWb2Port(cbxPort2.getSelectedItem().toString().trim());
        configuration.setWb2BaudRate((Integer) cbxSpeed2.getSelectedItem());
        configuration.setWb2DataBit((Short) cbxDataBits2.getSelectedItem());
        Float sbit2 = (Float) cbxStopBits2.getSelectedItem();
        configuration.setWb2StopBit(new BigDecimal(sbit2 == 1.5f ? sbit2 * 2f : sbit2));
        configuration.setWb2ParityControl(((ParityEnum) cbxPControl2.getSelectedItem()).ordinal());
        configuration.setWb2Mettler(chbMettler2.isSelected());
        configuration.setWb2AutoSignal(chbAutoSignal2.isSelected());

        config.setConfiguration(configuration);

        return config;
    }

    private void objBinding() {
        setFormEditable(JPAConnector.isOpen());

        txtDBHost.setText(config.getDbHost());
        txtDBName.setText(config.getDbName());
        txtDBUsr.setText(config.getDbUsername());
        txtDBPwd.setText(config.getDbPassword());

        Configuration configuration = config.getConfiguration();
        if (configuration != null) {
            txtHost.setText(configuration.getSapHost());
            txtSNo.setValue(configuration.getSapSystemNumber());
            txtRString.setText(configuration.getSapRouteString());
            txtDClient.setValue(configuration.getSapClient());
            txtSapUpsername.setText(configuration.getSapUser());
            txtSapPassword.setText(configuration.getSapPass());

            txtPlant.setText(configuration.getWkPlant());
            txtWBID.setText(configuration.getWbId());

            String port1 = configuration.getWb1Port();
            if (port1Model.getIndexOf(port1) < 0) {
                port1Model.addElement(port1);
            }
            cbxPort1.setModel(port1Model);
            cbxPort1.setSelectedItem(port1);

            DefaultComboBoxModel speed1Model = getSpeedModel();
            Integer speed1 = configuration.getWb1BaudRate();
            if (speed1Model.getIndexOf(speed1) < 0) {
                speed1Model.addElement(speed1);
                cbxSpeed1.setModel(speed1Model);
            }
            cbxSpeed1.setSelectedItem(speed1);

            Short dbit1 = configuration.getWb1DataBit().shortValue();
            cbxDataBits1.setSelectedItem(dbit1);

            Float sbit1 = configuration.getWb1StopBit().floatValue();
            if (sbit1 == 3f) {
                sbit1 = sbit1 / 2f;
            }
            cbxStopBits1.setSelectedItem(sbit1);

            ParityEnum p1Control = configController.getPlControl(config, configuration.getWb1ParityControl());

            cbxPControl1.setSelectedItem(p1Control);
            chbMettler1.setSelected(configuration.getWb1Mettler());
            chbAutoSignal1.setSelected(configuration.getWb1AutoSignal());

            String port2 = configuration.getWb2Port();
            if (port2Model.getIndexOf(port2) < 0) {
                port2Model.addElement(port2);
            }
            cbxPort2.setModel(port2Model);
            cbxPort2.setSelectedItem(port2);

            DefaultComboBoxModel speed2Model = getSpeedModel();
            Integer speed2 = configuration.getWb2BaudRate();
            if (speed2Model.getIndexOf(speed2) < 0) {
                speed2Model.addElement(speed2);
                cbxSpeed2.setModel(speed2Model);
            }
            cbxSpeed2.setSelectedItem(speed2);

            Short dbit2 = configuration.getWb2DataBit().shortValue();
            cbxDataBits2.setSelectedItem(dbit2);

            Float sbit2 = configuration.getWb2StopBit().floatValue();
            if (sbit2 == 3f) {
                sbit2 = sbit2 / 2f;
            }
            cbxStopBits2.setSelectedItem(sbit2);

            ParityEnum p2Control = configController.getPlControl(config, configuration.getWb2ParityControl());

            cbxPControl2.setSelectedItem(p2Control);
            chbMettler2.setSelected(configuration.getWb2Mettler());
            chbAutoSignal2.setSelected(configuration.getWb2AutoSignal());
        } else {
            txtWBID.setText(config.getWbId());
        }
    }

    @Action
    public Task saveConfig() {
        return new SaveConfigTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class SaveConfigTask extends Task<Object, Void> {

        SaveConfigTask(Application app) {
            super(app);
            syncIconLoading.setVisible(true);
            lblSyncData.setVisible(true);
            btnSave.setEnabled(false);
        }

        @Override
        protected Object doInBackground() {
            boolean error = false;
            StringBuilder msg = new StringBuilder();
            if (!validForm) {
                return null;
            }
            objMapping();
            try {
                config.save();
            } catch (ConfigurationException ex) {
                Logger.getLogger(this.getClass()).error(null, ex);
                error = true;
                for (String string : ex.getMessages()) {
                    msg.append(string).append(". \n");
                }
            }

            if (!error) {
                if (!WeighBridgeApp.getApplication().isOfflineMode()) {
                    try {
                        SyncMasterDataService syncMasterDataService = new SyncMasterDataService();
                        syncMasterDataService.syncMasterDataWhenLogin();
                    } catch (Exception ex) {
                        logger.error(ex);
                    }
                }

                dispose();
                WeighBridgeApp app = new WeighBridgeApp();
                app.restartApplication();
            } else {
                JOptionPane.showMessageDialog(rootPane, msg.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                syncIconLoading.setVisible(false);
                lblSyncData.setVisible(false);
                btnSave.setEnabled(true);
            }

            return null;  // return your result
        }
    }

    @Action
    public Task checkDbConnection() {
        return new CheckDbConnectionTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class CheckDbConnectionTask extends Task<Object, Void> {

        CheckDbConnectionTask(Application app) {
            super(app);
            iconLoading.setVisible(true);
            btnCheckDbConnection.setEnabled(false);

            config.setDbHost(txtDBHost.getText().trim());
            config.setDbName(txtDBName.getText().trim());
            config.setDbUsername(txtDBUsr.getText().trim());
            config.setDbPassword(new String(txtDBPwd.getPassword()).trim());
        }

        @Override
        protected Object doInBackground() {
            try {
                JPAConnector.close();
                JPAConnector.getInstance();

                // get config in database
                configController = new ConfigController();
                config.setConfiguration(configController.getConfiguration());

                objBinding();
            } catch (Exception ex) {
                setFormEditable(false);
                JOptionPane.showMessageDialog(ConfigView.this, resourceMap.getString("msg.errorDbConnectionFail"), "Error", JOptionPane.ERROR_MESSAGE);
            }

            return null;
        }

        @Override
        protected void succeeded(Object result) {
            iconLoading.setVisible(false);
            btnCheckDbConnection.setEnabled(true);
        }
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckDbConnection;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbxDataBits1;
    private javax.swing.JComboBox cbxDataBits2;
    private javax.swing.JComboBox cbxPControl1;
    private javax.swing.JComboBox cbxPControl2;
    private javax.swing.JComboBox cbxPort1;
    private javax.swing.JComboBox cbxPort2;
    private javax.swing.JComboBox cbxSpeed1;
    private javax.swing.JComboBox cbxSpeed2;
    private javax.swing.JComboBox cbxStopBits1;
    private javax.swing.JComboBox cbxStopBits2;
    private javax.swing.JCheckBox chbAutoSignal1;
    private javax.swing.JCheckBox chbAutoSignal2;
    private javax.swing.JCheckBox chbMettler1;
    private javax.swing.JCheckBox chbMettler2;
    private org.jdesktop.swingx.JXBusyLabel iconLoading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDBHost;
    private javax.swing.JLabel lblDBName;
    private javax.swing.JLabel lblDBPwd;
    private javax.swing.JLabel lblDBUsr;
    private javax.swing.JLabel lblDClient;
    private javax.swing.JLabel lblDataBits1;
    private javax.swing.JLabel lblDataBits2;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPControl1;
    private javax.swing.JLabel lblPControl2;
    private javax.swing.JLabel lblPlant;
    private javax.swing.JLabel lblPort1;
    private javax.swing.JLabel lblPort2;
    private javax.swing.JLabel lblRString;
    private javax.swing.JLabel lblSId;
    private javax.swing.JLabel lblSapPassword;
    private javax.swing.JLabel lblSapUsername;
    private javax.swing.JLabel lblSpeed1;
    private javax.swing.JLabel lblSpeed2;
    private javax.swing.JLabel lblStopBits1;
    private javax.swing.JLabel lblStopBits2;
    private javax.swing.JLabel lblSyncData;
    private javax.swing.JPanel pnMySQLCon;
    private javax.swing.JPanel pnSAPConfig;
    private javax.swing.JPanel pnWB1Config;
    private javax.swing.JPanel pnWB2Config;
    private javax.swing.JPanel pnWorkingPlant;
    private org.jdesktop.swingx.JXBusyLabel syncIconLoading;
    private javax.swing.JTextField txtDBHost;
    private javax.swing.JTextField txtDBName;
    private javax.swing.JPasswordField txtDBPwd;
    private javax.swing.JTextField txtDBUsr;
    private javax.swing.JFormattedTextField txtDClient;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtPlant;
    private javax.swing.JTextField txtRString;
    private javax.swing.JFormattedTextField txtSNo;
    private javax.swing.JPasswordField txtSapPassword;
    private javax.swing.JTextField txtSapUpsername;
    private javax.swing.JTextField txtWBID;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
