/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfigView.java
 *
 * Created on 29-11-2009, 14:32:15
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.model.AppConfig;
import com.gcs.wb.rs232.enums.ParityEnum;
import com.gcs.wb.rs232.SerialHelper;
import com.gcs.wb.utils.Base64_Utils;
import gnu.io.CommPortIdentifier;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.codec.binary.Base64;
import org.apache.commons.configuration.ConfigurationException;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.swingx.combobox.EnumComboBoxModel;

/**
 *
 * @author Tran-Vu
 */
public class ConfigView extends javax.swing.JDialog {

    // <editor-fold defaultstate="collapsed" desc="Class Constructors">
    /** Creates new form ConfigView */
    public ConfigView(java.awt.Frame parent) {
        super(parent);
        initComponents();
        initController();
        standAlone = false;
    }

    private ConfigView(java.awt.Frame parent, boolean b) {
        super(parent, b);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ConfigView.class.getName()).log(Level.FATAL, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ConfigView.class.getName()).log(Level.FATAL, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ConfigView.class.getName()).log(Level.FATAL, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ConfigView.class.getName()).log(Level.FATAL, null, ex);
        }
        initComponents();
        initController();
        standAlone = true;
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMySQLCon = new javax.swing.JPanel();
        lblDBHost = new javax.swing.JLabel();
        txtDBHost = new javax.swing.JTextField();
        lblDBName = new javax.swing.JLabel();
        txtDBName = new javax.swing.JTextField();
        lblDBUsr = new javax.swing.JLabel();
        txtDBUsr = new javax.swing.JTextField();
        lblDBPwd = new javax.swing.JLabel();
        txtDBPwd = new javax.swing.JPasswordField();
        pnSAPConfig = new javax.swing.JPanel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblSId = new javax.swing.JLabel();
        txfSNo = new javax.swing.JFormattedTextField();
        lblRString = new javax.swing.JLabel();
        txtRString = new javax.swing.JTextField();
        lblDClient = new javax.swing.JLabel();
        txfDClient = new javax.swing.JFormattedTextField();
        pnWB1Config = new javax.swing.JPanel();
        lblPort1 = new javax.swing.JLabel();
        cbxPort1 = new javax.swing.JComboBox();
        lblSpeed1 = new javax.swing.JLabel();
        cbxSpeed1 = new javax.swing.JComboBox();
        lblDataBits1 = new javax.swing.JLabel();
        cbxDataBits1 = new javax.swing.JComboBox();
        lblStopBits1 = new javax.swing.JLabel();
        cbxStopBits1 = new javax.swing.JComboBox();
        lblPControl1 = new javax.swing.JLabel();
        cbxPControl1 = new javax.swing.JComboBox();
        chbMettler1 = new javax.swing.JCheckBox();
        pnWB2Config = new javax.swing.JPanel();
        lblPort2 = new javax.swing.JLabel();
        cbxPort2 = new javax.swing.JComboBox();
        lblSpeed2 = new javax.swing.JLabel();
        cbxSpeed2 = new javax.swing.JComboBox();
        lblDataBits2 = new javax.swing.JLabel();
        cbxDataBits2 = new javax.swing.JComboBox();
        lblStopBits2 = new javax.swing.JLabel();
        cbxStopBits2 = new javax.swing.JComboBox();
        lblPControl2 = new javax.swing.JLabel();
        cbxPControl2 = new javax.swing.JComboBox();
        chbMettler2 = new javax.swing.JCheckBox();
        pnWorkingPlant = new javax.swing.JPanel();
        lblPlant = new javax.swing.JLabel();
        txtPlant = new javax.swing.JTextField();
        txtWBID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(ConfigView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnMySQLCon.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnMySQLCon.border.title"))); // NOI18N
        pnMySQLCon.setName("pnMySQLCon"); // NOI18N

        lblDBHost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDBHost.setText(resourceMap.getString("lblDBHost.text")); // NOI18N
        lblDBHost.setName("lblDBHost"); // NOI18N
        lblDBHost.setPreferredSize(new java.awt.Dimension(60, 14));

        txtDBHost.setText(resourceMap.getString("txtDBHost.text")); // NOI18N
        txtDBHost.setName("txtDBHost"); // NOI18N
        txtDBHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBHostKeyReleased(evt);
            }
        });

        lblDBName.setText(resourceMap.getString("lblDBName.text")); // NOI18N
        lblDBName.setName("lblDBName"); // NOI18N

        txtDBName.setText(resourceMap.getString("txtDBName.text")); // NOI18N
        txtDBName.setName("txtDBName"); // NOI18N
        txtDBName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBNameKeyReleased(evt);
            }
        });

        lblDBUsr.setText(resourceMap.getString("lblDBUsr.text")); // NOI18N
        lblDBUsr.setName("lblDBUsr"); // NOI18N

        txtDBUsr.setText(resourceMap.getString("txtDBUsr.text")); // NOI18N
        txtDBUsr.setName("txtDBUsr"); // NOI18N
        txtDBUsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBUsrKeyReleased(evt);
            }
        });

        lblDBPwd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDBPwd.setText(resourceMap.getString("lblDBPwd.text")); // NOI18N
        lblDBPwd.setName("lblDBPwd"); // NOI18N

        txtDBPwd.setText(resourceMap.getString("txtDBPwd.text")); // NOI18N
        txtDBPwd.setName("txtDBPwd"); // NOI18N
        txtDBPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDBPwdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnMySQLConLayout = new javax.swing.GroupLayout(pnMySQLCon);
        pnMySQLCon.setLayout(pnMySQLConLayout);
        pnMySQLConLayout.setHorizontalGroup(
            pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMySQLConLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDBUsr)
                    .addComponent(lblDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDBUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(txtDBHost, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDBName)
                    .addComponent(lblDBPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDBPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(txtDBName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMySQLConLayout.setVerticalGroup(
            pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMySQLConLayout.createSequentialGroup()
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMySQLConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDBUsr)
                    .addComponent(txtDBUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDBPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDBPwd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnSAPConfig.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnSAPConfig.border.title"))); // NOI18N
        pnSAPConfig.setMinimumSize(new java.awt.Dimension(247, 84));
        pnSAPConfig.setName("pnSAPConfig"); // NOI18N

        lblHost.setText(resourceMap.getString("lblHost.text")); // NOI18N
        lblHost.setName("lblHost"); // NOI18N

        txtHost.setText(resourceMap.getString("txtHost.text")); // NOI18N
        txtHost.setName("txtHost"); // NOI18N
        txtHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHostKeyReleased(evt);
            }
        });

        lblSId.setText(resourceMap.getString("lblSId.text")); // NOI18N
        lblSId.setName("lblSId"); // NOI18N

        txfSNo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfSNo.setName("txfSNo"); // NOI18N
        txfSNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfSNoKeyReleased(evt);
            }
        });

        lblRString.setText(resourceMap.getString("lblRString.text")); // NOI18N
        lblRString.setName("lblRString"); // NOI18N

        txtRString.setText(resourceMap.getString("txtRString.text")); // NOI18N
        txtRString.setName("txtRString"); // NOI18N
        txtRString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRStringKeyReleased(evt);
            }
        });

        lblDClient.setText(resourceMap.getString("lblDClient.text")); // NOI18N
        lblDClient.setName("lblDClient"); // NOI18N

        txfDClient.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfDClient.setName("txfDClient"); // NOI18N
        txfDClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfDClientKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnSAPConfigLayout = new javax.swing.GroupLayout(pnSAPConfig);
        pnSAPConfig.setLayout(pnSAPConfigLayout);
        pnSAPConfigLayout.setHorizontalGroup(
            pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSAPConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRString, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHost, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRString, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtHost, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDClient)
                    .addComponent(lblSId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfDClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnSAPConfigLayout.setVerticalGroup(
            pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSAPConfigLayout.createSequentialGroup()
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHost)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSAPConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRString)
                    .addComponent(txtRString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDClient))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnWB1Config.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWB1Config.border.title"))); // NOI18N
        pnWB1Config.setMinimumSize(new java.awt.Dimension(230, 170));
        pnWB1Config.setName("pnWB1Config"); // NOI18N

        lblPort1.setText(resourceMap.getString("lblPort1.text")); // NOI18N
        lblPort1.setName("lblPort1"); // NOI18N

        cbxPort1.setEditable(true);
        cbxPort1.setModel(getPortModel());
        cbxPort1.setName("cbxPort1"); // NOI18N
        cbxPort1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPort1ItemStateChanged(evt);
            }
        });

        lblSpeed1.setText(resourceMap.getString("lblSpeed1.text")); // NOI18N
        lblSpeed1.setName("lblSpeed1"); // NOI18N

        cbxSpeed1.setEditable(true);
        cbxSpeed1.setModel(getSpeedModel());
        cbxSpeed1.setName("cbxSpeed1"); // NOI18N
        cbxSpeed1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSpeed1ItemStateChanged(evt);
            }
        });

        lblDataBits1.setText(resourceMap.getString("lblDataBits1.text")); // NOI18N
        lblDataBits1.setName("lblDataBits1"); // NOI18N

        cbxDataBits1.setModel(getDBitsModel());
        cbxDataBits1.setName("cbxDataBits1"); // NOI18N
        cbxDataBits1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDataBits1ItemStateChanged(evt);
            }
        });

        lblStopBits1.setText(resourceMap.getString("lblStopBits1.text")); // NOI18N
        lblStopBits1.setName("lblStopBits1"); // NOI18N

        cbxStopBits1.setModel(getSBitsModel());
        cbxStopBits1.setName("cbxStopBits1"); // NOI18N
        cbxStopBits1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxStopBits1ItemStateChanged(evt);
            }
        });

        lblPControl1.setText(resourceMap.getString("lblPControl1.text")); // NOI18N
        lblPControl1.setName("lblPControl1"); // NOI18N

        cbxPControl1.setModel(getParityModel());
        cbxPControl1.setName("cbxPControl1"); // NOI18N
        cbxPControl1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPControl1ItemStateChanged(evt);
            }
        });

        chbMettler1.setText(resourceMap.getString("chbMettler1.text")); // NOI18N
        chbMettler1.setName("chbMettler1"); // NOI18N

        javax.swing.GroupLayout pnWB1ConfigLayout = new javax.swing.GroupLayout(pnWB1Config);
        pnWB1Config.setLayout(pnWB1ConfigLayout);
        pnWB1ConfigLayout.setHorizontalGroup(
            pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB1ConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPort1)
                    .addComponent(lblSpeed1)
                    .addComponent(lblDataBits1)
                    .addComponent(lblStopBits1)
                    .addComponent(lblPControl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbMettler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSpeed1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPort1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxDataBits1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxStopBits1, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPControl1, 0, 165, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWB1ConfigLayout.setVerticalGroup(
            pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB1ConfigLayout.createSequentialGroup()
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort1)
                    .addComponent(cbxPort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeed1)
                    .addComponent(cbxSpeed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataBits1)
                    .addComponent(cbxDataBits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopBits1)
                    .addComponent(cbxStopBits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB1ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPControl1)
                    .addComponent(cbxPControl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbMettler1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnWB2Config.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWB2Config.border.title"))); // NOI18N
        pnWB2Config.setMinimumSize(new java.awt.Dimension(230, 170));
        pnWB2Config.setName("pnWB2Config"); // NOI18N

        lblPort2.setText(resourceMap.getString("lblPort2.text")); // NOI18N
        lblPort2.setName("lblPort2"); // NOI18N

        cbxPort2.setEditable(true);
        cbxPort2.setModel(getPortModel());
        cbxPort2.setName("cbxPort2"); // NOI18N
        cbxPort2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPort2ItemStateChanged(evt);
            }
        });

        lblSpeed2.setText(resourceMap.getString("lblSpeed2.text")); // NOI18N
        lblSpeed2.setName("lblSpeed2"); // NOI18N

        cbxSpeed2.setEditable(true);
        cbxSpeed2.setModel(getSpeedModel());
        cbxSpeed2.setName("cbxSpeed2"); // NOI18N
        cbxSpeed2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSpeed2ItemStateChanged(evt);
            }
        });

        lblDataBits2.setText(resourceMap.getString("lblDataBits2.text")); // NOI18N
        lblDataBits2.setName("lblDataBits2"); // NOI18N

        cbxDataBits2.setModel(getDBitsModel());
        cbxDataBits2.setName("cbxDataBits2"); // NOI18N
        cbxDataBits2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDataBits2ItemStateChanged(evt);
            }
        });

        lblStopBits2.setText(resourceMap.getString("lblStopBits2.text")); // NOI18N
        lblStopBits2.setName("lblStopBits2"); // NOI18N

        cbxStopBits2.setModel(getSBitsModel());
        cbxStopBits2.setName("cbxStopBits2"); // NOI18N
        cbxStopBits2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxStopBits2ItemStateChanged(evt);
            }
        });

        lblPControl2.setText(resourceMap.getString("lblPControl2.text")); // NOI18N
        lblPControl2.setName("lblPControl2"); // NOI18N

        cbxPControl2.setModel(getParityModel());
        cbxPControl2.setName("cbxPControl2"); // NOI18N
        cbxPControl2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPControl2ItemStateChanged(evt);
            }
        });

        chbMettler2.setText(resourceMap.getString("chbMettler2.text")); // NOI18N
        chbMettler2.setName("chbMettler2"); // NOI18N

        javax.swing.GroupLayout pnWB2ConfigLayout = new javax.swing.GroupLayout(pnWB2Config);
        pnWB2Config.setLayout(pnWB2ConfigLayout);
        pnWB2ConfigLayout.setHorizontalGroup(
            pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB2ConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPort2)
                    .addComponent(lblSpeed2)
                    .addComponent(lblDataBits2)
                    .addComponent(lblStopBits2)
                    .addComponent(lblPControl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbMettler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSpeed2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPort2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxDataBits2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxStopBits2, 0, 165, Short.MAX_VALUE)
                    .addComponent(cbxPControl2, 0, 165, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWB2ConfigLayout.setVerticalGroup(
            pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWB2ConfigLayout.createSequentialGroup()
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort2)
                    .addComponent(cbxPort2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeed2)
                    .addComponent(cbxSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataBits2)
                    .addComponent(cbxDataBits2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopBits2)
                    .addComponent(cbxStopBits2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWB2ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPControl2)
                    .addComponent(cbxPControl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbMettler2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnWorkingPlant.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWorkingPlant.border.title"))); // NOI18N
        pnWorkingPlant.setName("pnWorkingPlant"); // NOI18N
        pnWorkingPlant.setPreferredSize(new java.awt.Dimension(640, 69));

        lblPlant.setText(resourceMap.getString("lblPlant.text")); // NOI18N
        lblPlant.setName("lblPlant"); // NOI18N

        txtPlant.setText(resourceMap.getString("txtPlant.text")); // NOI18N
        txtPlant.setName("txtPlant"); // NOI18N
        txtPlant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlantKeyReleased(evt);
            }
        });

        txtWBID.setText(resourceMap.getString("txtWBID.text")); // NOI18N
        txtWBID.setName("txtWBID"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout pnWorkingPlantLayout = new javax.swing.GroupLayout(pnWorkingPlant);
        pnWorkingPlant.setLayout(pnWorkingPlantLayout);
        pnWorkingPlantLayout.setHorizontalGroup(
            pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWorkingPlantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPlant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWBID)
                    .addComponent(txtPlant, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWorkingPlantLayout.setVerticalGroup(
            pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWorkingPlantLayout.createSequentialGroup()
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlant)
                    .addComponent(txtPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWorkingPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(ConfigView.class, this);
        btnSave.setAction(actionMap.get("saveConfig")); // NOI18N
        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setMaximumSize(new java.awt.Dimension(85, 23));
        btnSave.setMinimumSize(new java.awt.Dimension(85, 23));
        btnSave.setName("btnSave"); // NOI18N
        btnSave.setPreferredSize(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMySQLCon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnWB1Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnWB2Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnSAPConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnWorkingPlant, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMySQLCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnWorkingPlant, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(pnSAPConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnWB1Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnWB2Config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // </editor-fold>
    // <editor-fold defaultstate="expaned" desc="Event Handlers">

    /**
     * @return the standAlone
     */
    public boolean isStandAlone() {
        return standAlone;
    }

    private void txtRStringKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRStringKeyReleased
        validateForm();
    }//GEN-LAST:event_txtRStringKeyReleased

    private void cbxPort1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPort1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPort1ItemStateChanged

    private void cbxPort2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPort2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPort2ItemStateChanged

    private void cbxSpeed1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSpeed1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxSpeed1ItemStateChanged

    private void cbxSpeed2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSpeed2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxSpeed2ItemStateChanged

    private void cbxDataBits1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDataBits1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxDataBits1ItemStateChanged

    private void cbxDataBits2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDataBits2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxDataBits2ItemStateChanged

    private void cbxStopBits1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxStopBits1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxStopBits1ItemStateChanged

    private void cbxStopBits2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxStopBits2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxStopBits2ItemStateChanged

    private void cbxPControl1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPControl1ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPControl1ItemStateChanged

    private void cbxPControl2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPControl2ItemStateChanged
        validateForm();
    }//GEN-LAST:event_cbxPControl2ItemStateChanged

    private void txfSNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfSNoKeyReleased
        validateForm();
    }//GEN-LAST:event_txfSNoKeyReleased

    private void txfDClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfDClientKeyReleased
        validateForm();
    }//GEN-LAST:event_txfDClientKeyReleased

    private void txtDBHostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBHostKeyReleased
        validateForm();
    }//GEN-LAST:event_txtDBHostKeyReleased

    private void txtDBNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBNameKeyReleased
        validateForm();
    }//GEN-LAST:event_txtDBNameKeyReleased

    private void txtDBUsrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBUsrKeyReleased
        validateForm();
    }//GEN-LAST:event_txtDBUsrKeyReleased

    private void txtDBPwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDBPwdKeyReleased
        validateForm();
    }//GEN-LAST:event_txtDBPwdKeyReleased

    private void txtHostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostKeyReleased
        validateForm();
    }//GEN-LAST:event_txtHostKeyReleased

    private void txtPlantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlantKeyReleased
        validateForm();
    }//GEN-LAST:event_txtPlantKeyReleased

    /**
     * This is used for stand-alone execution
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ConfigView dialog = new ConfigView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

//    private static boolean checkString(String s) {
//        Matcher m = pat.matcher(s);
//        return m.matches();
//    }
    private void initController() {
        editable = btnSave.isEnabled();
        config = new AppConfig();
        if (config != null) {
            objBinding();
            validateForm();
        }
    }

    private DefaultComboBoxModel getPortModel() {
        DefaultComboBoxModel result = new DefaultComboBoxModel();
        HashSet<CommPortIdentifier> ports = SerialHelper.getAvailableSerialPorts();
        for (CommPortIdentifier port : ports) {
            result.addElement(port.getName());
        }
        return result;
    }

    private DefaultComboBoxModel getSpeedModel() {
        return new DefaultComboBoxModel(new Integer[]{110, 300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200});
    }

    private DefaultComboBoxModel getDBitsModel() {
        return new DefaultComboBoxModel(new Short[]{5, 6, 7, 8});
    }

    private DefaultComboBoxModel getSBitsModel() {
        return new DefaultComboBoxModel(new Float[]{1f, 1.5f, 2f});
    }

    private EnumComboBoxModel getParityModel() {
        return new EnumComboBoxModel<ParityEnum>(ParityEnum.class);
    }

    private boolean validateForm() {
        boolean //DB Checks
                bDBHost = false, bDBName = false, bDBUsr = false, bDBPwd = false,
                //SAP Checks
                bSHost = false, bSNo = false, bSClient = false,
                //Bridge 1 Checks,
                bCOM1 = false, bSpeed1 = false,
                //Bridge 1 Checks,
                bCOM2 = false, bSpeed2 = false,
                bWPlant = false;

        bDBHost = !(txtDBHost.getText().trim().length() == 0);
        if (bDBHost) {
            lblDBHost.setForeground(Color.BLACK);
        } else {
            lblDBHost.setForeground(Color.RED);
        }

        bDBName = !(txtDBName.getText().trim().length() == 0);
        if (bDBName) {
            lblDBName.setForeground(Color.BLACK);
        } else {
            lblDBName.setForeground(Color.RED);
        }

        bDBUsr = !(txtDBUsr.getText().trim().length() == 0);
        if (bDBUsr) {
            lblDBUsr.setForeground(Color.BLACK);
        } else {
            lblDBUsr.setForeground(Color.RED);
        }

        bDBPwd = !((new String(txtDBPwd.getPassword())).trim().length() == 0);
        if (bDBPwd) {
            lblDBPwd.setForeground(Color.BLACK);
        } else {
            lblDBPwd.setForeground(Color.RED);
        }

        bSHost = !(txtHost.getText().trim().length() == 0);
        if (bSHost) {// && checkString(txtHost.getText().trim())) {
            lblHost.setForeground(Color.black);
        } else {
            lblHost.setForeground(Color.red);
        }

        bSNo = !(txfSNo.getText().trim().length() == 0);
        if (bSNo) {
            lblSId.setForeground(Color.black);
        } else {
            lblSId.setForeground(Color.red);
        }

        bSClient = !(txfDClient.getText().trim().length() == 0);
        if (bSClient) {
            lblDClient.setForeground(Color.black);
        } else {
            lblDClient.setForeground(Color.red);
        }

        bCOM1 = !(cbxPort1.getSelectedItem() instanceof String && (cbxPort1.getSelectedItem() == null || ((String) cbxPort1.getSelectedItem()).isEmpty()));
        if (bCOM1) {
            lblPort1.setForeground(Color.black);
        } else {
            lblPort1.setForeground(Color.red);
        }

        bCOM2 = !(cbxPort2.getSelectedItem() instanceof String && (cbxPort2.getSelectedItem() == null || ((String) cbxPort2.getSelectedItem()).isEmpty()));
        if (bCOM2) {
            lblPort2.setForeground(Color.black);
        } else {
            lblPort2.setForeground(Color.red);
        }

        bSpeed1 = !(cbxSpeed1.getSelectedItem() == null);
        if (bSpeed1) {
            lblSpeed1.setForeground(Color.black);
        } else {
            lblSpeed1.setForeground(Color.red);
        }

        bSpeed2 = !(cbxSpeed2.getSelectedItem() == null);
        if (bSpeed2) {
            lblSpeed2.setForeground(Color.black);
        } else {
            lblSpeed2.setForeground(Color.red);
        }

        bWPlant = !(txtPlant.getText().trim().length() == 0);
        if (bWPlant) {
            lblPlant.setForeground(Color.black);
        } else {
            lblPlant.setForeground(Color.red);
        }

        boolean bB1 = bCOM1 && bSpeed1, bB2 = bCOM2 && bSpeed2;

        return (bDBHost && bDBName && bDBUsr && bDBPwd
                && bSHost && bSNo && bSClient
                && (bB1 || bB2)
                && bWPlant);
    }

    private AppConfig objMapping() {
        if (config == null) {
            config = new AppConfig();
        }
        String wbId = txtWBID.getText();
        wbId = wbId == null || wbId.trim().length() == 0 ? "" : wbId.trim();
        String dbHost = txtDBHost.getText();
        dbHost = dbHost == null || dbHost.trim().length() == 0 ? "" : dbHost.trim();
        String dbName = txtDBName.getText();
        dbName = dbName == null || dbName.trim().length() == 0 ? "" : dbName.trim();
        String dbUsr = txtDBUsr.getText();
        dbUsr = dbUsr == null || dbUsr.trim().length() == 0 ? "" : dbUsr.trim();
        String dbPwd = new String(txtDBPwd.getPassword());
        dbPwd = dbPwd == null || dbPwd.trim().length() == 0 ? "" : dbPwd.trim();
        config.setWbId(Base64_Utils.decodeNTimes(wbId));
        config.setDbHost(Base64_Utils.decodeNTimes(dbHost));
        config.setDbName(Base64_Utils.decodeNTimes(dbName));
        config.setDbUsr(Base64_Utils.decodeNTimes(dbUsr));
        config.setDbPwd(Base64_Utils.decodeNTimes(dbPwd));

        String sHost = txtHost.getText();
        sHost = sHost == null || sHost.trim().length() == 0 ? "" : sHost;
        String sRoute = txtRString.getText();
        sRoute = sRoute == null || sRoute.trim().length() == 0 ? "" : sRoute;
        String sNo = txfSNo.getValue() == null || txfSNo.getValue().toString() == null
                || txfSNo.getValue().toString().trim().length() == 0 ? "" : txfSNo.getValue().toString().trim();
        String sDClient = txfDClient.getValue() == null || txfDClient.getValue().toString() == null
                || txfDClient.getValue().toString().trim().length() == 0 ? "" : txfDClient.getValue().toString().trim();
        config.setsHost(Base64_Utils.decodeNTimes(sHost));
        config.setsRoute(Base64_Utils.decodeNTimes(sRoute));
        config.setsNumber(Base64_Utils.decodeNTimes(sNo));
        config.setsClient(Base64_Utils.decodeNTimes(sDClient));

        Object port1 = cbxPort1.getSelectedItem();
        port1 = port1 == null || port1.toString().trim().length() == 0 ? null : port1.toString().trim();
        Integer speed1 = 0;
        if (port1 == null) {
            speed1 = null;
        } else if (cbxSpeed1.getSelectedItem() instanceof Short) {
            speed1 = ((Short) cbxSpeed1.getSelectedItem()).intValue();
        } else if (cbxSpeed1.getSelectedItem() instanceof Integer) {
            speed1 = (Integer) cbxSpeed1.getSelectedItem();
        } else if (cbxSpeed1.getSelectedItem() instanceof String) {
            try {
                speed1 = Integer.valueOf(String.valueOf(cbxSpeed1.getSelectedItem()));
            } catch (NumberFormatException ex) {
                speed1 = null;
            }
        } else if (cbxSpeed1.getSelectedItem() == null) {
            speed1 = Integer.valueOf(String.valueOf(cbxSpeed1.getEditor().getItem()));
        }
        config.setB1Port((String) port1);
        config.setB1Speed(speed1);
        config.setB1DBits(port1 == null ? null : (Short) cbxDataBits1.getSelectedItem());
        Float sbit1 = 0f;
        sbit1 = (Float) cbxStopBits1.getSelectedItem();
        sbit1 = (sbit1 == 1.5f ? sbit1 * 2f : sbit1);
        config.setB1SBits(port1 == null ? null : sbit1);
        config.setB1PC(port1 == null ? null : (new Integer(((ParityEnum) cbxPControl1.getSelectedItem()).ordinal())).shortValue());
        config.setB1Mettler(port1 == null ? null : chbMettler1.isSelected());

        Object port2 = cbxPort2.getSelectedItem();
        port2 = port2 == null || port2.toString().trim().length() == 0 ? null : port2.toString().trim();
        Integer speed2 = 0;
        if (port2 == null) {
            speed2 = null;
        } else if (cbxSpeed2.getSelectedItem() instanceof Short) {
            speed2 = ((Short) cbxSpeed2.getSelectedItem()).intValue();
        } else if (cbxSpeed2.getSelectedItem() instanceof Integer) {
            speed2 = (Integer) cbxSpeed2.getSelectedItem();
        } else if (cbxSpeed2.getSelectedItem() instanceof String) {
            try {
                speed2 = Integer.valueOf(String.valueOf(cbxSpeed2.getSelectedItem()));
            } catch (NumberFormatException ex) {
                speed2 = null;
            }
        } else if (cbxSpeed2.getSelectedItem() == null) {
            speed2 = Integer.valueOf(String.valueOf(cbxSpeed2.getEditor().getItem()));
        }
        config.setB2Port((String) port2);
        config.setB2Speed(speed2);
        config.setB2DBits(port2 == null ? null : (Short) cbxDataBits2.getSelectedItem());
        Float sbit2 = 0f;
        sbit2 = (Float) cbxStopBits2.getSelectedItem();
        sbit2 = (sbit2 == 1.5f ? sbit2 * 2f : sbit2);
        config.setB2SBits(port2 == null ? null : sbit2);
        config.setB2PC(port2 == null ? null : (new Integer(((ParityEnum) cbxPControl2.getSelectedItem()).ordinal())).shortValue());
        config.setB2Mettler(port2 == null ? null : chbMettler2.isSelected());

        String wPlant = txtPlant.getText();
        wPlant = wPlant == null || wPlant.trim().isEmpty() ? "" : wPlant;
        config.setwPlant(Base64_Utils.decodeNTimes(wPlant));

        return config;
    }

    private void objBinding() {
        txtWBID.setText(Base64_Utils.encodeNTimes(config.getWbId()));
        txtDBHost.setText(Base64_Utils.encodeNTimes(config.getDbHost()));
        txtDBName.setText(Base64_Utils.encodeNTimes(config.getDbName()));
        txtDBUsr.setText(Base64_Utils.encodeNTimes(config.getDbUsr()));
        txtDBPwd.setText(Base64_Utils.encodeNTimes(config.getDbPwd()));

        txtHost.setText(Base64_Utils.encodeNTimes(config.getsHost()));
        txfSNo.setValue(Base64_Utils.encodeNTimes(config.getsNumber()));
        txtRString.setText(Base64_Utils.encodeNTimes(config.getsRoute()));
        txfDClient.setValue(Base64_Utils.encodeNTimes(config.getsClient()));      
        txtPlant.setText(Base64_Utils.encodeNTimes(config.getwPlant()));
        
        DefaultComboBoxModel port1Model = getPortModel();
        String port1 = config.getB1Port();
        if (port1Model.getIndexOf(port1) < 0) {
            port1Model.addElement(port1);
            cbxPort1.setModel(port1Model);
        }
        cbxPort1.setSelectedItem(port1);

        DefaultComboBoxModel speed1Model = getSpeedModel();
        Integer speed1 = config.getB1Speed();
        if (speed1Model.getIndexOf(speed1) < 0) {
            speed1Model.addElement(speed1);
            cbxSpeed1.setModel(speed1Model);
        }
        cbxSpeed1.setSelectedItem(speed1);

        Short dbit1 = config.getB1DBits();
        cbxDataBits1.setSelectedItem(dbit1);

        Float sbit1 = config.getB1SBits();
        if (sbit1 != null && sbit1 == 3f) {
            sbit1 = sbit1 / 2f;
        }
        cbxStopBits1.setSelectedItem(sbit1);

        ParityEnum p1Control = null;

        switch (config.getB1PC()) {
            case 0:
                p1Control = ParityEnum.NONE;
                break;
            case 1:
                p1Control = ParityEnum.ODD;
                break;
            case 2:
                p1Control = ParityEnum.EVEN;
                break;
            case 3:
                p1Control = ParityEnum.MARK;
                break;
            case 4:
                p1Control = ParityEnum.SPACE;
                break;
        }
        cbxPControl1.setSelectedItem(p1Control);
        chbMettler1.setSelected(config.getB1Mettler() == null ? false : config.getB1Mettler());

        DefaultComboBoxModel port2Model = getPortModel();
        String port2 = config.getB2Port();
        if (port2Model.getIndexOf(port2) < 0) {
            port2Model.addElement(port2);
            cbxPort2.setModel(port2Model);
        }
        cbxPort2.setSelectedItem(port2);

        DefaultComboBoxModel speed2Model = getSpeedModel();
        Integer speed2 = config.getB2Speed();
        if (speed2Model.getIndexOf(speed2) < 0) {
            speed2Model.addElement(speed2);
            cbxSpeed2.setModel(speed2Model);
        }
        cbxSpeed2.setSelectedItem(speed2);

        Short dbit2 = new Short(config.getB2DBits().shortValue());
        cbxDataBits2.setSelectedItem(dbit2);

        Float sbit2 = new Float(config.getB2SBits().shortValue());
        if (sbit2 != null && sbit2 == 3f) {
            sbit2 = sbit2 / 2f;
        }
        cbxStopBits2.setSelectedItem(sbit2);

        ParityEnum p2Control = null;
        switch (config.getB2PC()) {
            case 0:
                p2Control = ParityEnum.NONE;
                break;
            case 1:
                p2Control = ParityEnum.ODD;
                break;
            case 2:
                p2Control = ParityEnum.EVEN;
                break;
            case 3:
                p2Control = ParityEnum.MARK;
                break;
            case 4:
                p2Control = ParityEnum.SPACE;
                break;
        }
        cbxPControl2.setSelectedItem(p2Control);
        chbMettler2.setSelected(config.getB2Mettler() == null ? false : config.getB2Mettler());
    }

    @Action
    public void saveConfig() {
        boolean error = false;
        StringBuilder msg = new StringBuilder();
        if (!validateForm()) {
            return;
        }
        objMapping();
        try {
            config.save();
        } catch (ConfigurationException ex) {
            Logger.getLogger(this.getClass()).error(null, ex);
            error = true;
            for (String string : ex.getMessages()) {
                msg.append(string).append(". \n");
            }
        }
        if (!error) {
            if (standAlone) {
                System.exit(0);
            } else {
                WeighBridgeApp.getApplication().setConfig(new AppConfig());
                dispose();
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, msg.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Action
    public void clearForm() {
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbxDataBits1;
    private javax.swing.JComboBox cbxDataBits2;
    private javax.swing.JComboBox cbxPControl1;
    private javax.swing.JComboBox cbxPControl2;
    private javax.swing.JComboBox cbxPort1;
    private javax.swing.JComboBox cbxPort2;
    private javax.swing.JComboBox cbxSpeed1;
    private javax.swing.JComboBox cbxSpeed2;
    private javax.swing.JComboBox cbxStopBits1;
    private javax.swing.JComboBox cbxStopBits2;
    private javax.swing.JCheckBox chbMettler1;
    private javax.swing.JCheckBox chbMettler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDBHost;
    private javax.swing.JLabel lblDBName;
    private javax.swing.JLabel lblDBPwd;
    private javax.swing.JLabel lblDBUsr;
    private javax.swing.JLabel lblDClient;
    private javax.swing.JLabel lblDataBits1;
    private javax.swing.JLabel lblDataBits2;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPControl1;
    private javax.swing.JLabel lblPControl2;
    private javax.swing.JLabel lblPlant;
    private javax.swing.JLabel lblPort1;
    private javax.swing.JLabel lblPort2;
    private javax.swing.JLabel lblRString;
    private javax.swing.JLabel lblSId;
    private javax.swing.JLabel lblSpeed1;
    private javax.swing.JLabel lblSpeed2;
    private javax.swing.JLabel lblStopBits1;
    private javax.swing.JLabel lblStopBits2;
    private javax.swing.JPanel pnMySQLCon;
    private javax.swing.JPanel pnSAPConfig;
    private javax.swing.JPanel pnWB1Config;
    private javax.swing.JPanel pnWB2Config;
    private javax.swing.JPanel pnWorkingPlant;
    private javax.swing.JFormattedTextField txfDClient;
    private javax.swing.JFormattedTextField txfSNo;
    private javax.swing.JTextField txtDBHost;
    private javax.swing.JTextField txtDBName;
    private javax.swing.JPasswordField txtDBPwd;
    private javax.swing.JTextField txtDBUsr;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtPlant;
    private javax.swing.JTextField txtRString;
    private javax.swing.JTextField txtWBID;
    // End of variables declaration//GEN-END:variables
    private AppConfig config = null;
    private boolean standAlone;
    private boolean editable = false;
//    private static final Pattern pat = Pattern.compile("\\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\."
//            + "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\."
//            + "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\."
//            + "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b");
    // </editor-fold>
}
