/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DailyReportView.java
 *
 * Created on Jan 2, 2020
 */
package com.gcs.wb.views;

import java.util.Calendar;
import java.util.List;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.controller.DailyReportController;
import com.gcs.wb.jpa.entity.WeightTicket;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.application.Application;

/**
 *
 * @author thanghl
 */
public class DailyReportView extends javax.swing.JInternalFrame {

    /** Creates new form DailyReportView */
    public DailyReportView() {
        initComponents();
        weightTicketList = new ArrayList<WeightTicket>();
        FilterActionTask filterActionTask = new FilterActionTask(WeighBridgeApp.getApplication());
        filterActionTask.execute();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = WeighBridgeApp.getApplication().getEm();
        pnFilter = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        dpDateFrom = new org.jdesktop.swingx.JXDatePicker();
        lblTo = new javax.swing.JLabel();
        dpDateTo = new org.jdesktop.swingx.JXDatePicker();
        btnFilter = new javax.swing.JButton();
        btnPrintReport = new javax.swing.JButton();
        spnResult = new javax.swing.JScrollPane();
        tabResults = new org.jdesktop.swingx.JXTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(DailyReportView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnFilter.border.title"))); // NOI18N
        pnFilter.setName("pnFilter"); // NOI18N

        lblFrom.setText(resourceMap.getString("lblFrom.text")); // NOI18N
        lblFrom.setName("lblFrom"); // NOI18N

        dpDateFrom.setDate(Calendar.getInstance().getTime());
        dpDateFrom.setName("dpDateFrom"); // NOI18N

        lblTo.setText(resourceMap.getString("lblTo.text")); // NOI18N
        lblTo.setName("lblTo"); // NOI18N

        dpDateTo.setDate(Calendar.getInstance().getTime());
        dpDateTo.setName("dpDateTo"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(DailyReportView.class, this);
        btnFilter.setAction(actionMap.get("filterAction")); // NOI18N
        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N

        javax.swing.GroupLayout pnFilterLayout = new javax.swing.GroupLayout(pnFilter);
        pnFilter.setLayout(pnFilterLayout);
        pnFilterLayout.setHorizontalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFilter)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        pnFilterLayout.setVerticalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(dpDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(dpDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPrintReport.setAction(actionMap.get("printReport")); // NOI18N
        btnPrintReport.setText(resourceMap.getString("btnPrintReport.text")); // NOI18N
        btnPrintReport.setName("btnPrintReport"); // NOI18N

        spnResult.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("spnResult.border.title"))); // NOI18N
        spnResult.setName("spnResult"); // NOI18N

        tabResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabResults.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabResults.setEditable(false);
        tabResults.setName("tabResults"); // NOI18N
        tabResults.setShowGrid(true);
        spnResult.setViewportView(tabResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(btnPrintReport, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(spnResult, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintReport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action(block = Task.BlockingScope.ACTION)
    public Task filterAction() {
        return new FilterActionTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class FilterActionTask extends Task<Object, Void> {

        FilterActionTask(Application app) {
            super(app);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected Object doInBackground() {
            try {
                setProgress(0, 0, 4);
                weightTicketList.clear();

                setProgress(1, 0, 4);
                setMessage(resourceMapMsg.getString("msg.getData"));
                //AppConfig appConfig = WeighBridgeApp.getApplication().getConfig();
                //WeightTicketJpaController weightTicketJpaController = new WeightTicketJpaController();
                // = weightTicketJpaController.findByCreateDateRange(dpDateFrom.getDate(), dpDateTo.getDate());
                List<WeightTicket> weightTickets = dailyReportController.findByCreateDateRange(dpDateFrom, dpDateTo);

                setProgress(2, 0, 4);
                setMessage(resourceMapMsg.getString("msg.handleData"));
                weightTicketList.addAll(weightTickets);
                wtDatas = dailyReportController.handleWtDatas(wtDatas, weightTicketList, wtColNames);
//                wtDatas = new Object[weightTicketList.size()][wtColNames.length];
//
//                for (int i = 0; i < weightTicketList.size(); i++) {
//                    WeightTicket weightTicket = weightTicketList.get(i);
//                    WeightTicketPK weightTicketPK = weightTicket.getWeightTicketPK();
//                    if (!weightTicketPK.getMandt().equalsIgnoreCase(appConfig.getsClient()) && !weightTicketPK.getWPlant().equalsIgnoreCase(appConfig.getwPlant().toString())) {
//                        continue;
//                    }
//                    String hh = weightTicket.getCreateTime().substring(0, 2);
//                    String mm = weightTicket.getCreateTime().substring(2, 4);
//                    String ss = weightTicket.getCreateTime().substring(4);
//                    Calendar create_date = Calendar.getInstance();
//                    create_date.setTime(weightTicket.getCreateDate());
//                    create_date.set(Calendar.HOUR_OF_DAY, Integer.valueOf(hh));
//                    create_date.set(Calendar.MINUTE, Integer.valueOf(mm));
//                    create_date.set(Calendar.SECOND, Integer.valueOf(ss));
//                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
//                    String createdDateTime = dateFormat.format(create_date.getTime());
//                    wtDatas[i][0] = i + 1;
//                    wtDatas[i][1] = weightTicket.getWeightTicketPK().getSeqByDay();
//                    wtDatas[i][2] = weightTicket.getTenTaiXe();
//                    wtDatas[i][3] = weightTicket.getCmndBl();
//                    wtDatas[i][4] = weightTicket.getSoXe();
//                    wtDatas[i][5] = weightTicket.getSoRomooc();
//                    wtDatas[i][6] = weightTicket.getCreator();
//                    wtDatas[i][7] = createdDateTime;
//                    wtDatas[i][8] = weightTicket.getRegCategory();
//                    wtDatas[i][9] = weightTicket.getRegItemText();
//                    if (weightTicket.getFTime() != null) {
//                        Calendar calendar = Calendar.getInstance();
//                        calendar.setTime(weightTicket.getFTime());
//                        String inDateTime = dateFormat.format(calendar.getTime());
//                        wtDatas[i][10] = inDateTime;//item.getFTime();
//                    } else {
//                        wtDatas[i][10] = weightTicket.getFTime();
//                    }
//                    wtDatas[i][11] = weightTicket.getFScale() == null ? weightTicket.getFScale() : weightTicket.getFScale().doubleValue() / 1000d;
//                    if (weightTicket.getSTime() != null) {
//                        Calendar calendar = Calendar.getInstance();
//                        calendar.setTime(weightTicket.getSTime());
//                        String outDateTime = dateFormat.format(calendar.getTime());
//                        wtDatas[i][12] = outDateTime;//item.getSTime();
//                    } else {
//                        wtDatas[i][12] = weightTicket.getSTime();
//                    }
//                    wtDatas[i][13] = weightTicket.getSScale() == null ? weightTicket.getSScale() : weightTicket.getSScale().doubleValue() / 1000d;
//                    wtDatas[i][14] = weightTicket.getGQty();
//                    wtDatas[i][15] = weightTicket.getDelivNumb();
//                    wtDatas[i][16] = weightTicket.getMatDoc();
//                    wtDatas[i][17] = weightTicket.getDissolved();
//                    if (weightTicket.getPosted() == 1) {
//                        wtDatas[i][18] = true;
//                    } else {
//                        wtDatas[i][18] = false;
//                    }
//                    wtDatas[i][19] = weightTicket.getEbeln();
//                    wtDatas[i][20] = "";
//                }
                setProgress(3, 0, 4);
                editable = new boolean[wtColNames.length];
                for (int i = 0; i < editable.length; i++) {
                    editable[i] = false;
                }
                setProgress(4, 0, 4);
            } catch (Exception ex) {
                failed(ex);
            }
            return null; // return your result
        }

        @Override
        protected void finished() {
            setMessage(resourceMapMsg.getString("msg.finished"));
            WeighBridgeApp.getApplication().bindJTableModel(tabResults, wtDatas, wtColNames, wtColTypes, editable);
        }

        @Override
        protected void failed(Throwable cause) {
            logger.error(null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
        }
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task printReport() {
        if (tabResults.getModel().getRowCount() == 0) {
            return null;
        } else {
            return new PrintReportTask(Application.getInstance(WeighBridgeApp.class));
        }
    }

    private class PrintReportTask extends Task<Object, Void> {

        PrintReportTask(Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            try {
                Map<String, Object> params = new HashMap<String, Object>();
//                params.put("P_PNAME_RPT", WeighBridgeApp.getApplication().getSapSetting().getNameRpt());
//                params.put("P_PADDRESS", WeighBridgeApp.getApplication().getSapSetting().getAddress());
//                params.put("P_PPHONE", WeighBridgeApp.getApplication().getSapSetting().getPhone());
//                params.put("P_PFAX", WeighBridgeApp.getApplication().getSapSetting().getFax());
//                params.put("P_FROM", dpDateFrom.getDate());
//                params.put("P_TO", dpDateTo.getDate());
                String reportName = null;
//                if (WeighBridgeApp.getApplication().getConfig().getModeNormal()) {
//                    reportName = "./rpt/rptBT/WTList.jasper";
//                } else {
//                    reportName = "./rpt/rptPQ/WTList.jasper";
//                }
                params = dailyReportController.getParamsReport(dpDateFrom, dpDateTo);
                reportName = dailyReportController.getReportName();
                JasperPrint jasperPrint = JasperFillManager.fillReport(reportName, params, new JRTableModelDataSource(tabResults.getModel()));
                JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                jasperViewer.setVisible(true);
            } catch (Exception ex) {
                failed(ex);
            }
            return null;  // return your result
        }

        @Override
        protected void failed(Throwable cause) {
            logger.error(null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnPrintReport;
    private org.jdesktop.swingx.JXDatePicker dpDateFrom;
    private org.jdesktop.swingx.JXDatePicker dpDateTo;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnFilter;
    private javax.swing.JScrollPane spnResult;
    private org.jdesktop.swingx.JXTable tabResults;
    // End of variables declaration//GEN-END:variables
    private static Logger logger = Logger.getLogger(DailyReportView.class);
    private java.util.List<WeightTicket> weightTicketList;
    private boolean[] editable = null;
    Object[][] wtDatas = null;
    Object[] wtColNames = new String[]{
        "STT",
        "Số đăng tài",
        "Tên tài xế",
        "CMND/Bằng lái",
        "Số Xe",
        "Số Rơmoóc",
        "Người tạo",
        "Ngày giờ tạo",
        "Nhập/Xuất(I/O)",
        "Loại hàng",
        "Ngày giờ vào",
        "T.L vào",
        "Ngày giờ ra",
        "T.L ra",
        "T.L Hàng",
        "Số DO",
        "Số chứng từ SAP",
        "Hủy",
        "SAP Posted",
        "DVVC",
        "Số P.O"};
    Class[] wtColTypes = new Class[]{
        Integer.class,
        Integer.class,
        String.class,
        String.class,
        String.class,
        String.class,
        String.class,
        Date.class,
        Character.class,
        String.class,
        Date.class,
        BigDecimal.class,
        Date.class,
        BigDecimal.class,
        BigDecimal.class,
        String.class,
        String.class,
        Boolean.class,
        Boolean.class,
        String.class,
        String.class};
    org.jdesktop.application.ResourceMap resourceMapMsg = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(DailyReportView.class);
    DailyReportController dailyReportController = new DailyReportController();
}
