/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DailyReportView.java
 *
 * Created on Jan 2, 2020
 */
package com.gcs.wb.views;

import java.util.Calendar;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.base.constant.Constants;
import com.gcs.wb.base.util.ExceptionUtil;
import com.gcs.wb.base.validator.DateFromToValidator;
import com.gcs.wb.controller.DailyReportController;
import com.gcs.wb.jpa.entity.WeightTicket;
import java.awt.Color;
import java.util.Map;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author thanghl
 */
public class DailyReportView extends javax.swing.JInternalFrame {

    private static Logger logger = Logger.getLogger(DailyReportView.class);
    private final DateFromToValidator dateFromToValidator = new DateFromToValidator();
    private List<WeightTicket> weightTicketList = null;
    private boolean[] editable = null;
    public static final String SDATE = "date";
    Object[][] wtDatas = null;
    Object[] wtColNames = Constants.DailyReport.WT_COL_NAMES;
    Class[] wtColTypes = Constants.DailyReport.WT_COL_TYPES;
    ResourceMap resourceMapMsg = Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(DailyReportView.class);
    DailyReportController dailyReportController = new DailyReportController();

    /**
     * Creates new form DailyReportView
     */
    public DailyReportView() {
        initComponents();
        dpDateFrom.setFormats(Constants.Date.FORMAT);
        dpDateTo.setFormats(Constants.Date.FORMAT);
        weightTicketList = new ArrayList();

        btnFilter.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFilter = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        dpDateFrom = new org.jdesktop.swingx.JXDatePicker();
        lblTo = new javax.swing.JLabel();
        dpDateTo = new org.jdesktop.swingx.JXDatePicker();
        btnFilter = new javax.swing.JButton();
        btnPrintReport = new javax.swing.JButton();
        spnResult = new javax.swing.JScrollPane();
        tabResults = new org.jdesktop.swingx.JXTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(DailyReportView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnFilter.border.title"))); // NOI18N
        pnFilter.setName("pnFilter"); // NOI18N

        lblFrom.setText(resourceMap.getString("lblFrom.text")); // NOI18N
        lblFrom.setName("lblFrom"); // NOI18N

        dpDateFrom.setDate(Calendar.getInstance().getTime());
        dpDateFrom.setName("dpDateFrom"); // NOI18N
        dpDateFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpDateFromPropertyChange(evt);
            }
        });

        lblTo.setText(resourceMap.getString("lblTo.text")); // NOI18N
        lblTo.setName("lblTo"); // NOI18N

        dpDateTo.setDate(Calendar.getInstance().getTime());
        dpDateTo.setName("dpDateTo"); // NOI18N
        dpDateTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpDateToPropertyChange(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(DailyReportView.class, this);
        btnFilter.setAction(actionMap.get("filterAction")); // NOI18N
        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N

        javax.swing.GroupLayout pnFilterLayout = new javax.swing.GroupLayout(pnFilter);
        pnFilter.setLayout(pnFilterLayout);
        pnFilterLayout.setHorizontalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFilter)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnFilterLayout.setVerticalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(dpDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(dpDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPrintReport.setAction(actionMap.get("printReport")); // NOI18N
        btnPrintReport.setText(resourceMap.getString("btnPrintReport.text")); // NOI18N
        btnPrintReport.setName("btnPrintReport"); // NOI18N

        spnResult.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("spnResult.border.title"))); // NOI18N
        spnResult.setName("spnResult"); // NOI18N

        tabResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabResults.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabResults.setEditable(false);
        tabResults.setName("tabResults"); // NOI18N
        tabResults.setShowGrid(true);
        spnResult.setViewportView(tabResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addComponent(btnPrintReport, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(spnResult, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintReport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void dpDateToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpDateToPropertyChange
    if (SDATE.equals(evt.getPropertyName())) {
        validateFilterForm();
    }
}//GEN-LAST:event_dpDateToPropertyChange

private void dpDateFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpDateFromPropertyChange
    if (SDATE.equals(evt.getPropertyName())) {
        validateFilterForm();
    }
}//GEN-LAST:event_dpDateFromPropertyChange

    private void validateFilterForm() {
        try {
            dateFromToValidator.validate(dpDateFrom.getDate(), dpDateTo.getDate());

            lblFrom.setForeground(Color.black);
            lblTo.setForeground(Color.black);
            btnFilter.setEnabled(true);
            btnPrintReport.setEnabled(true);
        } catch (IllegalArgumentException ex) {
            lblFrom.setForeground(Color.red);
            lblTo.setForeground(Color.red);
            btnFilter.setEnabled(false);
            btnPrintReport.setEnabled(false);
        }
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task filterAction() {
        return new FilterActionTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class FilterActionTask extends Task<Object, Void> {

        FilterActionTask(Application app) {
            super(app);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected Object doInBackground() {
            try {
                setProgress(0, 0, 4);
                weightTicketList.clear();

                setProgress(1, 0, 4);
                setMessage(resourceMapMsg.getString("msg.getData"));
                List<WeightTicket> weightTickets = dailyReportController.findByCreateDateRange(dpDateFrom, dpDateTo);

                setProgress(2, 0, 4);
                setMessage(resourceMapMsg.getString("msg.handleData"));
                weightTicketList.addAll(weightTickets);
                wtDatas = dailyReportController.handleWtDatas(wtDatas, weightTicketList);

                setProgress(3, 0, 4);
                editable = new boolean[wtColNames.length];
                for (int i = 0; i < editable.length; i++) {
                    editable[i] = false;
                }
                setProgress(4, 0, 4);
            } catch (Exception ex) {
                failed(ex);
            }
            return null; // return your result
        }

        @Override
        protected void finished() {
            setMessage(resourceMapMsg.getString("msg.finished"));
            WeighBridgeApp.getApplication().bindJTableModel(tabResults, wtDatas, wtColNames, wtColTypes, editable);
        }

        @Override
        protected void failed(Throwable cause) {
            logger.error(null, cause);
            if (!ExceptionUtil.isDatabaseDisconnectedException(cause)) {
                JOptionPane.showMessageDialog(rootPane, cause.getMessage());
            }
        }
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task printReport() {
        return new PrintReportTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class PrintReportTask extends Task<Object, Void> {

        PrintReportTask(Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            try {
                setProgress(0, 0, 4);
                weightTicketList.clear();

                setProgress(1, 0, 4);
                setMessage(resourceMapMsg.getString("msg.getData"));
                List<WeightTicket> weightTickets = dailyReportController.findByCreateDateRange(dpDateFrom, dpDateTo);

                setProgress(2, 0, 4);
                setMessage(resourceMapMsg.getString("msg.handleData"));
                weightTicketList.addAll(weightTickets);
                wtDatas = dailyReportController.handleWtDatas(wtDatas, weightTicketList);

                setProgress(3, 0, 4);
                editable = new boolean[wtColNames.length];
                for (int i = 0; i < editable.length; i++) {
                    editable[i] = false;
                }
                WeighBridgeApp.getApplication().bindJTableModel(tabResults, wtDatas, wtColNames, wtColTypes, editable);
                setProgress(4, 0, 4);

                Map<String, Object> params = dailyReportController.getParamsReport(dpDateFrom, dpDateTo);
                String reportName = dailyReportController.getReportName();
                dailyReportController.printReport(params, reportName, new JRTableModelDataSource(tabResults.getModel()));
            } catch (Exception ex) {
                failed(ex);
            }
            return null;  // return your result
        }

        @Override
        protected void failed(Throwable cause) {
            logger.error(null, cause);
            if (!ExceptionUtil.isDatabaseDisconnectedException(cause)) {
                JOptionPane.showMessageDialog(rootPane, cause.getMessage());
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnPrintReport;
    private org.jdesktop.swingx.JXDatePicker dpDateFrom;
    private org.jdesktop.swingx.JXDatePicker dpDateTo;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnFilter;
    private javax.swing.JScrollPane spnResult;
    private org.jdesktop.swingx.JXTable tabResults;
    // End of variables declaration//GEN-END:variables
}
