/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginView.java
 *
 * Created on 30-11-2009, 08:14:03
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.controller.LoginController;
import com.gcs.wb.jpa.JPAConnector;
import com.sap.conn.jco.JCoException;
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.hibersap.HibersapException;
import org.hibersap.session.Session;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.Task;

/**
 *
 * @author Tran-Vu
 */
public class LoginView extends javax.swing.JDialog {

    /** Creates new form LoginView */
    public LoginView(java.awt.Frame parent) {
        super(parent);
        initComponents();
        initForm();
        iconLoading.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnForm = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        iconLoading = new org.jdesktop.swingx.JXBusyLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(LoginView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFont(resourceMap.getFont("Form.font")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnForm.setName("pnForm"); // NOI18N
        pnForm.setPreferredSize(new java.awt.Dimension(332, 139));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(LoginView.class, this);
        btnLogin.setAction(actionMap.get("login")); // NOI18N
        btnLogin.setText(resourceMap.getString("btnLogin.text")); // NOI18N
        btnLogin.setName("btnLogin"); // NOI18N

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText(resourceMap.getString("lblUsername.text")); // NOI18N
        lblUsername.setName("lblUsername"); // NOI18N

        txtUsername.setForeground(resourceMap.getColor("txtUsername.foreground")); // NOI18N
        txtUsername.setName("txtUsername"); // NOI18N
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText(resourceMap.getString("lblPassword.text")); // NOI18N
        lblPassword.setName("lblPassword"); // NOI18N

        txtPassword.setAction(actionMap.get("login")); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtUsername, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), txtPassword, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });

        iconLoading.setBusy(true);
        iconLoading.setLabelFor(btnLogin);
        iconLoading.setDirection(org.jdesktop.swingx.JXBusyLabel.Direction.RIGHT);
        iconLoading.setName("iconLoading"); // NOI18N

        javax.swing.GroupLayout pnFormLayout = new javax.swing.GroupLayout(pnForm);
        pnForm.setLayout(pnFormLayout);
        pnFormLayout.setHorizontalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addGroup(pnFormLayout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(iconLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnFormLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnFormLayout.setVerticalGroup(
            pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLogin)
                    .addComponent(iconLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnForm, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnForm, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        txtUsername.selectAll();
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        txtPassword.selectAll();
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        txtUsername.setText(txtUsername.getText().toUpperCase());
    }//GEN-LAST:event_txtUsernameFocusLost
    // <editor-fold defaultstate="expanded" desc="Variables Getter/Setter">

    // </editor-fold>
    // <editor-fold defaultstate="expanded" desc="Event Handlers area">
    private void initForm() {
        txtUsername.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                validateUsername(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateUsername(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateUsername(e);
            }
        });

        txtPassword.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                validatePassword(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validatePassword(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validatePassword(e);
            }
        });

        validateForm();
    }

    private void validateUsername(DocumentEvent e) {
        try {
            String text = e.getDocument().getText(0, e.getDocument().getLength()).trim();
            validUsername = text.length() > 0 && text.length() <= 12;
            lblUsername.setForeground(validUsername ? Color.BLACK : Color.RED);
        } catch (BadLocationException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.ERROR, null, ex);
        } finally {
            validateForm();
        }
    }

    private void validatePassword(DocumentEvent e) {
        try {
            String text = e.getDocument().getText(0, e.getDocument().getLength()).trim();
            validPassword = text.length() > 0;
            lblPassword.setForeground(validPassword ? Color.BLACK : Color.RED);
        } catch (BadLocationException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.ERROR, null, ex);
        } finally {
            validateForm();
        }
    }

    public void validateForm() {
        btnLogin.setEnabled(validUsername && validPassword);
    }

    public boolean isAuthenticated() {
        return this.authenticated;
    }

    public void setAuthenticated(boolean authenticated) {
        this.authenticated = authenticated;
    }

    @Action()
    public Task login() {
        return new LoginTask(WeighBridgeApp.getApplication(), this);
    }

    private class LoginTask extends org.jdesktop.application.Task<Object, Void> {

        private LoginController loginController;

        LoginTask(Application app, JDialog view) {
            super(app);
            String username = txtUsername.getText().trim();
            String password = new String(txtPassword.getPassword()).trim();
            loginController = new LoginController(username, password);

            txtUsername.setEnabled(false);
            txtPassword.setEnabled(false);
            iconLoading.setVisible(true);
            btnLogin.setEnabled(false);
        }

        @Override
        protected Object doInBackground() throws Exception {
            try {
                return loginController.doLogin();
            } catch (Exception ex) {
                throw ex;
            }
        }

        @Override
        protected void succeeded(Object result) {
            setAuthenticated(true);
            WeighBridgeApp.getApplication().setCredentials(loginController.getCredentials());
            WeighBridgeApp.getApplication().setLogin(loginController.getUser());
            WeighBridgeApp.getApplication().setOfflineMode(loginController.isOfflineMode());
            WeighBridgeApp.getApplication().setSapSetting(loginController.getSapSetting());
            WeighBridgeApp.getApplication().getConfig().setModeNormal(loginController.isOfflineMode());
            setVisible(false);
        }

        @Override
        protected void failed(Throwable cause) {
            if (cause instanceof HibersapException && cause.getCause() instanceof JCoException) {
                cause = cause.getCause();
                Session session = WeighBridgeApp.getApplication().getSAPSession();
                if (session != null) {
                    session.close();
                    session = null;
                }
                WeighBridgeApp.getApplication().setSAPSession(session);
            }

            txtUsername.setEnabled(true);
            txtPassword.setEnabled(true);
            iconLoading.setVisible(false);
            btnLogin.setEnabled(true);

            Logger.getLogger(LoginView.class.getName()).log(Level.ERROR, null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
        }
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Variables declaration area">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private org.jdesktop.swingx.JXBusyLabel iconLoading;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnForm;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private EntityManager entityManager = JPAConnector.getInstance();
    private boolean authenticated = false;
    private boolean validUsername = false;
    private boolean validPassword = false;
    // </editor-fold >
}
