/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LookupMatView.java
 *
 * Created on 15-08-2010, 16:38:10
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.bapi.helper.SAP2Local;
import com.gcs.wb.jpa.entity.Material;
import java.util.ArrayList;
import org.hibersap.session.Session;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author vunguyent
 */
public class LookupMatView extends javax.swing.JDialog {

    /** Creates new form LookupMatView */
    public LookupMatView(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        config = WeighBridgeApp.getApplication().getConfig();
        pnContent = new javax.swing.JPanel();
        pnFilter = new javax.swing.JPanel();
        lblMatDesc = new javax.swing.JLabel();
        txtMatDesc = new javax.swing.JTextField();
        btnLookup = new javax.swing.JButton();
        pnResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabResult = new org.jdesktop.swingx.JXTable();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(LookupMatView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnContent.setName("pnContent"); // NOI18N

        pnFilter.setName("pnFilter"); // NOI18N

        lblMatDesc.setText(resourceMap.getString("lblMatDesc.text")); // NOI18N
        lblMatDesc.setName("lblMatDesc"); // NOI18N

        txtMatDesc.setText(resourceMap.getString("txtMatDesc.text")); // NOI18N
        txtMatDesc.setName("txtMatDesc"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(LookupMatView.class, this);
        btnLookup.setAction(actionMap.get("lookupMat")); // NOI18N
        btnLookup.setText(resourceMap.getString("btnLookup.text")); // NOI18N
        btnLookup.setName("btnLookup"); // NOI18N

        javax.swing.GroupLayout pnFilterLayout = new javax.swing.GroupLayout(pnFilter);
        pnFilter.setLayout(pnFilterLayout);
        pnFilterLayout.setHorizontalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addComponent(lblMatDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnFilterLayout.setVerticalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatDesc)
                    .addComponent(btnLookup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnResult.setName("pnResult"); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jScrollPane1.border.title"))); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabResult.setName("tabResult"); // NOI18N
        jScrollPane1.setViewportView(tabResult);

        btnSelect.setAction(actionMap.get("chooseMat")); // NOI18N
        btnSelect.setText(resourceMap.getString("btnSelect.text")); // NOI18N
        btnSelect.setName("btnSelect"); // NOI18N

        javax.swing.GroupLayout pnResultLayout = new javax.swing.GroupLayout(pnResult);
        pnResult.setLayout(pnResultLayout);
        pnResultLayout.setHorizontalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelect))
        );
        pnResultLayout.setVerticalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnResultLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelect)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void chooseMat() {
        if (tabResult.getSelectedRow() == -1) {
            return;
        }
        selectedRow = materials.get(tabResult.convertRowIndexToModel(tabResult.getSelectedRow()));
        if (selectedRow != null) {
            setfMaterial(selectedRow);
            dispose();
        }
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task lookupMat() {
        return new LookupMatTask(org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class));
    }

    private class LookupMatTask extends org.jdesktop.application.Task<Object, Void> {

        Session sapSession = null;

        LookupMatTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to LookupMatTask fields, here.
            super(app);
            sapSession = WeighBridgeApp.getApplication().getSAPSession();
            if (materials == null) {
                materials = new ArrayList<Material>();
            }
        }

        @Override
        protected Object doInBackground() {
            materials.clear();
            materials.addAll(SAP2Local.lookupMaterialsByDesc(txtMatDesc.getText().trim()));
            wtData = new Object[materials.size()][wtCols.length];
            for (int i = 0; i < materials.size(); i++) {
                Material mat = materials.get(i);
                wtData[i][0] = mat.getMaterialPK().getMatnr();
                wtData[i][1] = mat.getMaktx();
            }
            editable = new boolean[wtCols.length];
            for (int i = 0; i < editable.length; i++) {
                editable[i] = false;
            }
            return null;  // return your result
        }

        @Override
        protected void finished() {
            WeighBridgeApp.getApplication().bindJTableModel(tabResult, wtData, wtCols, wtTypes, editable);
        }

        @Override
        protected void succeeded(Object result) {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }

    /**
     * @return the fMaterial
     */
    public Material getfMaterial() {
        return fMaterial;
    }

    /**
     * @param fMaterial the fMaterial to set
     */
    public void setfMaterial(Material fMaterial) {
        this.fMaterial = fMaterial;
    }
    private Material fMaterial = null;
    private boolean[] editable = null;
    Object[][] wtData = null;
    Object[] wtCols = new String[]{
        "Mã vật tư",
        "Loại vật tư"};
    Class[] wtTypes = new Class[]{
        String.class,
        String.class};
    private java.util.List<Material> materials;
    private Material selectedRow;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLookup;
    private javax.swing.JButton btnSelect;
    private com.gcs.wb.model.AppConfig config;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMatDesc;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnFilter;
    private javax.swing.JPanel pnResult;
    private org.jdesktop.swingx.JXTable tabResult;
    private javax.swing.JTextField txtMatDesc;
    // End of variables declaration//GEN-END:variables
}
