/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProcOrdView.java
 *
 * Created on 27-07-2010, 21:46:44
 */
package com.gcs.wb.views;

import com.gcs.wb.base.util.RegexFormatter;
import org.jdesktop.application.Action;
import com.gcs.wb.jpa.entity.Variant;
import com.gcs.wb.jpa.entity.VariantPK;
import com.gcs.wb.model.AppConfig;
import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.base.constant.Constants;
import javax.persistence.EntityManager;

/**
 *
 * @author vunguyent
 */
public class ProcOrdView extends javax.swing.JDialog {

    /** Creates new form ProcOrdView */
    public ProcOrdView(java.awt.Frame parent, String _procOrd) {
        super(parent);
        initComponents();
        //Save production order
        if ((_procOrd == null) || (_procOrd == null ? "" == null : _procOrd.equals(""))) {
            Variant vari = new Variant();
            VariantPK variPK = new VariantPK();
            EntityManager entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
            AppConfig lconfig = WeighBridgeApp.getApplication().getConfig();
            variPK.setMandt(lconfig.getsClient().toString());
            variPK.setWPlant(lconfig.getwPlant().toString());
            variPK.setParam("PROCESS_ORDER");
            vari.setVariantPK(variPK);
            vari = entityManager.find(Variant.class, vari.getVariantPK());
            if (vari != null) {
                try {
                    _procOrd = vari.getValue().toString();
                } catch (Exception e) {
                }
            }
            entityManager.clear();
        }
        //
        setProcOrd(_procOrd);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcOrd = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        txtProcOrd = new javax.swing.JFormattedTextField(new RegexFormatter("\\d{7,12}"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(ProcOrdView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        lblProcOrd.setText(resourceMap.getString("lblProcOrd.text")); // NOI18N
        lblProcOrd.setName("lblProcOrd"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(ProcOrdView.class, this);
        btnSelect.setAction(actionMap.get("chooseVal")); // NOI18N
        btnSelect.setText(resourceMap.getString("btnSelect.text")); // NOI18N
        btnSelect.setName("btnSelect"); // NOI18N

        txtProcOrd.setText(resourceMap.getString("txtProcOrd.text")); // NOI18N
        txtProcOrd.setName("txtProcOrd"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProcOrd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcOrd, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                    .addComponent(btnSelect, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcOrd)
                    .addComponent(txtProcOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnSelect)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String procOrd = null;
    

    /**
     * Get the value of procOrd
     *
     * @return the value of procOrd
     */
    public String getProcOrd() {
        return procOrd;
    }

    /**
     * Set the value of procOrd
     *
     * @param procOrd new value of procOrd
     */
    private void setProcOrd(String procOrd) {
        String oldProcOrd = this.procOrd;
        this.procOrd = procOrd;
        firePropertyChange(Constants.ProcOrdView.PROP_PROCORD, oldProcOrd, procOrd);
        //Save production order
        Variant vari = new Variant();
        VariantPK variPK = new VariantPK();
        EntityManager entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        AppConfig lconfig = WeighBridgeApp.getApplication().getConfig();
        try {
            variPK.setMandt(lconfig.getsClient().toString());
            variPK.setWPlant(lconfig.getwPlant().toString());
            variPK.setParam("PROCESS_ORDER");
            vari.setVariantPK(variPK);
            vari.setValue(procOrd);

            txtProcOrd.setValue(procOrd);
            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
            entityManager.merge(vari);
            entityManager.getTransaction().commit();
            entityManager.clear();
        } catch (Exception e) {
        }

        //
    }

    @Action
    public void chooseVal() {
        if (txtProcOrd.getValue() == null || ((String) txtProcOrd.getValue()).trim().isEmpty()) {
            setProcOrd(null);
        } else {
            String val = (String) txtProcOrd.getValue();
            while (val.length() < 12) {
                val = "0" + val;
            }
            setProcOrd(val);
        }
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel lblProcOrd;
    private javax.swing.JFormattedTextField txtProcOrd;
    // End of variables declaration//GEN-END:variables
}
