/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecvSlocView.java
 *
 * Created on 01-07-2010, 14:35:16
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.bapi.helper.SAP2Local;
import com.gcs.wb.jpa.entity.SLoc;
import com.gcs.wb.jpa.repositorys.SLocRepository;
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import org.jdesktop.application.Action;

/**
 *
 * @author vunguyent
 */
public class RecvSlocView extends javax.swing.JDialog {
    SLocRepository sLocRepository = new SLocRepository();

    /** Creates new form RecvSlocView */
    public RecvSlocView(java.awt.Frame parent, String recv_lgort, String ref_po) {
        super(parent);
        initComponents();
        this.refPO = ref_po;
        txtPONumber.setText(this.refPO);
        if (recv_lgort != null) {
            SLoc recv_sloc = sLocRepository.findByLgort(recv_lgort);
            this.recSloc = recv_sloc;
        } else {
            this.recSloc = null;
        }
        if (this.recSloc == null) {
            cbxRecvSloc.setSelectedIndex(-1);
        } else {
            cbxRecvSloc.setSelectedItem(this.recSloc);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        config = WeighBridgeApp.getApplication().getConfig();
        entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        if(entityManager != null ) entityManager.clear();
        pnContent = new javax.swing.JPanel();
        lblRecvSloc = new javax.swing.JLabel();
        cbxRecvSloc = new javax.swing.JComboBox();
        lblPONumber = new javax.swing.JLabel();
        txtPONumber = new javax.swing.JTextField();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(RecvSlocView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnContent.setName("pnContent"); // NOI18N

        lblRecvSloc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecvSloc.setText(resourceMap.getString("lblRecvSloc.text")); // NOI18N
        lblRecvSloc.setName("lblRecvSloc"); // NOI18N

        cbxRecvSloc.setModel(SAP2Local.getSlocModel(config, entityManager));
        cbxRecvSloc.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof SLoc) {
                    SLoc sloc = (SLoc)value;
                    setText(sloc.getLgobe());
                }
                return this;
            }
        });
        cbxRecvSloc.setName("cbxRecvSloc"); // NOI18N

        lblPONumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPONumber.setText(resourceMap.getString("lblPONumber.text")); // NOI18N
        lblPONumber.setName("lblPONumber"); // NOI18N

        txtPONumber.setText(resourceMap.getString("txtPONumber.text")); // NOI18N
        txtPONumber.setName("txtPONumber"); // NOI18N
        txtPONumber.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                checkPONum(e);
            }

            public void removeUpdate(DocumentEvent e) {
                checkPONum(e);
            }

            public void changedUpdate(DocumentEvent e) {
                checkPONum(e);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(RecvSlocView.class, this);
        btnSelect.setAction(actionMap.get("chooseVal")); // NOI18N
        btnSelect.setText(resourceMap.getString("btnSelect.text")); // NOI18N
        btnSelect.setName("btnSelect"); // NOI18N

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRecvSloc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPONumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRecvSloc, 0, 179, Short.MAX_VALUE)
                            .addComponent(txtPONumber, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                    .addComponent(btnSelect, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecvSloc)
                    .addComponent(cbxRecvSloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPONumber)
                    .addComponent(txtPONumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Get the value of recSloc
     *
     * @return the value of recSloc
     */
    public SLoc getRecSloc() {
        return recSloc;
    }

    /**
     * Set the value of recSloc
     *
     * @param recSloc new value of recSloc
     */
    public void setRecSloc(SLoc recSloc) {
        this.recSloc = recSloc;
    }

    /**
     * Get the value of refPO
     *
     * @return the value of refPO
     */
    public String getRefPO() {
        return refPO;
    }

    /**
     * Set the value of refPO
     *
     * @param refPO new value of refPO
     */
    public void setRefPO(String refPO) {
        this.refPO = refPO;
    }

    /**
     * Get the value of validEnteredPO
     *
     * @return the value of validEnteredPO
     */
    public boolean isValidEnteredPO() {
        return validEnteredPO;
    }

    /**
     * Set the value of validEnteredPO
     *
     * @param validEnteredPO new value of validEnteredPO
     */
    public void setValidEnteredPO(boolean validEnteredPO) {
        this.validEnteredPO = validEnteredPO;
    }

    @Action
    public void chooseVal() {
        if (cbxRecvSloc.getSelectedIndex() > -1) {
            setRecSloc((SLoc) cbxRecvSloc.getSelectedItem());
        } else {
            setRecSloc(null);
        }
        if (isValidEnteredPO()) {
            setRefPO(txtPONumber.getText().trim());
        } else {
            setRefPO(null);
        }
        dispose();
    }

    private void checkPONum(DocumentEvent e) {
        try {
            String text = e.getDocument().getText(0, e.getDocument().getLength()).trim();
            boolean valid = text.matches("\\d{10}");
            if (valid || text.length() == 0) {
                valid = true;
                lblPONumber.setForeground(Color.BLACK);
            } else {
                lblPONumber.setForeground(Color.RED);
            }
            setValidEnteredPO(valid);
        } catch (BadLocationException ex) {
        } finally {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox cbxRecvSloc;
    private com.gcs.wb.model.AppConfig config;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblPONumber;
    private javax.swing.JLabel lblRecvSloc;
    private javax.swing.JPanel pnContent;
    private javax.swing.JTextField txtPONumber;
    // End of variables declaration//GEN-END:variables
    private SLoc recSloc = null;
    private String refPO = null;
    private boolean validEnteredPO = false;
}
