/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingView.java
 *
 * Created on 17-06-2010, 14:41:08
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.jpa.entity.SAPSetting;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import com.gcs.wb.jpa.entity.Variant;
import com.gcs.wb.jpa.entity.VariantPK;
import com.gcs.wb.model.AppConfig;

/**
 *
 * @author vunguyent
 */
public class SettingView extends javax.swing.JDialog {

    /** Creates new form SettingView */
    public SettingView(java.awt.Frame parent) {
        super(parent);
        initComponents();
        if (sapSetting.getCheckTalp() == null || sapSetting.getCheckTalp() == false) {
            chkTALP.setSelected(false);
        } else {
            chkTALP.setSelected(true);
        }

        //----------------------------------
        //+20110119#01
        Variant vari = new Variant();
        VariantPK variPK = new VariantPK();
        AppConfig lconfig = WeighBridgeApp.getApplication().getConfig();
        variPK.setMandt(lconfig.getsClient().toString());
        variPK.setWPlant(lconfig.getwPlant().toString());
        variPK.setParam("PROCESS_ORDER_CF");
        vari.setVariantPK(variPK);
        vari = entityManager.find(Variant.class, vari.getVariantPK());
        String chkPROC = "";
        if (vari != null) {
            try {
                chkPROC = vari.getValue().toString();
            } catch (Exception e) {
            }
        }
        if (chkPROC.equals("X")) {
            chkPROC1.setSelected(true);
        }
        entityManager.clear();
        //+20110119#01
        //----------------------------------
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sapSetting = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getSapSetting();
        entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        pnWholeGroup = new javax.swing.JPanel();
        pnWPlant = new javax.swing.JPanel();
        lblWPlantRPT = new javax.swing.JLabel();
        txtWPlantRPT = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        pnMaterials = new javax.swing.JPanel();
        lblMatnrPCB40 = new javax.swing.JLabel();
        txtMatnrPCB40 = new javax.swing.JTextField();
        lblMatnrBulk = new javax.swing.JLabel();
        txtMatnrBulk = new javax.swing.JTextField();
        lblSubContractClinker = new javax.swing.JLabel();
        txtSubContractClinker = new javax.swing.JTextField();
        pnPPBaseVals = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfAct1Val = new javax.swing.JFormattedTextField();
        lblAct1Unit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfAct2Val = new javax.swing.JFormattedTextField();
        lblAct2Unit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfAct3Val = new javax.swing.JFormattedTextField();
        lblAct3Unit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfAct4Val = new javax.swing.JFormattedTextField();
        lblAct4Unit = new javax.swing.JLabel();
        pnWBTol = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txfWB1Tol = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txfWB2Tol = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        pnRolesMap = new javax.swing.JPanel();
        lblRWatchman = new javax.swing.JLabel();
        txtRWMan = new javax.swing.JTextField();
        lblRStationStaff = new javax.swing.JLabel();
        txtRSStaff = new javax.swing.JTextField();
        lblRAdministrator = new javax.swing.JLabel();
        txtRAdmin = new javax.swing.JTextField();
        chkTALP = new javax.swing.JCheckBox();
        chkPROC1 = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(SettingView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnWholeGroup.setName("pnWholeGroup"); // NOI18N

        pnWPlant.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWPlant.border.title"))); // NOI18N
        pnWPlant.setName("pnWPlant"); // NOI18N

        lblWPlantRPT.setText(resourceMap.getString("lblWPlantRPT.text")); // NOI18N
        lblWPlantRPT.setName("lblWPlantRPT"); // NOI18N

        txtWPlantRPT.setName("txtWPlantRPT"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${nameRpt}"), txtWPlantRPT, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblAddress.setText(resourceMap.getString("lblAddress.text")); // NOI18N
        lblAddress.setName("lblAddress"); // NOI18N

        txtAddress.setName("txtAddress"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${address}"), txtAddress, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblPhone.setText(resourceMap.getString("lblPhone.text")); // NOI18N
        lblPhone.setName("lblPhone"); // NOI18N

        txtPhone.setName("txtPhone"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${phone}"), txtPhone, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblFax.setText(resourceMap.getString("lblFax.text")); // NOI18N
        lblFax.setName("lblFax"); // NOI18N

        txtFax.setName("txtFax"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${fax}"), txtFax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnWPlantLayout = new javax.swing.GroupLayout(pnWPlant);
        pnWPlant.setLayout(pnWPlantLayout);
        pnWPlantLayout.setHorizontalGroup(
            pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWPlantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress)
                    .addComponent(lblWPlantRPT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtWPlantRPT, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhone)
                    .addComponent(lblFax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWPlantLayout.setVerticalGroup(
            pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnWPlantLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWPlantRPT)
                    .addComponent(txtWPlantRPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addContainerGap())
        );

        pnMaterials.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnMaterials.border.title"))); // NOI18N
        pnMaterials.setName("pnMaterials"); // NOI18N

        lblMatnrPCB40.setText(resourceMap.getString("lblMatnrPCB40.text")); // NOI18N
        lblMatnrPCB40.setName("lblMatnrPCB40"); // NOI18N

        txtMatnrPCB40.setName("txtMatnrPCB40"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${matnrPcb40}"), txtMatnrPCB40, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblMatnrBulk.setText(resourceMap.getString("lblMatnrBulk.text")); // NOI18N
        lblMatnrBulk.setName("lblMatnrBulk"); // NOI18N

        txtMatnrBulk.setName("txtMatnrBulk"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${matnrXmxa}"), txtMatnrBulk, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblSubContractClinker.setText(resourceMap.getString("lblSubContractClinker.text")); // NOI18N
        lblSubContractClinker.setName("lblSubContractClinker"); // NOI18N

        txtSubContractClinker.setName("txtSubContractClinker"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${matnrClinker}"), txtSubContractClinker, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnMaterialsLayout = new javax.swing.GroupLayout(pnMaterials);
        pnMaterials.setLayout(pnMaterialsLayout);
        pnMaterialsLayout.setHorizontalGroup(
            pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaterialsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSubContractClinker)
                    .addComponent(lblMatnrBulk)
                    .addComponent(lblMatnrPCB40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatnrBulk, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(txtMatnrPCB40, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(txtSubContractClinker, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMaterialsLayout.setVerticalGroup(
            pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaterialsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatnrPCB40)
                    .addComponent(txtMatnrPCB40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatnrBulk)
                    .addComponent(txtMatnrBulk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubContractClinker)
                    .addComponent(txtSubContractClinker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPPBaseVals.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnPPBaseVals.border.title"))); // NOI18N
        pnPPBaseVals.setName("pnPPBaseVals"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txfAct1Val.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        txfAct1Val.setText(resourceMap.getString("txfAct1Val.text")); // NOI18N
        txfAct1Val.setName("txfAct1Val"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${bact1Val}"), txfAct1Val, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        lblAct1Unit.setText(resourceMap.getString("lblAct1Unit.text")); // NOI18N
        lblAct1Unit.setName("lblAct1Unit"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txfAct2Val.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        txfAct2Val.setText(resourceMap.getString("txfAct2Val.text")); // NOI18N
        txfAct2Val.setName("txfAct2Val"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${bact2Val}"), txfAct2Val, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        lblAct2Unit.setText(resourceMap.getString("lblAct2Unit.text")); // NOI18N
        lblAct2Unit.setName("lblAct2Unit"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txfAct3Val.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        txfAct3Val.setText(resourceMap.getString("txfAct3Val.text")); // NOI18N
        txfAct3Val.setName("txfAct3Val"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${bact3Val}"), txfAct3Val, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        lblAct3Unit.setText(resourceMap.getString("lblAct3Unit.text")); // NOI18N
        lblAct3Unit.setName("lblAct3Unit"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        txfAct4Val.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        txfAct4Val.setText(resourceMap.getString("txfAct4Val.text")); // NOI18N
        txfAct4Val.setName("txfAct4Val"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${bact4Val}"), txfAct4Val, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        lblAct4Unit.setText(resourceMap.getString("lblAct4Unit.text")); // NOI18N
        lblAct4Unit.setName("lblAct4Unit"); // NOI18N

        javax.swing.GroupLayout pnPPBaseValsLayout = new javax.swing.GroupLayout(pnPPBaseVals);
        pnPPBaseVals.setLayout(pnPPBaseValsLayout);
        pnPPBaseValsLayout.setHorizontalGroup(
            pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPPBaseValsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPPBaseValsLayout.createSequentialGroup()
                        .addComponent(txfAct1Val, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAct1Unit)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(pnPPBaseValsLayout.createSequentialGroup()
                        .addComponent(txfAct3Val, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAct3Unit)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPPBaseValsLayout.createSequentialGroup()
                        .addComponent(txfAct2Val, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAct2Unit)
                        .addGap(7, 7, 7))
                    .addGroup(pnPPBaseValsLayout.createSequentialGroup()
                        .addComponent(txfAct4Val, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAct4Unit)))
                .addContainerGap())
        );
        pnPPBaseValsLayout.setVerticalGroup(
            pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPPBaseValsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfAct1Val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAct2Unit)
                    .addComponent(txfAct2Val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAct1Unit)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPPBaseValsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfAct3Val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAct3Unit)
                    .addComponent(jLabel7)
                    .addComponent(txfAct4Val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAct4Unit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnWBTol.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWBTol.border.title"))); // NOI18N
        pnWBTol.setName("pnWBTol"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        txfWB1Tol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        txfWB1Tol.setText(resourceMap.getString("txfWB1Tol.text")); // NOI18N
        txfWB1Tol.setName("txfWB1Tol"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${wb1Tol}"), txfWB1Tol, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        txfWB2Tol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        txfWB2Tol.setText(resourceMap.getString("txfWB2Tol.text")); // NOI18N
        txfWB2Tol.setName("txfWB2Tol"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${wb2Tol}"), txfWB2Tol, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout pnWBTolLayout = new javax.swing.GroupLayout(pnWBTol);
        pnWBTol.setLayout(pnWBTolLayout);
        pnWBTolLayout.setHorizontalGroup(
            pnWBTolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWBTolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfWB1Tol, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfWB2Tol, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        pnWBTolLayout.setVerticalGroup(
            pnWBTolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWBTolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWBTolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txfWB1Tol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txfWB2Tol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnRolesMap.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnRolesMap.border.title"))); // NOI18N
        pnRolesMap.setMinimumSize(new java.awt.Dimension(247, 84));
        pnRolesMap.setName("pnRolesMap"); // NOI18N

        lblRWatchman.setText(resourceMap.getString("lblRWatchman.text")); // NOI18N
        lblRWatchman.setName("lblRWatchman"); // NOI18N

        txtRWMan.setName("txtRWMan"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${roleWm}"), txtRWMan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblRStationStaff.setText(resourceMap.getString("lblRStationStaff.text")); // NOI18N
        lblRStationStaff.setName("lblRStationStaff"); // NOI18N

        txtRSStaff.setName("txtRSStaff"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${roleSs}"), txtRSStaff, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblRAdministrator.setText(resourceMap.getString("lblRAdministrator.text")); // NOI18N
        lblRAdministrator.setName("lblRAdministrator"); // NOI18N

        txtRAdmin.setName("txtRAdmin"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${roleAd}"), txtRAdmin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnRolesMapLayout = new javax.swing.GroupLayout(pnRolesMap);
        pnRolesMap.setLayout(pnRolesMapLayout);
        pnRolesMapLayout.setHorizontalGroup(
            pnRolesMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRolesMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRolesMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRAdministrator)
                    .addComponent(lblRWatchman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRolesMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtRWMan, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(lblRStationStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRSStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnRolesMapLayout.setVerticalGroup(
            pnRolesMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRolesMapLayout.createSequentialGroup()
                .addGroup(pnRolesMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRWatchman)
                    .addComponent(txtRWMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRSStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRStationStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRolesMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRAdministrator)
                    .addComponent(txtRAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        chkTALP.setText(resourceMap.getString("chkTALP.text")); // NOI18N
        chkTALP.setName("chkTALP"); // NOI18N

        chkPROC1.setText(resourceMap.getString("chkPROC.text")); // NOI18N
        chkPROC1.setName("chkPROC"); // NOI18N

        javax.swing.GroupLayout pnWholeGroupLayout = new javax.swing.GroupLayout(pnWholeGroup);
        pnWholeGroup.setLayout(pnWholeGroupLayout);
        pnWholeGroupLayout.setHorizontalGroup(
            pnWholeGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnWPlant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMaterials, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPPBaseVals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnWBTol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnWholeGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkTALP, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPROC1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(pnRolesMap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnWholeGroupLayout.setVerticalGroup(
            pnWholeGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWholeGroupLayout.createSequentialGroup()
                .addComponent(pnWPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPPBaseVals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnWBTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnRolesMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnWholeGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPROC1)
                    .addComponent(chkTALP))
                .addContainerGap())
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(SettingView.class, this);
        btnSave.setAction(actionMap.get("save")); // NOI18N
        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnWholeGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnWholeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public Task save() {
        return new SaveTask(WeighBridgeApp.getApplication());
    }

    private class SaveTask extends org.jdesktop.application.Task<Object, Void> {

        SaveTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SaveTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            String tmp = txtWPlantRPT.getText().trim();
            Number tmpNum = null;
            sapSetting.setNameRpt(tmp.isEmpty() ? null : tmp);
            tmp = txtAddress.getText().trim();
            sapSetting.setAddress(tmp.isEmpty() ? null : tmp);
            tmp = txtPhone.getText().trim();
            sapSetting.setPhone(tmp.isEmpty() ? null : tmp);
            tmp = txtFax.getText().trim();
            sapSetting.setFax(tmp.isEmpty() ? null : tmp);
            tmp = txtSubContractClinker.getText().trim();
            sapSetting.setMatnrClinker(tmp.isEmpty() ? null : tmp);
            tmp = txtMatnrPCB40.getText().trim();
            sapSetting.setMatnrPcb40(tmp.isEmpty() ? null : tmp);
            tmp = txtMatnrBulk.getText().trim();
            sapSetting.setMatnrXmxa(tmp.isEmpty() ? null : tmp);
            tmpNum = (Number) txfAct1Val.getValue();
            sapSetting.setBact1Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
            tmpNum = (Number) txfAct2Val.getValue();
            sapSetting.setBact2Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
            tmpNum = (Number) txfAct3Val.getValue();
            sapSetting.setBact3Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
            tmpNum = (Number) txfAct4Val.getValue();
            sapSetting.setBact4Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
            tmpNum = (Number) txfWB1Tol.getValue();
            sapSetting.setWb1Tol(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
            tmpNum = (Number) txfWB2Tol.getValue();
            sapSetting.setWb2Tol(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
            tmp = txtRAdmin.getText().trim();
            sapSetting.setRoleAd(tmp.isEmpty() ? null : tmp);
            tmp = txtRSStaff.getText().trim();
            sapSetting.setRoleSs(tmp.isEmpty() ? null : tmp);
            tmp = txtRWMan.getText().trim();
            sapSetting.setRoleWm(tmp.isEmpty() ? null : tmp);
            sapSetting.setCheckTalp(chkTALP.isSelected());

            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
            entityManager.merge(sapSetting);
            entityManager.getTransaction().commit();
            entityManager.clear();
            sapSetting = entityManager.find(SAPSetting.class, sapSetting.getSAPSettingPK());
            entityManager.clear();

            //{+20110119#01
            //Save process order checking
            Variant vari = new Variant();
            VariantPK variPK = new VariantPK();
            try {
                AppConfig lconfig = WeighBridgeApp.getApplication().getConfig();
                variPK.setMandt(lconfig.getsClient().toString());
                variPK.setWPlant(lconfig.getwPlant().toString());
                variPK.setParam("PROCESS_ORDER_CF");
                vari.setVariantPK(variPK);
                String checkP = "";
                if (chkPROC1.isSelected()) {
                    checkP = "X";
                }
                vari.setValue(checkP);
                if (!entityManager.getTransaction().isActive()) {
                    entityManager.getTransaction().begin();
                }
                entityManager.merge(vari);
                entityManager.getTransaction().commit();
                entityManager.clear();
            } catch (Exception e) {
            }
            //}+20110119#01
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            WeighBridgeApp.getApplication().setSapSetting(sapSetting);
            dispose();
        }

        @Override
        protected void failed(Throwable cause) {
            Logger.getLogger(LoginView.class.getName()).log(Level.ERROR, null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
            done();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkPROC1;
    private javax.swing.JCheckBox chkTALP;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAct1Unit;
    private javax.swing.JLabel lblAct2Unit;
    private javax.swing.JLabel lblAct3Unit;
    private javax.swing.JLabel lblAct4Unit;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblMatnrBulk;
    private javax.swing.JLabel lblMatnrPCB40;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRAdministrator;
    private javax.swing.JLabel lblRStationStaff;
    private javax.swing.JLabel lblRWatchman;
    private javax.swing.JLabel lblSubContractClinker;
    private javax.swing.JLabel lblWPlantRPT;
    private javax.swing.JPanel pnMaterials;
    private javax.swing.JPanel pnPPBaseVals;
    private javax.swing.JPanel pnRolesMap;
    private javax.swing.JPanel pnWBTol;
    private javax.swing.JPanel pnWPlant;
    private javax.swing.JPanel pnWholeGroup;
    private com.gcs.wb.jpa.entity.SAPSetting sapSetting;
    private javax.swing.JFormattedTextField txfAct1Val;
    private javax.swing.JFormattedTextField txfAct2Val;
    private javax.swing.JFormattedTextField txfAct3Val;
    private javax.swing.JFormattedTextField txfAct4Val;
    private javax.swing.JFormattedTextField txfWB1Tol;
    private javax.swing.JFormattedTextField txfWB2Tol;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtMatnrBulk;
    private javax.swing.JTextField txtMatnrPCB40;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRAdmin;
    private javax.swing.JTextField txtRSStaff;
    private javax.swing.JTextField txtRWMan;
    private javax.swing.JTextField txtSubContractClinker;
    private javax.swing.JTextField txtWPlantRPT;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
