/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingView.java
 *
 * Created on 17-06-2010, 14:41:08
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.jpa.entity.SAPSetting;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import com.gcs.wb.jpa.entity.Variant;
import com.gcs.wb.jpa.entity.VariantPK;
import com.gcs.wb.model.AppConfig;

/**
 *
 * @author vunguyent
 */
public class SettingView extends javax.swing.JDialog {

    /** Creates new form SettingView */
    public SettingView(java.awt.Frame parent) {
        super(parent);
        initComponents();
//        if (sapSetting.getCheckTalp() == null || sapSetting.getCheckTalp() == false) {
//            chkTALP.setSelected(false);
//        } else {
//            chkTALP.setSelected(true);
//        }

        // set select for checkbox chkPOV
        if (sapSetting.getCheckPov() == null || sapSetting.getCheckPov() == false) {
            chkPOV.setSelected(false);
        } else {
            chkPOV.setSelected(true);
        }
        //----------------------------------
        //+20110119#01
        Variant vari = new Variant();
        VariantPK variPK = new VariantPK();
        AppConfig lconfig = WeighBridgeApp.getApplication().getConfig();
        variPK.setMandt(lconfig.getsClient().toString());
        variPK.setWPlant(lconfig.getwPlant().toString());
        variPK.setParam("PROCESS_ORDER_CF");
        vari.setVariantPK(variPK);
        vari = entityManager.find(Variant.class, vari.getVariantPK());
        String chkPROC = "";
        if (vari != null) {
            try {
                chkPROC = vari.getValue().toString();
            } catch (Exception e) {
            }
        }
//        if (chkPROC.equals("X")) {
//            chkPROC1.setSelected(true);
//        }
        entityManager.clear();
        //+20110119#01
        //----------------------------------
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sapSetting = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getSapSetting();
        entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        pnWholeGroup = new javax.swing.JPanel();
        pnWPlant = new javax.swing.JPanel();
        lblWPlantRPT = new javax.swing.JLabel();
        txtWPlantRPT = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        pnPO = new javax.swing.JPanel();
        chkPOV = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(SettingView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnWholeGroup.setName("pnWholeGroup"); // NOI18N

        pnWPlant.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnWPlant.border.title"))); // NOI18N
        pnWPlant.setName("pnWPlant"); // NOI18N

        lblWPlantRPT.setText(resourceMap.getString("lblWPlantRPT.text")); // NOI18N
        lblWPlantRPT.setName("lblWPlantRPT"); // NOI18N

        txtWPlantRPT.setName("txtWPlantRPT"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${nameRpt}"), txtWPlantRPT, org.jdesktop.beansbinding.BeanProperty.create("text"), "");
        bindingGroup.addBinding(binding);

        lblAddress.setText(resourceMap.getString("lblAddress.text")); // NOI18N
        lblAddress.setName("lblAddress"); // NOI18N

        txtAddress.setName("txtAddress"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${address}"), txtAddress, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblPhone.setText(resourceMap.getString("lblPhone.text")); // NOI18N
        lblPhone.setName("lblPhone"); // NOI18N

        txtPhone.setName("txtPhone"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${phone}"), txtPhone, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblFax.setText(resourceMap.getString("lblFax.text")); // NOI18N
        lblFax.setName("lblFax"); // NOI18N

        txtFax.setName("txtFax"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sapSetting, org.jdesktop.beansbinding.ELProperty.create("${fax}"), txtFax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnWPlantLayout = new javax.swing.GroupLayout(pnWPlant);
        pnWPlant.setLayout(pnWPlantLayout);
        pnWPlantLayout.setHorizontalGroup(
            pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWPlantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress)
                    .addComponent(lblWPlantRPT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtWPlantRPT, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhone)
                    .addComponent(lblFax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnWPlantLayout.setVerticalGroup(
            pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnWPlantLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWPlantRPT)
                    .addComponent(txtWPlantRPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnWPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addContainerGap())
        );

        pnPO.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnPO.border.title"))); // NOI18N
        pnPO.setName("pnPO"); // NOI18N

        chkPOV.setText(resourceMap.getString("chkPOV.text")); // NOI18N
        chkPOV.setToolTipText(resourceMap.getString("chkPOV.toolTipText")); // NOI18N
        chkPOV.setName("chkPOV"); // NOI18N

        javax.swing.GroupLayout pnPOLayout = new javax.swing.GroupLayout(pnPO);
        pnPO.setLayout(pnPOLayout);
        pnPOLayout.setHorizontalGroup(
            pnPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPOLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(chkPOV, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        pnPOLayout.setVerticalGroup(
            pnPOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPOV)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnWholeGroupLayout = new javax.swing.GroupLayout(pnWholeGroup);
        pnWholeGroup.setLayout(pnWholeGroupLayout);
        pnWholeGroupLayout.setHorizontalGroup(
            pnWholeGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnWPlant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnWholeGroupLayout.setVerticalGroup(
            pnWholeGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWholeGroupLayout.createSequentialGroup()
                .addComponent(pnWPlant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPO.getAccessibleContext().setAccessibleName(resourceMap.getString("pnMaterials.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(SettingView.class, this);
        btnSave.setAction(actionMap.get("save")); // NOI18N
        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnWholeGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnWholeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public Task save() {
        return new SaveTask(WeighBridgeApp.getApplication());
    }

    private class SaveTask extends org.jdesktop.application.Task<Object, Void> {

        SaveTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SaveTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            String tmp = txtWPlantRPT.getText().trim();
            Number tmpNum = null;
            sapSetting.setNameRpt(tmp.isEmpty() ? null : tmp);
            tmp = txtAddress.getText().trim();
            sapSetting.setAddress(tmp.isEmpty() ? null : tmp);
            tmp = txtPhone.getText().trim();
            sapSetting.setPhone(tmp.isEmpty() ? null : tmp);
            tmp = txtFax.getText().trim();
            sapSetting.setFax(tmp.isEmpty() ? null : tmp);
            sapSetting.setCheckPov(chkPOV.isSelected() ? true: false);
//            tmp = txtSubContractClinker.getText().trim();
//            sapSetting.setMatnrClinker(tmp.isEmpty() ? null : tmp);
//            tmp = txtMatnrPCB40.getText().trim();
//            sapSetting.setMatnrPcb40(tmp.isEmpty() ? null : tmp);
//            tmp = txtMatnrBulk.getText().trim();
//            sapSetting.setMatnrXmxa(tmp.isEmpty() ? null : tmp);
//            tmpNum = (Number) txfAct1Val.getValue();
//            sapSetting.setBact1Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
//            tmpNum = (Number) txfAct2Val.getValue();
//            sapSetting.setBact2Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
//            tmpNum = (Number) txfAct3Val.getValue();
//            sapSetting.setBact3Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
//            tmpNum = (Number) txfAct4Val.getValue();
//            sapSetting.setBact4Val(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
//            tmpNum = (Number) txfWB1Tol.getValue();
//            sapSetting.setWb1Tol(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
//            tmpNum = (Number) txfWB2Tol.getValue();
//            sapSetting.setWb2Tol(tmpNum == null ? null : new BigDecimal(tmpNum.doubleValue()));
//            tmp = txtRAdmin.getText().trim();
//            sapSetting.setRoleAd(tmp.isEmpty() ? null : tmp);
//            tmp = txtRSStaff.getText().trim();
//            sapSetting.setRoleSs(tmp.isEmpty() ? null : tmp);
//            tmp = txtRWMan.getText().trim();
            sapSetting.setRoleWm(tmp.isEmpty() ? null : tmp);
            sapSetting.setCheckTalp(chkPOV.isSelected());

            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
            entityManager.merge(sapSetting);
            entityManager.getTransaction().commit();
            entityManager.clear();
            sapSetting = entityManager.find(SAPSetting.class, sapSetting.getSAPSettingPK());
            entityManager.clear();

            //{+20110119#01
            //Save process order checking
            Variant vari = new Variant();
            VariantPK variPK = new VariantPK();
            try {
                AppConfig lconfig = WeighBridgeApp.getApplication().getConfig();
                variPK.setMandt(lconfig.getsClient().toString());
                variPK.setWPlant(lconfig.getwPlant().toString());
                variPK.setParam("PROCESS_ORDER_CF");
                vari.setVariantPK(variPK);
//                String checkP = "";
//                if (chkPROC1.isSelected()) {
//                    checkP = "X";
//                }
//                vari.setValue(checkP);
                if (!entityManager.getTransaction().isActive()) {
                    entityManager.getTransaction().begin();
                }
                entityManager.merge(vari);
                entityManager.getTransaction().commit();
                entityManager.clear();
            } catch (Exception e) {
            }
            //}+20110119#01
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            WeighBridgeApp.getApplication().setSapSetting(sapSetting);
            dispose();
        }

        @Override
        protected void failed(Throwable cause) {
            Logger.getLogger(LoginView.class.getName()).log(Level.ERROR, null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
            done();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkPOV;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblWPlantRPT;
    private javax.swing.JPanel pnPO;
    private javax.swing.JPanel pnWPlant;
    private javax.swing.JPanel pnWholeGroup;
    private com.gcs.wb.jpa.entity.SAPSetting sapSetting;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtWPlantRPT;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
