/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransportAgentView.java
 *
 * Created on 06-01-2020
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.bapi.helper.SAP2Local;
import com.gcs.wb.jpa.JpaProperties;
import com.gcs.wb.jpa.entity.TransportAgent;
import com.gcs.wb.jpa.entity.TransportAgentVehicle;
import com.gcs.wb.jpa.entity.Vehicle;
import com.gcs.wb.jpa.repositorys.TransportAgentRepository;
import com.gcs.wb.jpa.repositorys.TransportAgentVehicleRepository;
import com.gcs.wb.jpa.repositorys.VehicleRepository;
import com.gcs.wb.model.AppConfig;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author thang
 */
public class TransportAgentView extends javax.swing.JInternalFrame {

    private AppConfig config = null;
    private EntityManager entityManager = JpaProperties.getEntityManager();
    private TransportAgentRepository transportAgentRepository = new TransportAgentRepository();
    private VehicleRepository vehicleRepository = new VehicleRepository();
    private TransportAgentVehicleRepository transportAgentVehicleRepository = new TransportAgentVehicleRepository();

    /** Creates new form TransportAgentView */
    public TransportAgentView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        transportAgentSelected = new com.gcs.wb.jpa.entity.TransportAgent();
        vehicleSelected = new com.gcs.wb.jpa.entity.Vehicle();
        pnTransportAgent = new javax.swing.JPanel();
        spnTransportAgent = new javax.swing.JScrollPane();
        lstTransportAgent = new javax.swing.JList();
        pnVehicle = new javax.swing.JPanel();
        spnVehicle = new javax.swing.JScrollPane();
        lstVehicle = new javax.swing.JList();
        lblLicensePlate = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        btnVehicleSave = new javax.swing.JButton();
        btnVehicleRemove = new javax.swing.JButton();
        chkProhibitVehicle = new javax.swing.JCheckBox();
        btnProhibitApply = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(TransportAgentView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnTransportAgent.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn vị vận chuyển"));
        pnTransportAgent.setName("pnTransportAgent"); // NOI18N

        spnTransportAgent.setName("spnTransportAgent"); // NOI18N

        lstTransportAgent.setModel(getTransportAgentsModel());
        lstTransportAgent.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof TransportAgent) {
                    TransportAgent ta = (TransportAgent)value;
                    setText(ta.getName());
                }
                return this;
            }
        });
        lstTransportAgent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTransportAgent.setName("lstTransportAgent"); // NOI18N
        lstTransportAgent.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTransportAgentValueChanged(evt);
            }
        });
        spnTransportAgent.setViewportView(lstTransportAgent);

        javax.swing.GroupLayout pnTransportAgentLayout = new javax.swing.GroupLayout(pnTransportAgent);
        pnTransportAgent.setLayout(pnTransportAgentLayout);
        pnTransportAgentLayout.setHorizontalGroup(
            pnTransportAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransportAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnTransportAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTransportAgentLayout.setVerticalGroup(
            pnTransportAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransportAgentLayout.createSequentialGroup()
                .addComponent(spnTransportAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(147, 147, 147))
        );

        pnVehicle.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnVehicle.border.title"))); // NOI18N
        pnVehicle.setName("pnVehicle"); // NOI18N

        spnVehicle.setName("spnVehicle"); // NOI18N

        lstVehicle.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Vehicle) {
                    Vehicle ta = (Vehicle)value;
                    setText(ta.getPlateNo());
                }
                return this;
            }
        });
        lstVehicle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVehicle.setName("lstVehicle"); // NOI18N
        lstVehicle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVehicleValueChanged(evt);
            }
        });
        spnVehicle.setViewportView(lstVehicle);

        lblLicensePlate.setText(resourceMap.getString("lblLicensePlate.text")); // NOI18N
        lblLicensePlate.setName("lblLicensePlate"); // NOI18N

        txtLicensePlate.setName("txtLicensePlate"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstTransportAgent, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtLicensePlate, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtLicensePlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicensePlateFocusGained(evt);
            }
        });
        txtLicensePlate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicensePlateKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(TransportAgentView.class, this);
        btnVehicleSave.setAction(actionMap.get("saveVehicle")); // NOI18N
        btnVehicleSave.setText(resourceMap.getString("btnVehicleSave.text")); // NOI18N
        btnVehicleSave.setName("btnVehicleSave"); // NOI18N

        btnVehicleRemove.setText(resourceMap.getString("btnVehicleRemove.text")); // NOI18N
        btnVehicleRemove.setName("btnVehicleRemove"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstVehicle, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnVehicleRemove, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnVehicleRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleRemoveActionPerformed(evt);
            }
        });

        chkProhibitVehicle.setText(resourceMap.getString("chkProhibitVehicle.text")); // NOI18N
        chkProhibitVehicle.setName("chkProhibitVehicle"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstVehicle, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), chkProhibitVehicle, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnProhibitApply.setText(resourceMap.getString("btnProhibitApply.text")); // NOI18N
        btnProhibitApply.setName("btnProhibitApply"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstVehicle, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnProhibitApply, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnProhibitApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProhibitApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnVehicleLayout = new javax.swing.GroupLayout(pnVehicle);
        pnVehicle.setLayout(pnVehicleLayout);
        pnVehicleLayout.setHorizontalGroup(
            pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnVehicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(pnVehicleLayout.createSequentialGroup()
                        .addComponent(chkProhibitVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnProhibitApply))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVehicleLayout.createSequentialGroup()
                        .addComponent(btnVehicleRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnVehicleSave))
                    .addGroup(pnVehicleLayout.createSequentialGroup()
                        .addComponent(lblLicensePlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicensePlate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnVehicleLayout.setVerticalGroup(
            pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVehicleLayout.createSequentialGroup()
                .addComponent(spnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicensePlate)
                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVehicleSave)
                    .addComponent(btnVehicleRemove))
                .addGap(11, 11, 11)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProhibitVehicle)
                    .addComponent(btnProhibitApply))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTransportAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnTransportAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstTransportAgentValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTransportAgentValueChanged
        transportAgentSelected = (TransportAgent) lstTransportAgent.getSelectedValue();
        if (transportAgentSelected != null) {
            vehicleSelected = null;
            lstVehicle.clearSelection();
            lstVehicle.setModel(getVehiclesModel());
        }
    }//GEN-LAST:event_lstTransportAgentValueChanged

    private void lstVehicleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVehicleValueChanged
        vehicleSelected = (Vehicle) lstVehicle.getSelectedValue();
        if (vehicleSelected != null) {
            chkProhibitVehicle.setSelected(vehicleSelected.isProhibit());
        }
    }//GEN-LAST:event_lstVehicleValueChanged

    private void txtLicensePlateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicensePlateKeyReleased
        setVehicleCreatable(validateLicensePlate());
    }//GEN-LAST:event_txtLicensePlateKeyReleased

    private void txtLicensePlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicensePlateFocusGained
        lstVehicle.clearSelection();
        vehicleSelected = null;
    }//GEN-LAST:event_txtLicensePlateFocusGained

private void btnVehicleRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleRemoveActionPerformed
    EntityTransaction entityTransaction = entityManager.getTransaction();
    try {
        if (!entityTransaction.isActive()) {
            entityTransaction.begin();
        }

        TransportAgentVehicle transportAgentVehicle =
                transportAgentVehicleRepository.findByTransportAgentIdAndVehicleId(
                transportAgentSelected.getId(), vehicleSelected.getId());
        entityManager.remove(transportAgentVehicle);

        entityTransaction.commit();
        entityManager.clear();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Xóa phương tiện vận chuyển không thành công");
        entityTransaction.rollback();
        entityManager.clear();
    }

    lstVehicle.clearSelection();
    lstVehicle.setModel(getVehiclesModel());
    vehicleSelected = null;
}//GEN-LAST:event_btnVehicleRemoveActionPerformed

private void btnProhibitApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProhibitApplyActionPerformed
    EntityTransaction entityTransaction = entityManager.getTransaction();
    try {
        if (!entityTransaction.isActive()) {
            entityTransaction.begin();
        }

        vehicleSelected.setProhibit(chkProhibitVehicle.isSelected());
        entityManager.merge(vehicleSelected);
        entityTransaction.commit();
        entityManager.clear();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Thực hiện cấm xe không thành công");
        entityTransaction.rollback();
        entityManager.clear();
    }

    chkProhibitVehicle.setSelected(false);
    vehicleSelected = null;
    lstVehicle.clearSelection();
    lstVehicle.setModel(getVehiclesModel());
}//GEN-LAST:event_btnProhibitApplyActionPerformed

    private boolean validateLicensePlate() {
        boolean isLicensePlate = false;
        String licensePlateStr = txtLicensePlate.getText().trim();

        Matcher matcher = LICENSE_PLATE_PATTERN.matcher(licensePlateStr);
        isLicensePlate = !licensePlateStr.isEmpty() && matcher.matches();
        lblLicensePlate.setForeground(isLicensePlate ? Color.black : Color.red);

        return isLicensePlate;
    }

    private DefaultListModel getTransportAgentsModel() {
        config = WeighBridgeApp.getApplication().getConfig();
        EntityTransaction entityTransaction = entityManager.getTransaction();
        List<TransportAgent> transportAgents = transportAgentRepository.getListTransportAgent();

        // get from SAP
        List<TransportAgent> transportAgentsSAP = SAP2Local.getTransportAgentList(config.getwPlant());
        //sync SAP <=> DB
        // delete data DB not exist SAP
        for (TransportAgent transportAgent : transportAgents) {
            if (transportAgentsSAP.indexOf(transportAgent) == -1) {
                // delete in table Vehicle
                List<TransportAgentVehicle> transportAgentVehicles = transportAgentVehicleRepository.findByTransportAgentId(transportAgent.getId());

                if (!entityTransaction.isActive()) {
                    entityTransaction.begin();
                }

                try {
                    for (TransportAgentVehicle transportAgentVehicle : transportAgentVehicles) {
                        entityManager.remove(transportAgentVehicle);

                        entityManager.remove(transportAgentVehicle.getVehicle());
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Xóa phương tiện vận chuyển không thành công");
                    entityTransaction.rollback();
                    return null;
                }

                // delete dvvc
                try {
                    if (!entityManager.contains(transportAgent)) {
                        transportAgent = entityManager.merge(transportAgent);
                    }
                    entityManager.remove(transportAgent);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Xóa nhà vận chuyển không thành công");
                    entityTransaction.rollback();
                    return null;
                }

                entityTransaction.commit();
                entityManager.clear();
            }
        }

        try {
            if (!entityTransaction.isActive()) {
                entityTransaction.begin();
            }
            // update dara SAP -> DB
            for (TransportAgent transportAgentSAP : transportAgentsSAP) {
                int index = transportAgents.indexOf(transportAgentSAP);
                if (index == -1) {
                    entityManager.persist(transportAgentSAP);
                } else {
                    transportAgentSAP.setId(transportAgents.get(index).getId());
                    entityManager.merge(transportAgentSAP);
                }
            }

            entityTransaction.commit();
            entityManager.clear();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Đồng bộ đơn vị vận chuyển không thành công!");
            entityTransaction.rollback();
            return null;
        }

        // get dvvc
        transportAgents = transportAgentRepository.getListTransportAgent();
        DefaultListModel model = new DefaultListModel();
        for (TransportAgent transportAgent : transportAgents) {
            model.addElement(transportAgent);
        }
        return model;
    }

    private DefaultListModel getVehiclesModel() {
        List<TransportAgentVehicle> transportAgentVehicles = transportAgentVehicleRepository.findByTransportAgentId(transportAgentSelected.getId());
        DefaultListModel model = new DefaultListModel();
        for (TransportAgentVehicle transportAgentVehicle : transportAgentVehicles) {
            model.addElement(transportAgentVehicle.getVehicle());
        }
        return model;
    }

    @Action(enabledProperty = "vehicleCreatable")
    public void saveVehicle() {
        TransportAgentVehicle transportAgentVehicle = new TransportAgentVehicle();
        Vehicle vehicle = vehicleRepository.findByPlateNo(txtLicensePlate.getText().trim());

        EntityTransaction entityTransaction = entityManager.getTransaction();
        try {
            if (!entityTransaction.isActive()) {
                entityTransaction.begin();
            }

            if (vehicle == null) {
                // insert new vehicle 
                vehicle = new Vehicle();
                vehicle.setPlateNo(txtLicensePlate.getText().trim());
                vehicle.setProhibit(false);
                entityManager.persist(vehicle);

                // insert vehicle relationship
                transportAgentVehicle.setTransportAgent(transportAgentSelected);
                transportAgentVehicle.setVehicle(vehicle);
                entityManager.persist(transportAgentVehicle);
            } else {
                // check vehicle has exit in transport agent
                transportAgentVehicle = transportAgentVehicleRepository.findByTransportAgentIdAndVehicleId(transportAgentSelected.getId(), vehicle.getId());
                if (transportAgentVehicle != null) {
                    JOptionPane.showMessageDialog(rootPane, "Số xe "
                            + txtLicensePlate.getText().trim()
                            + " đã được đăng ký cho đơn vị vận chuyển "
                            + transportAgentSelected.getName());
                    return;
                } else {
                    // insert vehicle relationship
                    transportAgentVehicle = new TransportAgentVehicle();
                    transportAgentVehicle.setTransportAgent(transportAgentSelected);
                    transportAgentVehicle.setVehicle(vehicle);
                    entityManager.persist(transportAgentVehicle);
                }
            }

            entityTransaction.commit();
            entityManager.clear();

            setVehicleCreatable(false);
            vehicleSelected = null;
            txtLicensePlate.setText("");
            lstVehicle.clearSelection();
            lstVehicle.setModel(getVehiclesModel());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi khi thêm mới biển số xe!");

            entityTransaction.rollback();
            entityManager.clear();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Form's Properties">
    public boolean isVehicleCreatable() {
        return vehicleCreatable;
    }

    public void setVehicleCreatable(boolean b) {
        boolean old = isVehicleCreatable();
        this.vehicleCreatable = b;
        firePropertyChange("vehicleCreatable", old, isVehicleCreatable());
    }
    // </editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProhibitApply;
    private javax.swing.JButton btnVehicleRemove;
    private javax.swing.JButton btnVehicleSave;
    private javax.swing.JCheckBox chkProhibitVehicle;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JList lstTransportAgent;
    private javax.swing.JList lstVehicle;
    private javax.swing.JPanel pnTransportAgent;
    private javax.swing.JPanel pnVehicle;
    private javax.swing.JScrollPane spnTransportAgent;
    private javax.swing.JScrollPane spnVehicle;
    private com.gcs.wb.jpa.entity.TransportAgent transportAgentSelected;
    private javax.swing.JTextField txtLicensePlate;
    private com.gcs.wb.jpa.entity.Vehicle vehicleSelected;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private boolean vehicleCreatable = false;
    private static final Pattern LICENSE_PLATE_PATTERN = Pattern.compile("^(\\d{2}[A-Z]-\\d{4})|(\\d{2}[A-Z]-\\d{3}.\\d{2})$");
}
