/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * TransportAgentView.java
 *
 * Created on 06-01-2020
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.base.constant.Constants;
import com.gcs.wb.base.validator.DateFromToValidator;
import com.gcs.wb.controller.TransportAgentController;
import com.gcs.wb.jpa.entity.TransportAgent;
import com.gcs.wb.jpa.entity.Vehicle;
import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author thanghl
 */
public class TransportAgentView extends javax.swing.JInternalFrame {

    public TransportAgentController transportAgentController = new TransportAgentController();
    private boolean vehicleCreatable = false;
    public ResourceMap resourceMapMsg = Application.getInstance(WeighBridgeApp.class).getContext().getResourceMap(TransportAgentView.class);
    public static final String SDATE = "date";
    private final DateFromToValidator dateFromToValidator = new DateFromToValidator();

    /**
     * Creates new form TransportAgentView
     */
    public TransportAgentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnTransportAgent = new javax.swing.JPanel();
        spnTransportAgent = new javax.swing.JScrollPane();
        lstTransportAgent = new javax.swing.JList();
        pnVehicle = new javax.swing.JPanel();
        spnVehicle = new javax.swing.JScrollPane();
        lstVehicle = new javax.swing.JList();
        lblLicensePlate = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        btnVehicleSave = new javax.swing.JButton();
        btnVehicleRemove = new javax.swing.JButton();
        lblValidFrom = new javax.swing.JLabel();
        lblValidTo = new javax.swing.JLabel();
        dpValidFrom = new org.jdesktop.swingx.JXDatePicker();
        dpValidTo = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(TransportAgentView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnTransportAgent.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn vị vận chuyển"));
        pnTransportAgent.setName("pnTransportAgent"); // NOI18N

        spnTransportAgent.setName("spnTransportAgent"); // NOI18N

        lstTransportAgent.setModel(getTransportAgentsModel());
        lstTransportAgent.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof TransportAgent) {
                    TransportAgent ta = (TransportAgent)value;
                    setText(ta.getName());
                }
                return this;
            }
        });
        lstTransportAgent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTransportAgent.setName("lstTransportAgent"); // NOI18N
        lstTransportAgent.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTransportAgentValueChanged(evt);
            }
        });
        spnTransportAgent.setViewportView(lstTransportAgent);

        javax.swing.GroupLayout pnTransportAgentLayout = new javax.swing.GroupLayout(pnTransportAgent);
        pnTransportAgent.setLayout(pnTransportAgentLayout);
        pnTransportAgentLayout.setHorizontalGroup(
            pnTransportAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransportAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnTransportAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTransportAgentLayout.setVerticalGroup(
            pnTransportAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransportAgentLayout.createSequentialGroup()
                .addComponent(spnTransportAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pnVehicle.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnVehicle.border.title"))); // NOI18N
        pnVehicle.setName("pnVehicle"); // NOI18N

        spnVehicle.setName("spnVehicle"); // NOI18N

        lstVehicle.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Vehicle) {
                    Vehicle ta = (Vehicle)value;
                    setText(ta.getPlateNo());
                }
                return this;
            }
        });
        lstVehicle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVehicle.setName("lstVehicle"); // NOI18N
        lstVehicle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVehicleValueChanged(evt);
            }
        });
        spnVehicle.setViewportView(lstVehicle);

        lblLicensePlate.setText(resourceMap.getString("lblLicensePlate.text")); // NOI18N
        lblLicensePlate.setName("lblLicensePlate"); // NOI18N

        txtLicensePlate.setName("txtLicensePlate"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstTransportAgent, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtLicensePlate, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtLicensePlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicensePlateFocusGained(evt);
            }
        });
        txtLicensePlate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicensePlateKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(TransportAgentView.class, this);
        btnVehicleSave.setAction(actionMap.get("saveVehicle")); // NOI18N
        btnVehicleSave.setText(resourceMap.getString("btnVehicleSave.text")); // NOI18N
        btnVehicleSave.setName("btnVehicleSave"); // NOI18N

        btnVehicleRemove.setText(resourceMap.getString("btnVehicleRemove.text")); // NOI18N
        btnVehicleRemove.setName("btnVehicleRemove"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstVehicle, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnVehicleRemove, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnVehicleRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleRemoveActionPerformed(evt);
            }
        });

        lblValidFrom.setText(resourceMap.getString("lblValidFrom.text")); // NOI18N
        lblValidFrom.setName("lblValidFrom"); // NOI18N

        lblValidTo.setText(resourceMap.getString("lblValidTo.text")); // NOI18N
        lblValidTo.setName("lblValidTo"); // NOI18N

        dpValidFrom.setDate(null);
        dpValidFrom.setName("dpValidFrom"); // NOI18N
        dpValidFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpValidFromPropertyChange(evt);
            }
        });

        dpValidTo.setDate(null);
        dpValidTo.setName("dpValidTo"); // NOI18N
        dpValidTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpValidToPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnVehicleLayout = new javax.swing.GroupLayout(pnVehicle);
        pnVehicle.setLayout(pnVehicleLayout);
        pnVehicleLayout.setHorizontalGroup(
            pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVehicleLayout.createSequentialGroup()
                        .addComponent(btnVehicleRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btnVehicleSave))
                    .addComponent(lblLicensePlate)
                    .addGroup(pnVehicleLayout.createSequentialGroup()
                        .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValidFrom)
                            .addComponent(lblValidTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(dpValidTo, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(dpValidFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnVehicleLayout.setVerticalGroup(
            pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVehicleLayout.createSequentialGroup()
                .addComponent(spnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicensePlate)
                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValidFrom)
                    .addComponent(dpValidFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValidTo)
                    .addComponent(dpValidTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVehicleSave)
                    .addComponent(btnVehicleRemove))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTransportAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnTransportAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstTransportAgentValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTransportAgentValueChanged
        transportAgentSelected = (TransportAgent) lstTransportAgent.getSelectedValue();
        dpValidFrom.setBackground(Color.black);
        dpValidTo.setBackground(Color.black);
        if (transportAgentSelected != null) {
            dpValidFrom.setDate(null);
            dpValidTo.setDate(null);
            txtLicensePlate.setEditable(true);
            txtLicensePlate.setText("");
            vehicleSelected = null;
            lstVehicle.clearSelection();
            lstVehicle.setModel(getVehiclesModel());
        }
    }//GEN-LAST:event_lstTransportAgentValueChanged

    private void lstVehicleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVehicleValueChanged
        vehicleSelected = (Vehicle) lstVehicle.getSelectedValue();

        if (vehicleSelected != null) {
            txtLicensePlate.setText(vehicleSelected.getPlateNo());
            txtLicensePlate.setEditable(false);
            txtLicensePlate.setEnabled(false);
            dpValidFrom.setDate(vehicleSelected.getValidFrom());
            dpValidTo.setDate(vehicleSelected.getValidTo());
        }
    }//GEN-LAST:event_lstVehicleValueChanged

    private void txtLicensePlateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicensePlateKeyReleased
        String plateNo = txtLicensePlate.getText().trim().toUpperCase();
        txtLicensePlate.setText(plateNo);

        boolean isValid = validateLicensePlate();
        setVehicleCreatable(isValid);

        if (isValid) {
            Vehicle vehicle = transportAgentController.getVehicle(plateNo);
            if (vehicle != null) {
                dpValidFrom.setDate(vehicle.getValidFrom());
                dpValidTo.setDate(vehicle.getValidTo());
            } else {
                dpValidFrom.setDate(new Date());
                Calendar calendar = Calendar.getInstance();
                calendar.set(9999, 12, 31);
                dpValidTo.setDate(calendar.getTime());
            }
        }
    }//GEN-LAST:event_txtLicensePlateKeyReleased

    private void txtLicensePlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicensePlateFocusGained
        lstVehicle.clearSelection();
        vehicleSelected = null;
    }//GEN-LAST:event_txtLicensePlateFocusGained

private void btnVehicleRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleRemoveActionPerformed
    // remove vehicle
    transportAgentController.vehicleRemoveActionPerformed(transportAgentSelected, vehicleSelected);
    lstVehicle.clearSelection();
    lstVehicle.setModel(getVehiclesModel());
    vehicleSelected = null;
}//GEN-LAST:event_btnVehicleRemoveActionPerformed

private void dpValidFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpValidFromPropertyChange
// TODO add your handling code here:
    if (SDATE.equals(evt.getPropertyName())) {
        validateDateForm();
    }
}//GEN-LAST:event_dpValidFromPropertyChange

private void dpValidToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpValidToPropertyChange
// TODO add your handling code here:
    if (SDATE.equals(evt.getPropertyName())) {
        validateDateForm();
    }
}//GEN-LAST:event_dpValidToPropertyChange

    private void validateDateForm() {
        try {
            dateFromToValidator.validate(dpValidFrom.getDate(), dpValidTo.getDate());

            lblValidFrom.setForeground(Color.black);
            lblValidTo.setForeground(Color.black);
            if (txtLicensePlate.getText() != null && dpValidFrom.getDate() != null && dpValidTo.getDate() != null) {
                btnVehicleSave.setEnabled(true);
            }
        } catch (IllegalArgumentException ex) {
            if (dpValidFrom.getDate() == null) {
                lblValidFrom.setForeground(Color.black);
            } else {
                lblValidFrom.setForeground(Color.red);
            }
            if (dpValidTo.getDate() == null) {
                lblValidTo.setForeground(Color.black);
            } else {
                lblValidTo.setForeground(Color.red);
            }
            btnVehicleSave.setEnabled(false);
        }
    }

    private boolean validateLicensePlate() {
        boolean isLicensePlate = false;
        String licensePlateStr = txtLicensePlate.getText().trim();

        Matcher matcher = Constants.TransportAgent.LICENSE_PLATE_PATTERN.matcher(licensePlateStr);
        isLicensePlate = !licensePlateStr.isEmpty() && matcher.matches();
        lblLicensePlate.setForeground(isLicensePlate ? Color.black : Color.red);

        return isLicensePlate;
    }

    private DefaultListModel getTransportAgentsModel() {
        // get dvvc
        return transportAgentController.getTransportAgentsModel();
    }

    private DefaultListModel getVehiclesModel() {
        return transportAgentController.getVehiclesModel(transportAgentSelected);
    }

    @Action(enabledProperty = "vehicleCreatable")
    public void saveVehicle() {

        //save vehicle
        transportAgentController.saveVehicle(txtLicensePlate.getText().trim(), transportAgentSelected, dpValidFrom.getDate(), dpValidTo.getDate());
        setVehicleCreatable(false);
        vehicleSelected = null;
        txtLicensePlate.setText("");
        dpValidFrom.setDate(null);
        dpValidTo.setDate(null);
        dpValidFrom.setBackground(Color.black);
        dpValidTo.setBackground(Color.black);
        lstVehicle.clearSelection();
        lstVehicle.setModel(getVehiclesModel());
    }

    // <editor-fold defaultstate="collapsed" desc="Form's Properties">
    public boolean isVehicleCreatable() {
        return vehicleCreatable;
    }

    public void setVehicleCreatable(boolean b) {
        boolean old = isVehicleCreatable();
        this.vehicleCreatable = b;
        firePropertyChange("vehicleCreatable", old, isVehicleCreatable());
    }
    // </editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVehicleRemove;
    private javax.swing.JButton btnVehicleSave;
    private org.jdesktop.swingx.JXDatePicker dpValidFrom;
    private org.jdesktop.swingx.JXDatePicker dpValidTo;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblValidFrom;
    private javax.swing.JLabel lblValidTo;
    private javax.swing.JList lstTransportAgent;
    private javax.swing.JList lstVehicle;
    private javax.swing.JPanel pnTransportAgent;
    private javax.swing.JPanel pnVehicle;
    private javax.swing.JScrollPane spnTransportAgent;
    private javax.swing.JScrollPane spnVehicle;
    private javax.swing.JTextField txtLicensePlate;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private com.gcs.wb.jpa.entity.TransportAgent transportAgentSelected;
    private com.gcs.wb.jpa.entity.Vehicle vehicleSelected;
}
