/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VRView.java
 *
 * Created on 05-05-2010, 09:12:34
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.jpa.entity.TransportAgent;
import com.gcs.wb.jpa.entity.Vehicle;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.TypedQuery;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author vunguyent
 */
public class VRView1 extends javax.swing.JInternalFrame {

    /** Creates new form VRView */
    public VRView1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tAgent = new com.gcs.wb.jpa.entity.TransportAgent();
        vehicle = new com.gcs.wb.jpa.entity.Vehicle();
        entityManager = WeighBridgeApp.getApplication().getEm();
        pnTAgent = new javax.swing.JPanel();
        spTAgent = new javax.swing.JScrollPane();
        lstTAgent = new javax.swing.JList();
        lblAName = new javax.swing.JLabel();
        lblAAbbr = new javax.swing.JLabel();
        txtAName = new javax.swing.JTextField();
        txtAAbbr = new javax.swing.JTextField();
        btnASave = new javax.swing.JButton();
        btnARemove = new javax.swing.JButton();
        pnVehicle = new javax.swing.JPanel();
        spVehicle = new javax.swing.JScrollPane();
        lstVehicle = new javax.swing.JList();
        lblLicPlate = new javax.swing.JLabel();
        txtLicPlate = new javax.swing.JTextField();
        btnVSave = new javax.swing.JButton();
        btnVRemove = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(VRView1.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnTAgent.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnTAgent.border.title"))); // NOI18N
        pnTAgent.setName("pnTAgent"); // NOI18N

        spTAgent.setName("spTAgent"); // NOI18N

        lstTAgent.setModel(getTAModel());
        lstTAgent.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof TransportAgent) {
                    TransportAgent ta = (TransportAgent)value;
                    setText(ta.getName());
                }
                return this;
            }
        });
        lstTAgent.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTAgent.setName("lstTAgent"); // NOI18N
        lstTAgent.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTAgentValueChanged(evt);
            }
        });
        spTAgent.setViewportView(lstTAgent);

        lblAName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAName.setText(resourceMap.getString("lblAName.text")); // NOI18N
        lblAName.setName("lblAName"); // NOI18N

        lblAAbbr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAAbbr.setText(resourceMap.getString("lblAAbbr.text")); // NOI18N
        lblAAbbr.setName("lblAAbbr"); // NOI18N

        txtAName.setText(resourceMap.getString("txtAName.text")); // NOI18N
        txtAName.setName("txtAName"); // NOI18N
        txtAName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtANameFocusGained(evt);
            }
        });
        txtAName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtANameKeyReleased(evt);
            }
        });

        txtAAbbr.setText(resourceMap.getString("txtAAbbr.text")); // NOI18N
        txtAAbbr.setName("txtAAbbr"); // NOI18N
        txtAAbbr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAAbbrFocusGained(evt);
            }
        });
        txtAAbbr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAAbbrKeyReleased(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(VRView1.class, this);
        btnASave.setAction(actionMap.get("saveAgent")); // NOI18N
        btnASave.setText(resourceMap.getString("btnASave.text")); // NOI18N
        btnASave.setName("btnASave"); // NOI18N

        btnARemove.setText(resourceMap.getString("btnARemove.text")); // NOI18N
        btnARemove.setName("btnARemove"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstTAgent, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnARemove, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnARemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnARemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTAgentLayout = new javax.swing.GroupLayout(pnTAgent);
        pnTAgent.setLayout(pnTAgentLayout);
        pnTAgentLayout.setHorizontalGroup(
            pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(pnTAgentLayout.createSequentialGroup()
                        .addGroup(pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAAbbr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAAbbr, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txtAName, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTAgentLayout.createSequentialGroup()
                        .addComponent(btnARemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnASave)))
                .addContainerGap())
        );
        pnTAgentLayout.setVerticalGroup(
            pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTAgentLayout.createSequentialGroup()
                .addComponent(spTAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAName)
                    .addComponent(txtAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAAbbr)
                    .addComponent(txtAAbbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnTAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnASave)
                    .addComponent(btnARemove))
                .addContainerGap())
        );

        pnVehicle.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnVehicle.border.title"))); // NOI18N
        pnVehicle.setName("pnVehicle"); // NOI18N

        spVehicle.setName("spVehicle"); // NOI18N

        lstVehicle.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Vehicle) {
                    Vehicle ta = (Vehicle)value;
                    setText(ta.getSoXe());
                }
                return this;
            }
        });
        lstVehicle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVehicle.setName("lstVehicle"); // NOI18N
        lstVehicle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVehicleValueChanged(evt);
            }
        });
        spVehicle.setViewportView(lstVehicle);

        lblLicPlate.setText(resourceMap.getString("lblLicPlate.text")); // NOI18N
        lblLicPlate.setName("lblLicPlate"); // NOI18N

        txtLicPlate.setText(resourceMap.getString("txtLicPlate.text")); // NOI18N
        txtLicPlate.setName("txtLicPlate"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstTAgent, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtLicPlate, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtLicPlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicPlateFocusGained(evt);
            }
        });
        txtLicPlate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicPlateKeyReleased(evt);
            }
        });

        btnVSave.setAction(actionMap.get("saveVehicle")); // NOI18N
        btnVSave.setText(resourceMap.getString("btnVSave.text")); // NOI18N
        btnVSave.setName("btnVSave"); // NOI18N

        btnVRemove.setText(resourceMap.getString("btnVRemove.text")); // NOI18N
        btnVRemove.setName("btnVRemove"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lstVehicle, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnVRemove, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnVRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnVehicleLayout = new javax.swing.GroupLayout(pnVehicle);
        pnVehicle.setLayout(pnVehicleLayout);
        pnVehicleLayout.setHorizontalGroup(
            pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(pnVehicleLayout.createSequentialGroup()
                        .addComponent(btnVRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnVSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnVehicleLayout.createSequentialGroup()
                        .addComponent(lblLicPlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicPlate, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnVehicleLayout.setVerticalGroup(
            pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVehicleLayout.createSequentialGroup()
                .addComponent(spVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicPlate)
                    .addComponent(txtLicPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVSave)
                    .addComponent(btnVRemove))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnTAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtANameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANameKeyReleased
        setACreatable(validateTA());
    }//GEN-LAST:event_txtANameKeyReleased

    private void txtAAbbrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAAbbrKeyReleased
        setACreatable(validateTA());
    }//GEN-LAST:event_txtAAbbrKeyReleased

    private void lstTAgentValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTAgentValueChanged
        tAgent = (TransportAgent) lstTAgent.getSelectedValue();
        if (tAgent != null) {
            vehicle = null;
            lstVehicle.clearSelection();
            lstVehicle.setModel(getVModel());
        }
    }//GEN-LAST:event_lstTAgentValueChanged

    private void lstVehicleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVehicleValueChanged
        vehicle = (Vehicle) lstVehicle.getSelectedValue();
    }//GEN-LAST:event_lstVehicleValueChanged

    private void txtLicPlateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicPlateKeyReleased
        setVCreatable(validateLicPlate());
    }//GEN-LAST:event_txtLicPlateKeyReleased

    private void txtANameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtANameFocusGained
        lstTAgent.clearSelection();
        lstVehicle.clearSelection();
        lstVehicle.setModel(new DefaultListModel());
        tAgent = null;
        vehicle = null;
    }//GEN-LAST:event_txtANameFocusGained

    private void txtAAbbrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAAbbrFocusGained
        lstTAgent.clearSelection();
        lstVehicle.clearSelection();
        lstVehicle.setModel(new DefaultListModel());
        tAgent = null;
        vehicle = null;
    }//GEN-LAST:event_txtAAbbrFocusGained

    private void txtLicPlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicPlateFocusGained
        lstVehicle.clearSelection();
        vehicle = null;
    }//GEN-LAST:event_txtLicPlateFocusGained

private void btnVRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVRemoveActionPerformed
// TODO add your handling code here:
    if (!entityManager.getTransaction().isActive()) {
        entityManager.getTransaction().begin();
    }
    entityManager.remove(vehicle);
    entityManager.getTransaction().commit();

    entityManager.clear();
    lstVehicle.clearSelection();
    lstVehicle.setModel(getVModel());
    vehicle = null;
}//GEN-LAST:event_btnVRemoveActionPerformed

private void btnARemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnARemoveActionPerformed
// TODO add your handling code here:
    if (tAgent == null) {
        return;
    }
    String abbr = tAgent.getAbbr();
    tAgent = null;
    entityManager.clear();
    int answer = JOptionPane.showConfirmDialog(
            rootPane,
            "Danh sách xe sẽ bị xóa theo đơn vị vận chuyển"
            + ".Bạn có muốn tiếp tục?",
            JOptionPane.OPTIONS_PROPERTY,
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
    if (answer == JOptionPane.YES_OPTION) {
        TypedQuery<Vehicle> vehTq = entityManager.createNamedQuery("Vehicle.findByTaAbbr", Vehicle.class);
        vehTq.setParameter("taAbbr", abbr);
        List<Vehicle> lVeh = vehTq.getResultList();
        int i = 0;
        try {
            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
            for (Vehicle v : lVeh) {
                entityManager.remove(v);
                i++;
            }
            if (i >= 1) {
                entityManager.getTransaction().commit();
                //entityManager.clear();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(WeighBridgeApp.getApplication().getMainFrame(), "Xóa phương tiện vận chuyển không thành công");
            return;
        }
        try {
            TransportAgent tmpAgent = entityManager.find(TransportAgent.class, abbr);
            if (tmpAgent != null) {
                if (!entityManager.getTransaction().isActive()) {
                    entityManager.getTransaction().begin();
                }
                //entityManager.setProperty("tAgent", tAgent);
                entityManager.remove(tmpAgent);
                entityManager.getTransaction().commit();
//                entityManager.clear();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(WeighBridgeApp.getApplication().getMainFrame(), "Xóa nhà vận chuyển không thành công");
//            System.out.println(ex);
            return;
        }
        entityManager.clear();
        lstVehicle.clearSelection();
        lstVehicle.setModel(new DefaultListModel());
        lstTAgent.clearSelection();
        lstTAgent.setModel(getTAModel());
        tAgent = null;
        vehicle = null;
    }
}//GEN-LAST:event_btnARemoveActionPerformed

    private boolean validateLicPlate() {
        boolean bLicPlate = false;

        Matcher m = patLicPlate.matcher(txtLicPlate.getText().trim());
        Matcher m_new = patLicPlatenew.matcher(txtLicPlate.getText().trim());
        bLicPlate = !(txtLicPlate.getText().trim().isEmpty());// || !(m.matches() || m_new.matches()));
        if (bLicPlate) {
            lblLicPlate.setForeground(Color.black);
        } else {
            lblLicPlate.setForeground(Color.red);
        }

        return bLicPlate;
    }

    private boolean validateTA() {
        boolean bTAName = false, bTAAbbr = false;
        bTAName = !(txtAName.getText().trim().isEmpty());
        if (bTAName) {
            lblAName.setForeground(Color.black);
        } else {
            lblAName.setForeground(Color.red);
        }

        Matcher m = patAAbbr.matcher(txtAAbbr.getText().trim());

        bTAAbbr = !(txtAAbbr.getText().trim().isEmpty() || txtAAbbr.getText().trim().length() > 10 || !m.matches());
        if (bTAAbbr) {
            lblAAbbr.setForeground(Color.black);
        } else {
            lblAAbbr.setForeground(Color.red);
        }

        return bTAName && bTAAbbr;
    }

    private DefaultListModel getTAModel() {
        TypedQuery<TransportAgent> tq = entityManager.createNamedQuery("TransportAgent.findAll", TransportAgent.class);
        List<TransportAgent> tAgents = tq.getResultList();
        DefaultListModel model = new DefaultListModel();
        for (TransportAgent tagent : tAgents) {
            model.addElement(tagent);
        }
        return model;
    }

    private DefaultListModel getVModel() {
        TypedQuery<Vehicle> tq = entityManager.createNamedQuery("Vehicle.findByTaAbbr", Vehicle.class);
        tq.setParameter("taAbbr", tAgent.getAbbr());
        List<Vehicle> vehicles = tq.getResultList();
        DefaultListModel model = new DefaultListModel();
        for (Vehicle vh : vehicles) {
            model.addElement(vh);
        }
        return model;
    }

    @Action(enabledProperty = "aCreatable")
    public void saveAgent() {
        TransportAgent ta = entityManager.find(TransportAgent.class, txtAAbbr.getText().trim());
        if (ta == null) {
            ta = new TransportAgent();
            ta.setAbbr(txtAAbbr.getText().trim());
            ta.setName(txtAName.getText().trim());
            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
            entityManager.persist(ta);
            entityManager.getTransaction().commit();
            entityManager.clear();
            lstTAgent.clearSelection();
            tAgent = null;
            vehicle = null;
            txtAAbbr.setText("");
            txtAName.setText("");
            txtLicPlate.setText("");
            lstTAgent.setModel(getTAModel());
            lstVehicle.clearSelection();
            lstVehicle.setModel(new DefaultListModel());
            setACreatable(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Đơn vị vận chuyển với số "
                    + "SAP Vendor Nr. \"" + txtAAbbr.getText().trim() + "\" đã được đăng ký!");
        }
    }

    @Action
    public void delAgent() {
        if (tAgent == null) {
            return;
        }
        int answer = JOptionPane.showConfirmDialog(
                rootPane,
                "Danh sách xe sẽ bị xóa theo đơn vị vận chuyển"
                + ".Bạn có muốn tiếp tục?",
                JOptionPane.OPTIONS_PROPERTY,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            TypedQuery<Vehicle> vehTq = entityManager.createNamedQuery("Vehicle.findByTaAbbr", Vehicle.class);
            vehTq.setParameter("taAbbr", tAgent.getAbbr());
            List<Vehicle> lVeh = vehTq.getResultList();
            int i = 0;
            try {
                if (!entityManager.getTransaction().isActive()) {
                    entityManager.getTransaction().begin();
                }
                for (Vehicle v : lVeh) {
                    entityManager.remove(v);
                    i++;
                }
                if (i >= 1) {
                    entityManager.getTransaction().commit();
                    //entityManager.clear();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(WeighBridgeApp.getApplication().getMainFrame(), "Xóa phương tiện vận chuyển không thành công");
                return;
            }
            try {
                TransportAgent tmpAgent = entityManager.find(TransportAgent.class, tAgent.getAbbr().toString());
                if (tmpAgent != null) {
                    if (!entityManager.getTransaction().isActive()) {
                        entityManager.getTransaction().begin();
                    }
                    //entityManager.setProperty("tAgent", tAgent);
                    entityManager.remove(tmpAgent);
                    entityManager.getTransaction().commit();
                    entityManager.clear();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(WeighBridgeApp.getApplication().getMainFrame(), "Xóa nhà vận chuyển không thành công");
                return;
            }
            entityManager.clear();
            lstVehicle.clearSelection();
            lstVehicle.setModel(new DefaultListModel());
            lstTAgent.clearSelection();
            lstTAgent.setModel(getTAModel());
            tAgent = null;
            vehicle = null;
        }
    }

    @Action(enabledProperty = "vCreatable")
    public void saveVehicle() {
        Vehicle v = entityManager.find(Vehicle.class, txtLicPlate.getText().trim());
        if (v == null) {
            v = new Vehicle();
            v.setSoXe(txtLicPlate.getText().trim());
            v.setTaAbbr(tAgent.getAbbr());
            if (!entityManager.getTransaction().isActive()) {
                entityManager.getTransaction().begin();
            }
            entityManager.persist(v);
            entityManager.getTransaction().commit();
            entityManager.clear();
            setVCreatable(false);
            vehicle = null;
            txtLicPlate.setText("");
            lstVehicle.clearSelection();
            lstVehicle.setModel(getVModel());
        } else {
            TransportAgent ta = entityManager.find(TransportAgent.class, v.getTaAbbr());
            if (ta != null) {
                JOptionPane.showMessageDialog(rootPane, "Số xe "
                        + txtLicPlate.getText().trim()
                        + " đã được đăng ký cho đơn vị vận chuyển "
                        + ta.getName());
            }
        }
    }

    @Action
    public void delVehicle() {
        if (!entityManager.getTransaction().isActive()) {
            entityManager.getTransaction().begin();
        }
        entityManager.remove(vehicle);
        entityManager.getTransaction().commit();

        entityManager.clear();
        lstVehicle.clearSelection();
        lstVehicle.setModel(getVModel());
        vehicle = null;
    }

    // <editor-fold defaultstate="collapsed" desc="Form's Properties">
    public boolean isACreatable() {
        return aCreatable;
    }

    public void setACreatable(boolean b) {
        boolean old = isACreatable();
        this.aCreatable = b;
        firePropertyChange("aCreatable", old, isACreatable());
    }

    public boolean isVCreatable() {
        return vCreatable;
    }

    public void setVCreatable(boolean b) {
        boolean old = isVCreatable();
        this.vCreatable = b;
        firePropertyChange("vCreatable", old, isVCreatable());
    }
    // </editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnARemove;
    private javax.swing.JButton btnASave;
    private javax.swing.JButton btnVRemove;
    private javax.swing.JButton btnVSave;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblAAbbr;
    private javax.swing.JLabel lblAName;
    private javax.swing.JLabel lblLicPlate;
    private javax.swing.JList lstTAgent;
    private javax.swing.JList lstVehicle;
    private javax.swing.JPanel pnTAgent;
    private javax.swing.JPanel pnVehicle;
    private javax.swing.JScrollPane spTAgent;
    private javax.swing.JScrollPane spVehicle;
    private com.gcs.wb.jpa.entity.TransportAgent tAgent;
    private javax.swing.JTextField txtAAbbr;
    private javax.swing.JTextField txtAName;
    private javax.swing.JTextField txtLicPlate;
    private com.gcs.wb.jpa.entity.Vehicle vehicle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private boolean aCreatable = false;
    private boolean vCreatable = false;
    private static final Pattern patLicPlate = Pattern.compile("\\d{2}[A-Z]-\\d{4}");
    private static final Pattern patLicPlatenew = Pattern.compile("\\d{2}[A-Z]-\\S+"); //+20110309#01
    private static final Pattern patAAbbr = Pattern.compile("[0-9A-Z]{1,10}");
}
