/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WeightTicketReportView.java
 *
 * Created on 06-01-2020
 */
package com.gcs.wb.views;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.jpa.controller.WeightTicketJpaController;
import com.gcs.wb.jpa.entity.Material;
import com.gcs.wb.jpa.entity.MaterialPK;
import com.gcs.wb.jpa.entity.TransportAgent;
import com.gcs.wb.jpa.entity.WeightTicket;
import java.awt.Component;
import java.util.List;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import com.gcs.wb.utils.FormatRenderer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;
import org.jdesktop.application.Application;

/**
 *
 * @author thanghl
 */
public class WeightTicketReportView extends javax.swing.JInternalFrame {

    /** Creates new form WeightTicketReportView */
    public WeightTicketReportView() {
        initComponents();
        // <editor-fold defaultstate="collapsed" desc="Init. Month combobox">
        DefaultComboBoxModel monthModel = new DefaultComboBoxModel();
        for (int i = 1; i <= 12; i++) {
            String month = i < 10 ? "0" + String.valueOf(i) : String.valueOf(i);
            monthModel.addElement(month);
        }
        int currMonth = Calendar.getInstance().get(Calendar.MONTH) + 1;
        monthModel.setSelectedItem(currMonth < 10 ? "0" + String.valueOf(currMonth) : String.valueOf(currMonth));
        cbxMonth.setModel(monthModel);
        // </editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Init. Year Combobox">
        DefaultComboBoxModel yearModel = new DefaultComboBoxModel();
        int currYear = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = currYear - 10; i < currYear + 10; i++) {
            yearModel.addElement(String.valueOf(i));
        }
        yearModel.setSelectedItem(currYear);
        cbxYear.setModel(yearModel);
        // </editor-fold>
        btnFind.setEnabled(true);

        // Init mode combobox
        cbxMode.setModel(new DefaultComboBoxModel(modesModel));
        modes = new ArrayList<Character>();
        modes.add('I');
        modes.add('O');

        // Init state combobox
        cbxStatus.setModel(new DefaultComboBoxModel(statusModel));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        pnFilter = new javax.swing.JPanel();
        pnMY = new javax.swing.JPanel();
        lblMonth = new javax.swing.JLabel();
        cbxMonth = new javax.swing.JComboBox();
        lblYear = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox();
        btnFind = new javax.swing.JButton();
        pnExtra = new javax.swing.JPanel();
        lblTAgent = new javax.swing.JLabel();
        cbxTransportAgent = new javax.swing.JComboBox();
        lblType = new javax.swing.JLabel();
        cbxMaterial = new javax.swing.JComboBox();
        lblMode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        cbxMode = new javax.swing.JComboBox();
        cbxStatus = new javax.swing.JComboBox();
        pnResult = new javax.swing.JPanel();
        spTabResult = new javax.swing.JScrollPane();
        tabWeightTicket = new org.jdesktop.swingx.JXTable();
        pnControl = new javax.swing.JPanel();
        btnPrintReport = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(WeightTicketReportView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnFilter.border.title"))); // NOI18N
        pnFilter.setName("pnFilter"); // NOI18N

        pnMY.setName("pnMY"); // NOI18N

        lblMonth.setText(resourceMap.getString("lblMonth.text")); // NOI18N
        lblMonth.setName("lblMonth"); // NOI18N

        cbxMonth.setName("cbxMonth"); // NOI18N

        lblYear.setText(resourceMap.getString("lblYear.text")); // NOI18N
        lblYear.setName("lblYear"); // NOI18N

        cbxYear.setName("cbxYear"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(WeightTicketReportView.class, this);
        btnFind.setAction(actionMap.get("findWeightTickets")); // NOI18N
        btnFind.setText(resourceMap.getString("btnFind.text")); // NOI18N
        btnFind.setName("btnFind"); // NOI18N

        javax.swing.GroupLayout pnMYLayout = new javax.swing.GroupLayout(pnMY);
        pnMY.setLayout(pnMYLayout);
        pnMYLayout.setHorizontalGroup(
            pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMYLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYear)
                    .addComponent(lblMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFind)
                    .addComponent(cbxMonth, 0, 65, Short.MAX_VALUE)
                    .addComponent(cbxYear, 0, 65, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMYLayout.setVerticalGroup(
            pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMYLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonth)
                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnExtra.setName("pnExtra"); // NOI18N

        lblTAgent.setText(resourceMap.getString("lblTAgent.text")); // NOI18N
        lblTAgent.setName("lblTAgent"); // NOI18N

        cbxTransportAgent.setModel(getTransportAgentsModel());
        cbxTransportAgent.setName("cbxTransportAgent"); // NOI18N
        cbxTransportAgent.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof TransportAgent) {
                    TransportAgent tagent = (TransportAgent)value;
                    setText(tagent.getName());
                    setToolTipText(tagent.getAbbr());
                }
                return this;
            }
        });

        lblType.setText(resourceMap.getString("lblType.text")); // NOI18N
        lblType.setName("lblType"); // NOI18N

        cbxMaterial.setModel(getMaterialsModel());
        cbxMaterial.setName("cbxMaterial"); // NOI18N
        cbxMaterial.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Material) {
                    Material mat = (Material)value;
                    setText(mat.getMaktx());
                    setToolTipText(mat.getMaterialPK().getMatnr());
                }
                return this;
            }
        });

        lblMode.setText(resourceMap.getString("lblMode.text")); // NOI18N
        lblMode.setName("lblMode"); // NOI18N

        lblState.setText(resourceMap.getString("lblState.text")); // NOI18N
        lblState.setName("lblState"); // NOI18N

        cbxMode.setName("cbxMode"); // NOI18N
        cbxMode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModeItemStateChanged(evt);
            }
        });

        cbxStatus.setName("cbxStatus"); // NOI18N

        javax.swing.GroupLayout pnExtraLayout = new javax.swing.GroupLayout(pnExtra);
        pnExtra.setLayout(pnExtraLayout);
        pnExtraLayout.setHorizontalGroup(
            pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTAgent)
                    .addComponent(lblType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMaterial, 0, 217, Short.MAX_VALUE)
                    .addComponent(cbxTransportAgent, 0, 217, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMode)
                    .addComponent(lblState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStatus, 0, 89, Short.MAX_VALUE)
                    .addComponent(cbxMode, 0, 89, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnExtraLayout.setVerticalGroup(
            pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTAgent)
                    .addComponent(cbxTransportAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMode)
                    .addComponent(cbxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cbxMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnFilterLayout = new javax.swing.GroupLayout(pnFilter);
        pnFilter.setLayout(pnFilterLayout);
        pnFilterLayout.setHorizontalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnFilterLayout.setVerticalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnMY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnResult.setName("pnResult"); // NOI18N
        pnResult.setLayout(new java.awt.BorderLayout());

        spTabResult.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("spTabResult.border.title"))); // NOI18N
        spTabResult.setName("spTabResult"); // NOI18N

        tabWeightTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabWeightTicket.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabWeightTicket.setEditable(false);
        tabWeightTicket.setName("tabWeightTicket"); // NOI18N
        tabWeightTicket.setShowGrid(true);
        spTabResult.setViewportView(tabWeightTicket);
        tabWeightTicket.setDefaultRenderer(Date.class, FormatRenderer.getDateTimeRenderer());

        pnResult.add(spTabResult, java.awt.BorderLayout.CENTER);

        pnControl.setName("pnControl"); // NOI18N
        pnControl.setLayout(new javax.swing.BoxLayout(pnControl, javax.swing.BoxLayout.LINE_AXIS));

        btnPrintReport.setAction(actionMap.get("printReport")); // NOI18N
        btnPrintReport.setText(resourceMap.getString("btnPrintReport.text")); // NOI18N
        btnPrintReport.setName("btnPrintReport"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tabWeightTicket, org.jdesktop.beansbinding.ELProperty.create("${rowCount > 0}"), btnPrintReport, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        pnControl.add(btnPrintReport);

        pnResult.add(pnControl, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(pnFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnResult, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cbxModeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModeItemStateChanged
    modes = new ArrayList<Character>();
    switch (cbxMode.getSelectedIndex()) {
        case 0:
            modes.add('I');
            modes.add('O');
            break;
        case 1:
            modes.add('I');
            break;
        case 2:
            modes.add('O');
            break;
    }
}//GEN-LAST:event_cbxModeItemStateChanged

    private DefaultComboBoxModel getTransportAgentsModel() {
        TypedQuery<TransportAgent> typedQuery = entityManager.createNamedQuery("TransportAgent.findAll", TransportAgent.class);
        List<TransportAgent> listTransportAgents = typedQuery.getResultList();
        return new DefaultComboBoxModel(listTransportAgents.toArray());
    }

    private DefaultComboBoxModel getMaterialsModel() {
        DefaultComboBoxModel result = new DefaultComboBoxModel();
        Query query = entityManager.createNativeQuery("select distinct MATNR_REF, REG_ITEM_TEXT from WeightTicket where MANDT = ? and WPlant = ?");
        query.setParameter(1, WeighBridgeApp.getApplication().getConfig().getsClient());
        query.setParameter(2, WeighBridgeApp.getApplication().getConfig().getwPlant());
        List weightTickets = query.getResultList();
        for (Object obj : weightTickets) {
            Object[] weightTicket = (Object[]) obj;
            MaterialPK materialPK = new MaterialPK();
            Material material = new Material();
            materialPK.setMandt(WeighBridgeApp.getApplication().getConfig().getsClient());
            if (weightTicket[0] == null) {
                materialPK.setMatnr("-1");
                material.setMaktx("Linh tinh");
            } else {
                materialPK.setMatnr(weightTicket[0].toString());
                material.setMaktx(weightTicket[1].toString());
            }
            material.setMaterialPK(materialPK);
            if (result.getIndexOf(material) < 0) {
                result.addElement(material);
            }
        }
        return result;
    }

    @Action
    public Task findWeightTickets() {
        return new FindWeightTicketsTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class FindWeightTicketsTask extends Task<Object, Void> {

        FindWeightTicketsTask(Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            String month = cbxMonth.getSelectedItem().toString();
            String year = cbxYear.getSelectedItem().toString();
            String tAgent = ((TransportAgent) cbxTransportAgent.getSelectedItem()).getAbbr();
            String matnr = ((Material) cbxMaterial.getSelectedItem()).getMaterialPK().getMatnr();
            try {
                WeightTicketJpaController weightTicketJpaController = new WeightTicketJpaController(entityManager);
                List<WeightTicket> weightTickets = weightTicketJpaController.findListWTs(month, year, tAgent, matnr, modes, cbxStatus.getSelectedIndex() == 1, cbxStatus.getSelectedIndex() == 2);
                wtDatas = new Object[weightTickets.size()][wtColNames.length];
                for (int i = 0; i < weightTickets.size(); i++) {
                    WeightTicket item = weightTickets.get(i);
                    String hh = item.getCreateTime().substring(0, 2);
                    String mm = item.getCreateTime().substring(2, 4);
                    String ss = item.getCreateTime().substring(4);
                    Calendar create_date = Calendar.getInstance();
                    create_date.setTime(item.getCreateDate());
                    create_date.set(Calendar.HOUR_OF_DAY, Integer.valueOf(hh));
                    create_date.set(Calendar.MINUTE, Integer.valueOf(mm));
                    create_date.set(Calendar.SECOND, Integer.valueOf(ss));
                    wtDatas[i][0] = i + 1;// item.getSeqByMonth();
                    wtDatas[i][1] = item.getWeightTicketPK().getSeqByDay();
                    wtDatas[i][2] = item.getTenTaiXe();
                    wtDatas[i][3] = item.getCmndBl();
                    wtDatas[i][4] = item.getSoXe();
                    wtDatas[i][5] = item.getSoRomooc();
                    wtDatas[i][6] = item.getCreator();
                    wtDatas[i][7] = create_date.getTime();
                    wtDatas[i][8] = item.getRegCategory();
                    wtDatas[i][9] = item.getRegItemText();
                    wtDatas[i][10] = item.getFTime();
                    wtDatas[i][11] = item.getFScale() == null ? item.getFScale() : item.getFScale().doubleValue() / 1000d;
                    wtDatas[i][12] = item.getSTime();
                    wtDatas[i][13] = item.getSScale() == null ? item.getSScale() : item.getSScale().doubleValue() / 1000d;
                    wtDatas[i][14] = item.getGQty();
                    wtDatas[i][15] = item.getDelivNumb();
                    wtDatas[i][16] = item.getMatDoc();
                    wtDatas[i][17] = item.getDissolved();
//                    wtDatas[i][18] = item.getPosted();
                    if (item.getPosted() == 1) {
                        wtDatas[i][18] = true;
                    } else {
                        wtDatas[i][18] = false;
                    }
                    wtDatas[i][19] = ((TransportAgent) cbxTransportAgent.getSelectedItem()).getName();
                    wtDatas[i][20] = item.getEbeln();
                }
                editable = new boolean[wtColNames.length];
                for (int i = 0; i < editable.length; i++) {
                    editable[i] = false;
                }
            } catch (Exception ex) {
                failed(ex);
            }
            return null;  // return your result
        }

        @Override
        protected void failed(Throwable cause) {
        }

        @Override
        protected void finished() {
            setMessage("Hoàn tất...");
            WeighBridgeApp.getApplication().bindJTableModel(tabWeightTicket, wtDatas, wtColNames, wtColTypes, editable);
        }
    }

    @Action
    public Task printReport() {
        return new PrintReportTask(Application.getInstance(WeighBridgeApp.class));
    }

    private class PrintReportTask extends Task<Object, Void> {

        PrintReportTask(Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            try {
                Map<String, Object> params = new HashMap<String, Object>();
                params.put("P_PNAME_RPT", WeighBridgeApp.getApplication().getSapSetting().getNameRpt());
                params.put("P_PADDRESS", WeighBridgeApp.getApplication().getSapSetting().getAddress());
                params.put("P_PPHONE", WeighBridgeApp.getApplication().getSapSetting().getPhone());
                params.put("P_PFAX", WeighBridgeApp.getApplication().getSapSetting().getFax());
                params.put("P_TAGENT", ((TransportAgent) cbxTransportAgent.getSelectedItem()).getName());
                params.put("P_MONTH", cbxMonth.getSelectedItem().toString());
                params.put("P_YEAR", cbxYear.getSelectedItem().toString());
                String reportName = null;
                if (WeighBridgeApp.getApplication().getConfig().getModeNormal()) {
                    reportName = "./rpt/rptBT/WTList.jasper";
                } else {
                    reportName = "./rpt/rptPQ/WTList.jasper";
                }

                JasperPrint jasperPrint = JasperFillManager.fillReport(reportName, params, new JRTableModelDataSource(tabWeightTicket.getModel()));
                JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                jasperViewer.setVisible(true);
            } catch (Exception ex) {
                failed(ex);
            }
            return null;  // return your result
        }

        @Override
        protected void failed(Throwable cause) {
            logger.error(null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnPrintReport;
    private javax.swing.JComboBox cbxMaterial;
    private javax.swing.JComboBox cbxMode;
    private javax.swing.JComboBox cbxMonth;
    private javax.swing.JComboBox cbxStatus;
    private javax.swing.JComboBox cbxTransportAgent;
    private javax.swing.JComboBox cbxYear;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTAgent;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnControl;
    private javax.swing.JPanel pnExtra;
    private javax.swing.JPanel pnFilter;
    private javax.swing.JPanel pnMY;
    private javax.swing.JPanel pnResult;
    private javax.swing.JScrollPane spTabResult;
    private org.jdesktop.swingx.JXTable tabWeightTicket;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private static Logger logger = Logger.getLogger(WeightTicketReportView.class);
    private boolean[] editable = null;
    private List<Character> modes = null;
    private String[] modesModel = {"Tất cả", "Nhập", "Xuất"};
    private String[] statusModel = {"Tất cả", "Bị hủy", "Hoàn tất"};
    Object[][] wtDatas = null;
    Object[] wtColNames = new String[]{
        "STT",
        "S.Đ.Tài",
        "Tên tài xế",
        "CMND/BL",
        "Số Xe",
        "Số Rơmoóc",
        "Người tạo",
        "Ngày giờ tạo",
        "Nhập/Xuất(I/O)",
        "Loại hàng",
        "Ngày giờ vào",
        "T.L vào",
        "Ngày giờ ra",
        "T.L ra",
        "T.L Hàng",
        "Số D.O",
        "Số chứng từ SAP",
        "Hủy",
        "SAP Posted",
        "DVVC",
        "Số P.O"};
    Class[] wtColTypes = new Class[]{
        Integer.class,
        Integer.class,
        String.class,
        String.class,
        String.class,
        String.class,
        String.class,
        Date.class,
        Character.class,
        String.class,
        Date.class,
        BigDecimal.class,
        Date.class,
        BigDecimal.class,
        BigDecimal.class,
        String.class,
        String.class,
        Boolean.class,
        Boolean.class,
        String.class,
        String.class};
}
