/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WTListView.java
 *
 * Created on 03-06-2010, 14:52:38
 */
package com.gcs.wb.views;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.jpa.controller.WeightTicketJpaController;
import com.gcs.wb.jpa.entity.Material;
import com.gcs.wb.jpa.entity.MaterialPK;
import com.gcs.wb.jpa.entity.TransportAgent;
import com.gcs.wb.jpa.entity.WeightTicket;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import com.gcs.wb.utils.FormatRenderer;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;

/**
 *
 * @author vunguyent
 */
public class WTListView extends javax.swing.JInternalFrame {

    /** Creates new form WTListView */
    public WTListView() {
        initComponents();
        // <editor-fold defaultstate="collapsed" desc="Init. Month combobox">
        DefaultComboBoxModel monthModel = new DefaultComboBoxModel();
        for (int i = 1; i <= 12; i++) {
            String month = i < 10 ? "0" + String.valueOf(i) : String.valueOf(i);
            monthModel.addElement(month);
        }
        int currMonth = Calendar.getInstance().get(Calendar.MONTH) + 1;
        monthModel.setSelectedItem(currMonth < 10 ? "0" + String.valueOf(currMonth) : String.valueOf(currMonth));
        cbxMonth.setModel(monthModel);
        // </editor-fold>
        // <editor-fold defaultstate="collapsed" desc="Init. Year Combobox">
        DefaultComboBoxModel yearModel = new DefaultComboBoxModel();
        int currYear = Calendar.getInstance().get(Calendar.YEAR);
        for (int i = currYear - 10; i < currYear + 10; i++) {
            yearModel.addElement(String.valueOf(i));
        }
        yearModel.setSelectedItem(currYear);
        cbxYear.setModel(yearModel);
        // </editor-fold>
        btnFind.setEnabled(false); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        rbtModeGroup = new javax.swing.ButtonGroup();
        rbtStateGroup = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        pnFilter = new javax.swing.JPanel();
        pnMY = new javax.swing.JPanel();
        lblMonth = new javax.swing.JLabel();
        cbxMonth = new javax.swing.JComboBox();
        lblYear = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox();
        pnExtra = new javax.swing.JPanel();
        lblTAgent = new javax.swing.JLabel();
        cbxTAgent = new javax.swing.JComboBox();
        lblType = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox();
        lblMode = new javax.swing.JLabel();
        rbtInward = new javax.swing.JRadioButton();
        rbtOutward = new javax.swing.JRadioButton();
        rbtModeAll = new javax.swing.JRadioButton();
        lblState = new javax.swing.JLabel();
        rbtDissolved = new javax.swing.JRadioButton();
        rbtPosted = new javax.swing.JRadioButton();
        rbtStateAll = new javax.swing.JRadioButton();
        btnFind = new javax.swing.JButton();
        pnResult = new javax.swing.JPanel();
        spTabResult = new javax.swing.JScrollPane();
        tabWTList = new org.jdesktop.swingx.JXTable();
        pnControl = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(WTListView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        pnFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("pnFilter.border.title"))); // NOI18N
        pnFilter.setName("pnFilter"); // NOI18N

        pnMY.setName("pnMY"); // NOI18N

        lblMonth.setText(resourceMap.getString("lblMonth.text")); // NOI18N
        lblMonth.setName("lblMonth"); // NOI18N

        cbxMonth.setName("cbxMonth"); // NOI18N

        lblYear.setText(resourceMap.getString("lblYear.text")); // NOI18N
        lblYear.setName("lblYear"); // NOI18N

        cbxYear.setName("cbxYear"); // NOI18N

        javax.swing.GroupLayout pnMYLayout = new javax.swing.GroupLayout(pnMY);
        pnMY.setLayout(pnMYLayout);
        pnMYLayout.setHorizontalGroup(
            pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMYLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYear)
                    .addComponent(lblMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxMonth, 0, 65, Short.MAX_VALUE)
                    .addComponent(cbxYear, 0, 65, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMYLayout.setVerticalGroup(
            pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMYLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonth)
                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnExtra.setName("pnExtra"); // NOI18N

        lblTAgent.setText(resourceMap.getString("lblTAgent.text")); // NOI18N
        lblTAgent.setName("lblTAgent"); // NOI18N

        cbxTAgent.setModel(getTAgentsModel());
        cbxTAgent.setName("cbxTAgent"); // NOI18N
        cbxTAgent.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof TransportAgent) {
                    TransportAgent tagent = (TransportAgent)value;
                    setText(tagent.getName());
                    setToolTipText(tagent.getAbbr());
                }
                return this;
            }
        });

        lblType.setText(resourceMap.getString("lblType.text")); // NOI18N
        lblType.setName("lblType"); // NOI18N

        cbxType.setModel(getMatsModel());
        cbxType.setName("cbxType"); // NOI18N
        cbxType.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Material) {
                    Material mat = (Material)value;
                    setText(mat.getMaktx());
                    setToolTipText(mat.getMaterialPK().getMatnr());
                }
                return this;
            }
        });

        lblMode.setText(resourceMap.getString("lblMode.text")); // NOI18N
        lblMode.setName("lblMode"); // NOI18N

        rbtModeGroup.add(rbtInward);
        rbtInward.setText(resourceMap.getString("rbtInward.text")); // NOI18N
        rbtInward.setName("rbtInward"); // NOI18N
        rbtInward.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtInwardItemStateChanged(evt);
            }
        });

        rbtModeGroup.add(rbtOutward);
        rbtOutward.setText(resourceMap.getString("rbtOutward.text")); // NOI18N
        rbtOutward.setName("rbtOutward"); // NOI18N
        rbtOutward.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtOutwardItemStateChanged(evt);
            }
        });

        rbtModeGroup.add(rbtModeAll);
        rbtModeAll.setText(resourceMap.getString("rbtModeAll.text")); // NOI18N
        rbtModeAll.setName("rbtModeAll"); // NOI18N
        rbtModeAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtModeAllItemStateChanged(evt);
            }
        });

        lblState.setText(resourceMap.getString("lblState.text")); // NOI18N
        lblState.setName("lblState"); // NOI18N

        rbtStateGroup.add(rbtDissolved);
        rbtDissolved.setText(resourceMap.getString("rbtDissolved.text")); // NOI18N
        rbtDissolved.setName("rbtDissolved"); // NOI18N
        rbtDissolved.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtDissolvedItemStateChanged(evt);
            }
        });

        rbtStateGroup.add(rbtPosted);
        rbtPosted.setText(resourceMap.getString("rbtPosted.text")); // NOI18N
        rbtPosted.setName("rbtPosted"); // NOI18N
        rbtPosted.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtPostedItemStateChanged(evt);
            }
        });

        rbtStateGroup.add(rbtStateAll);
        rbtStateAll.setText(resourceMap.getString("rbtStateAll.text")); // NOI18N
        rbtStateAll.setName("rbtStateAll"); // NOI18N
        rbtStateAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtStateAllItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnExtraLayout = new javax.swing.GroupLayout(pnExtra);
        pnExtra.setLayout(pnExtraLayout);
        pnExtraLayout.setHorizontalGroup(
            pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTAgent)
                    .addComponent(lblType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxType, 0, 71, Short.MAX_VALUE)
                    .addComponent(cbxTAgent, 0, 71, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnExtraLayout.createSequentialGroup()
                        .addComponent(lblMode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtInward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtOutward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtModeAll))
                    .addGroup(pnExtraLayout.createSequentialGroup()
                        .addComponent(lblState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtDissolved)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtPosted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtStateAll)))
                .addContainerGap())
        );
        pnExtraLayout.setVerticalGroup(
            pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTAgent)
                    .addComponent(cbxTAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMode)
                    .addComponent(rbtInward)
                    .addComponent(rbtOutward)
                    .addComponent(rbtModeAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtDissolved)
                    .addComponent(lblState)
                    .addComponent(rbtPosted)
                    .addComponent(rbtStateAll))
                .addContainerGap())
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(WTListView.class, this);
        btnFind.setAction(actionMap.get("findWTs")); // NOI18N
        btnFind.setText(resourceMap.getString("btnFind.text")); // NOI18N
        btnFind.setName("btnFind"); // NOI18N

        javax.swing.GroupLayout pnFilterLayout = new javax.swing.GroupLayout(pnFilter);
        pnFilter.setLayout(pnFilterLayout);
        pnFilterLayout.setHorizontalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addContainerGap())
        );
        pnFilterLayout.setVerticalGroup(
            pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(pnExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pnMY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFind))
        );

        pnResult.setName("pnResult"); // NOI18N
        pnResult.setLayout(new java.awt.BorderLayout());

        spTabResult.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("spTabResult.border.title"))); // NOI18N
        spTabResult.setName("spTabResult"); // NOI18N

        tabWTList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabWTList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabWTList.setEditable(false);
        tabWTList.setName("tabWTList"); // NOI18N
        tabWTList.setShowGrid(true);
        spTabResult.setViewportView(tabWTList);
        tabWTList.setDefaultRenderer(Date.class, FormatRenderer.getDateTimeRenderer());

        pnResult.add(spTabResult, java.awt.BorderLayout.CENTER);

        pnControl.setName("pnControl"); // NOI18N
        pnControl.setLayout(new javax.swing.BoxLayout(pnControl, javax.swing.BoxLayout.LINE_AXIS));

        btnPrint.setAction(actionMap.get("printReport")); // NOI18N
        btnPrint.setText(resourceMap.getString("btnPrint.text")); // NOI18N
        btnPrint.setName("btnPrint"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tabWTList, org.jdesktop.beansbinding.ELProperty.create("${rowCount > 0}"), btnPrint, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        pnControl.add(btnPrint);

        pnResult.add(pnControl, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addComponent(pnFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnResult, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtInwardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtInwardItemStateChanged
        if (rbtInward.isSelected()) {
            modes = new ArrayList<Character>();
            modes.add('I');
        }
    }//GEN-LAST:event_rbtInwardItemStateChanged

    private void rbtOutwardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtOutwardItemStateChanged
        if (rbtOutward.isSelected()) {
            modes = new ArrayList<Character>();
            modes.add('O');
        }
    }//GEN-LAST:event_rbtOutwardItemStateChanged

    private void rbtModeAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtModeAllItemStateChanged
        if (rbtModeAll.isSelected()) {
            modes = new ArrayList<Character>();
            modes.add('O');
            modes.add('I');
        }
    }//GEN-LAST:event_rbtModeAllItemStateChanged

    private void rbtDissolvedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtDissolvedItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtDissolvedItemStateChanged

    private void rbtPostedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtPostedItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPostedItemStateChanged

    private void rbtStateAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtStateAllItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtStateAllItemStateChanged

    private DefaultComboBoxModel getTAgentsModel() {
        DefaultComboBoxModel result = new DefaultComboBoxModel();
        TypedQuery<TransportAgent> tq = entityManager.createNamedQuery("TransportAgent.findAll", TransportAgent.class);
        List<TransportAgent> listTAs = tq.getResultList();
        result = new DefaultComboBoxModel(listTAs.toArray());
        return result;
    }

    private DefaultComboBoxModel getMatsModel() {
        DefaultComboBoxModel result = new DefaultComboBoxModel();
        Query q = entityManager.createNativeQuery("select distinct MATNR_REF, REG_ITEM_TEXT from WeightTicket where MANDT = ? and WPlant = ?");
        q.setParameter(1, WeighBridgeApp.getApplication().getConfig().getsClient());
        q.setParameter(2, WeighBridgeApp.getApplication().getConfig().getwPlant());
        List wts = q.getResultList();
        for (Object obj : wts) {
            Object[] wt = (Object[]) obj;
            MaterialPK matPK = new MaterialPK();
            Material mat = new Material();
            matPK.setMandt(WeighBridgeApp.getApplication().getConfig().getsClient());
            if (wt[0] == null) {
                matPK.setMatnr("-1");
                mat.setMaktx("Linh tinh");
            } else {
                matPK.setMatnr(wt[0].toString());
                mat.setMaktx(wt[1].toString());
            }
            mat.setMaterialPK(matPK);
            if (result.getIndexOf(mat) < 0) {
                result.addElement(mat);
            }
        }
        return result;
    }

    @Action
    public Task findWTs() {
        if (rbtModeGroup.getSelection() == null) {
            lblMode.setForeground(Color.red);
        } else {
            lblMode.setForeground(Color.black);
        }

        if (rbtStateGroup.getSelection() == null) {
            lblState.setForeground(Color.red);
        } else {
            lblState.setForeground(Color.black);
        }

        if (rbtModeGroup.getSelection() == null || rbtStateGroup.getSelection() == null) {
            return null;
        } else {
            return new FindWTsTask(org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class));
        }
    }

    private class FindWTsTask extends org.jdesktop.application.Task<Object, Void> {

        FindWTsTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to FindWTsTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {

            String month = cbxMonth.getSelectedItem().toString();
            String year = cbxYear.getSelectedItem().toString();
            String tagent = ((TransportAgent) cbxTAgent.getSelectedItem()).getAbbr();
            String matnr = ((Material) cbxType.getSelectedItem()).getMaterialPK().getMatnr();
            try {
                WeightTicketJpaController wCon = new WeightTicketJpaController(entityManager);
                List<WeightTicket> wts = wCon.findListWTs(month, year, tagent, matnr, modes, rbtDissolved.isSelected(), rbtPosted.isSelected());
                wtData = new Object[wts.size()][wtCols.length];
                for (int i = 0; i < wts.size(); i++) {
                    WeightTicket item = wts.get(i);
                    String hh;
                    String mm;
                    String ss;
                    hh = item.getCreateTime().substring(0, 2);
                    mm = item.getCreateTime().substring(2, 4);
                    ss = item.getCreateTime().substring(4);
                    Calendar create_date = Calendar.getInstance();
                    create_date.setTime(item.getCreateDate());
                    create_date.set(Calendar.HOUR_OF_DAY, Integer.valueOf(hh));
                    create_date.set(Calendar.MINUTE, Integer.valueOf(mm));
                    create_date.set(Calendar.SECOND, Integer.valueOf(ss));
                    wtData[i][0] = i + 1;// item.getSeqByMonth();
                    wtData[i][1] = item.getWeightTicketPK().getSeqByDay();
                    wtData[i][2] = item.getTenTaiXe();
                    wtData[i][3] = item.getCmndBl();
                    wtData[i][4] = item.getSoXe();
                    wtData[i][5] = item.getSoRomooc();
                    wtData[i][6] = item.getCreator();
                    wtData[i][7] = create_date.getTime();
                    wtData[i][8] = item.getRegCategory();
                    wtData[i][9] = item.getRegItemText();
                    wtData[i][10] = item.getFTime();
                    wtData[i][11] = item.getFScale() == null ? item.getFScale() : item.getFScale().doubleValue() / 1000d;
                    wtData[i][12] = item.getSTime();
                    wtData[i][13] = item.getSScale() == null ? item.getSScale() : item.getSScale().doubleValue() / 1000d;
                    wtData[i][14] = item.getGQty();
                    wtData[i][15] = item.getDelivNumb();
                    wtData[i][16] = item.getMatDoc();
                    wtData[i][17] = item.getDissolved();
//                    wtData[i][18] = item.getPosted();
                    if(item.getPosted() == 1){
                        wtData[i][18] = true;
                    }else{
                        wtData[i][18] = false;
                    }
                    wtData[i][19] = ((TransportAgent) cbxTAgent.getSelectedItem()).getName();
                    wtData[i][20] = item.getEbeln();
                }
                editable = new boolean[wtCols.length];
                for (int i = 0; i < editable.length; i++) {
                    editable[i] = false;
                }
            } catch (Exception ex) {
                failed(ex);
            }
            return null;  // return your result
        }

        @Override
        protected void failed(Throwable cause) {
        }

        @Override
        protected void finished() {
            setMessage("Hoàn tất...");
            WeighBridgeApp.getApplication().bindJTableModel(tabWTList, wtData, wtCols, wtTypes, editable);
        }
    }

    @Action
    public Task printReport() {
        return new PrintReportTask(org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class));
    }

    private class PrintReportTask extends org.jdesktop.application.Task<Object, Void> {

        PrintReportTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to PrintReportTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            try {
                Map<String, Object> params = new HashMap<String, Object>();
                params.put("P_PNAME_RPT", WeighBridgeApp.getApplication().getSapSetting().getNameRpt());
                params.put("P_PADDRESS", WeighBridgeApp.getApplication().getSapSetting().getAddress());
                params.put("P_PPHONE", WeighBridgeApp.getApplication().getSapSetting().getPhone());
                params.put("P_PFAX", WeighBridgeApp.getApplication().getSapSetting().getFax());
                params.put("P_TAGENT", ((TransportAgent) cbxTAgent.getSelectedItem()).getName());
                params.put("P_MONTH", cbxMonth.getSelectedItem().toString());
                params.put("P_YEAR", cbxYear.getSelectedItem().toString());
                String reportName = null;
                if (WeighBridgeApp.getApplication().getConfig().getModeNormal()) {
                    reportName = "./rpt/rptBT/WTList.jasper";
                } else {
                    reportName = "./rpt/rptPQ/WTList.jasper";
                }
                
                JasperPrint jasperPrint = JasperFillManager.fillReport(reportName, params, new JRTableModelDataSource(tabWTList.getModel()));
                JasperViewer jv = new JasperViewer(jasperPrint, false);
                jv.setVisible(true);
            } catch (Exception ex) {
                failed(ex);
            }
            return null;  // return your result
        }

        @Override
        protected void failed(Throwable cause) {
            logger.error(null, cause);
            JOptionPane.showMessageDialog(rootPane, cause.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cbxMonth;
    private javax.swing.JComboBox cbxTAgent;
    private javax.swing.JComboBox cbxType;
    private javax.swing.JComboBox cbxYear;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTAgent;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel pnControl;
    private javax.swing.JPanel pnExtra;
    private javax.swing.JPanel pnFilter;
    private javax.swing.JPanel pnMY;
    private javax.swing.JPanel pnResult;
    private javax.swing.JRadioButton rbtDissolved;
    private javax.swing.JRadioButton rbtInward;
    private javax.swing.JRadioButton rbtModeAll;
    private javax.swing.ButtonGroup rbtModeGroup;
    private javax.swing.JRadioButton rbtOutward;
    private javax.swing.JRadioButton rbtPosted;
    private javax.swing.JRadioButton rbtStateAll;
    private javax.swing.ButtonGroup rbtStateGroup;
    private javax.swing.JScrollPane spTabResult;
    private org.jdesktop.swingx.JXTable tabWTList;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private static Logger logger = Logger.getLogger(WTListView.class);
    private boolean[] editable = null;
    private List<Character> modes = null;
    Object[][] wtData = null;
    Object[] wtCols = new String[]{
        "STT",
        "S.Đ.Tài",
        "Tên tài xế",
        "CMND/BL",
        "Số Xe",
        "Số Rơmoóc",
        "Người tạo",
        "Ngày giờ tạo",
        "Nhập/Xuất(I/O)",
        "Loại hàng",
        "Ngày giờ vào",
        "T.L vào",
        "Ngày giờ ra",
        "T.L ra",
        "T.L Hàng",
        "Số D.O",
        "Số chứng từ SAP",
        "Hủy",
        "SAP Posted",
        "Đơn vị vân chuyển",
        "Số P.O"};
    Class[] wtTypes = new Class[]{
        Integer.class,
        Integer.class,
        String.class,
        String.class,
        String.class,
        String.class,
        String.class,
        Date.class,
        Character.class,
        String.class,
        Date.class,
        BigDecimal.class,
        Date.class,
        BigDecimal.class,
        BigDecimal.class,
        String.class,
        String.class,
        Boolean.class,
        Boolean.class,
        String.class,
        String.class};
}
