/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Mvt311View.java
 *
 * Created on 15-08-2010, 00:01:57
 */
package com.gcs.wb.views;

import com.gcs.wb.WeighBridgeApp;
import com.gcs.wb.bapi.helper.SAP2Local;
import com.gcs.wb.jpa.entity.Material;
import com.gcs.wb.jpa.entity.SLoc;
import com.gcs.wb.jpa.entity.SLocPK;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import org.jdesktop.application.Action;

/**
 *
 * @author vunguyent
 */
public class Mvt311View extends javax.swing.JDialog {

    /** Creates new form Mvt311View */
    public Mvt311View(java.awt.Frame parent, String recv_lgort, Material mat) {
        super(parent);
        initComponents();
        if (recv_lgort != null) {
            SLoc recv_sloc = entityManager.find(SLoc.class, new SLocPK(config.getsClient(), config.getwPlant(), recv_lgort));
            this.recSloc = recv_sloc;
        } else {
            this.recSloc = null;
        }
        if (this.recSloc == null) {
            cbxRecvSloc.setSelectedIndex(-1);
        } else {
            cbxRecvSloc.setSelectedItem(this.recSloc);
        }
        this.selMaterial = mat;
        if (this.selMaterial != null && this.selMaterial.getMaterialPK() != null) {
            txtMatnr.setText(this.selMaterial.getMaterialPK().getMatnr());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        config = WeighBridgeApp.getApplication().getConfig();
        entityManager = java.beans.Beans.isDesignTime() ? null : WeighBridgeApp.getApplication().getEm();
        if(entityManager != null ) entityManager.clear();
        pnContent = new javax.swing.JPanel();
        lblRecvSloc = new javax.swing.JLabel();
        cbxRecvSloc = new javax.swing.JComboBox();
        lblMatnr = new javax.swing.JLabel();
        txtMatnr = new javax.swing.JTextField();
        btnLookup = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        pnContent.setName("pnContent"); // NOI18N

        lblRecvSloc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getResourceMap(Mvt311View.class);
        lblRecvSloc.setText(resourceMap.getString("lblRecvSloc.text")); // NOI18N
        lblRecvSloc.setName("lblRecvSloc"); // NOI18N

        cbxRecvSloc.setModel(SAP2Local.getSlocModel(config, entityManager));
        cbxRecvSloc.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof SLoc) {
                    SLoc sloc = (SLoc)value;
                    setText(sloc.getLgobe());
                }
                return this;
            }
        });
        cbxRecvSloc.setName("cbxRecvSloc"); // NOI18N

        lblMatnr.setText(resourceMap.getString("lblMatnr.text")); // NOI18N
        lblMatnr.setName("lblMatnr"); // NOI18N

        txtMatnr.setEditable(false);
        txtMatnr.setText(resourceMap.getString("txtMatnr.text")); // NOI18N
        txtMatnr.setName("txtMatnr"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.gcs.wb.WeighBridgeApp.class).getContext().getActionMap(Mvt311View.class, this);
        btnLookup.setAction(actionMap.get("lookupMat")); // NOI18N
        btnLookup.setText(resourceMap.getString("btnLookup.text")); // NOI18N
        btnLookup.setName("btnLookup"); // NOI18N

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMatnr)
                    .addComponent(lblRecvSloc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContentLayout.createSequentialGroup()
                        .addComponent(txtMatnr, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLookup))
                    .addComponent(cbxRecvSloc, 0, 559, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecvSloc)
                    .addComponent(cbxRecvSloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatnr)
                    .addComponent(txtMatnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSelect.setAction(actionMap.get("chooseVal")); // NOI18N
        btnSelect.setText(resourceMap.getString("btnSelect.text")); // NOI18N
        btnSelect.setName("btnSelect"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(btnSelect)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelect)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void chooseVal() {
        if (cbxRecvSloc.getSelectedIndex() == -1) {
            setRecSloc(null);
        } else {
            setRecSloc((SLoc) cbxRecvSloc.getSelectedItem());
        }
        dispose();
    }

    @Action
    public void lookupMat() {
        LookupMatView lmat = new LookupMatView(WeighBridgeApp.getApplication().getMainFrame());
        lmat.setLocationRelativeTo(WeighBridgeApp.getApplication().getMainFrame());
        WeighBridgeApp.getApplication().show(lmat);
        if (!lmat.isShowing()) {
            if (lmat.getfMaterial() != null && lmat.getfMaterial().getMaterialPK() != null) {
                txtMatnr.setText(lmat.getfMaterial().getMaterialPK().getMatnr());
                setSelMaterial(lmat.getfMaterial());
            }
            lmat.dispose();
            lmat = null;
        }
    }

    /**
     * @return the recSloc
     */
    public SLoc getRecSloc() {
        return recSloc;
    }

    /**
     * @param recSloc the recSloc to set
     */
    public void setRecSloc(SLoc recSloc) {
        this.recSloc = recSloc;
    }

    /**
     * @return the selMaterial
     */
    public Material getSelMaterial() {
        return selMaterial;
    }

    /**
     * @param selMaterial the selMaterial to set
     */
    public void setSelMaterial(Material selMaterial) {
        this.selMaterial = selMaterial;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLookup;
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox cbxRecvSloc;
    private com.gcs.wb.model.AppConfig config;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel lblMatnr;
    private javax.swing.JLabel lblRecvSloc;
    private javax.swing.JPanel pnContent;
    private javax.swing.JTextField txtMatnr;
    // End of variables declaration//GEN-END:variables
    private SLoc recSloc = null;
    private Material selMaterial = null;
}
